### ISSUE TITLE
Download page: add reference to https://copr.fedoraproject.org/coprs/fabio/jq

### ISSUE THREAD

**Issue by fabio-porcedda** [jqlang/jq#1006]
The latest version is avaiable only on the unreleased Fedora 23

Add reference to the copr repository with the latest version rebuilt for Fedora 21 and Fedora 22.

To enable it use the command:
  sudo dnf copr enable fabio/jq

Thanks
Fabio Porcedda

**Comment by itchyny** [comment]
The url in the title is 404 now, so I'm closing this issue. There is already a command instruction for Fedora in the [Download page](https://jqlang.github.io/jq/download/), but if you think it is not enough, please submit us a PR. Thanks.
