### ISSUE TITLE
how can i get this

### ISSUE THREAD

**Issue by arthur657834** [jqlang/jq#1048]
JSON:

```
{
    "Trigger": "Java",
    "Trigger status": "OK",
    "HOST.IP": "10.10.1.8"
}
```

how can i get the value of HOST.IP  and Trigger severity ?

please help me

**Comment by linquize** [comment]
Is the dot a special char?

**Comment by arthur657834** [comment]
just a dot.
it work on https://jqplay.org/#  ,but cant work on echo '{"foo.1": 42, "bar 1": "less interesting data"}' | jq ."bar 1"
![1](https://cloud.githubusercontent.com/assets/9419700/11911805/11b381d8-a65d-11e5-9bd8-a9443d794f22.png)

**Comment by arthur657834** [comment]
echo '{"foo.1": 42, "bar 1": "less interesting data"}' |jq .'["foo.1"]'

it work ,guys!

**Comment by pkoppstein** [comment]
(1) For keys with non-alphanumeric characters (such as "."), and for keys beginning with a numeric character, you can use the form: `.["key name"]`

For example, on a Mac or Linux platform:

```
    jq '.["bar 1"]
```

(2) There is an excellent tutorial, as well as a comprehensive manual, both easily accessible via the jq home page.

(3) This web site is primarily for bug reports and enhancement requests.  It is suggested that usage questions be posted on stackoverflow.com (https://stackoverflow.com/questions/tagged/jq)

**Comment by pkoppstein** [comment]
(1) For keys with non-alphanumeric characters (such as "."), and for keys beginning with a numeric character, you can use the form: `.["key name"]`

For example, on a Mac or Linux platform:

```
    jq '.["bar 1"]
```

(2) There is an excellent tutorial, as well as a comprehensive manual, both easily accessible via the jq home page.

(3) This web site is primarily for bug reports and enhancement requests.  It is suggested that usage questions be posted on stackoverflow.com (https://stackoverflow.com/questions/tagged/jq)
