### ISSUE TITLE
Array subdivision

### ISSUE THREAD

**Issue by boaf** [jqlang/jq#1107]
_This is not a question, but I'm not sure where else to put this kind of thing, so please direct me to a more appropriate location!_

While working with `jq` on a few AWS DynamoDB scripts I'm creating, I came up with a simple filter to chunk requests (i.e. within `aws dynamodb batch-write-item`, due to [AWS' limits on request count](https://docs.aws.amazon.com/cli/latest/reference/dynamodb/batch-write-item.html)). I couldn't find this documented anywhere else, so I thought it might be useful to others.

Feel free to critique and hack!

```
def subdivide(n):
  [.[] | [.]]
  | reduce .[] as $x (
    [[]];
    if .[0][n-1] then
      [$x] + .
    else
      [.[0] + $x] + .[1:]
    end
  )
  | reverse
```

**Comment by pkoppstein** [comment]
The following `def` has several advantages - notably that it avoids `reverse` and emits a stream:
 ```
def subdivide(n):
  if n <= 0 or length == 0 then empty
  else .[0:n], (.[n:] | subdivide(n))
  end;
```

**Comment by pkoppstein** [comment]
For reference, the (undocumented) built-in filter `_nwise/1` fills this particular bill.
