### ISSUE TITLE
Replace key from environment in jq 1.5

### ISSUE THREAD

**Issue by juwi** [jqlang/jq#1112]
Hi, 
I am trying to use jq to generically replace stuff in a json conf file. I have written a bash function along the lines of:

```
json_replace() {
  local file="$1"
  local parent="$2"
  local child="${parent}.${3}"
  local value="$4"
  echo $key
  echo $value
  cat ${file} | jq --arg parent "$parent" --arg child "$child" --arg newvalue "$value" 'if has("[$parent]") then .[$child]=[$newvalue] else . end' > ${file}
}
```

However I cannot get this working, properly. Am I doing it wrong or is this kind of usage simply not supported?

**Comment by Melvar** [comment]
What this looks like to me is that `> ${file}` truncates the file before `cat` is executed, thus the input is always empty.
