### ISSUE TITLE
gsub getting exponentially slower on longer strings?

### ISSUE THREAD

**Issue by netj** [jqlang/jq#1113]
I have [a script that uses jq to strip carriage returns (`\r`)](https://github.com/HazyResearch/deepdive/blob/05bde411b07e1496a1d4c78c9a7c67ef59ace499/examples/spouse/input/articles.tsv.sh#L23) from a field in [a million json objects](http://research.signalmedia.co/newsir16/signal-dataset.html), one per line.  However, I noticed it was getting stuck on some part of the dataset and found that `gsub` (or I believe equivalently `sub` with `"g"` flag) becomes extremely slow as the string value gets longer.  The manual says PCRE, so I compared with the identical regex in Perl, but that doesn't show any problem.  Is the regex functions in jq simply slow, or am I doing something completely wrong?

The jq expression I'm using basically boils down to this:

``` jq
jq '.content | gsub("[\r]"; "")'
```

I pulled out the object that was causing trouble (~40KiB) and posted [a gist here](https://gist.github.com/netj/cbbce345c1e959b582b6):

``` bash
curl -RLO https://gist.github.com/netj/cbbce345c1e959b582b6/raw/specimen.jsonl
```

When I run my query with `gsub`, it takes more than 5 secs.

``` bash
$ cat specimen.jsonl | timeout 5s time jq -r '.content | gsub("[\r]"; "")' >/dev/null || echo TIMEOUT
TIMEOUT
```

I wondered if `sub` with `"g"` might make a difference, but still timed out:

``` bash
$ cat specimen.jsonl | timeout 5s time jq -r '.content | sub("[\r]"; ""; "g")' >/dev/null || echo TIMEOUT
TIMEOUT
```

And of course, it takes no time to pull out the field, so the slowdown is purely due to the regex functions.

``` bash
$ cat specimen.jsonl | timeout 5s time jq -r .content | wc
        0.01 real         0.00 user         0.00 sys
     43    4317   41132
```

If I try essentially the same thing with Perl's regex substitution, it takes almost no time:

``` bash
$ cat specimen.jsonl | timeout 5s time sh -c 'jq -r .content | perl -ne '\''s/[\r]//g; print'\'' | jq -R .' >/dev/null
        0.02 real         0.02 user         0.02 sys
```

I tried on both Mac and Linux and they give me the same result.

``` bash
$ jq --version
jq-1.5
```

Btw for the `timeout` command on my Mac, I'm using GNU coreutils installed via Homebrew without the `g` prefix by adding the following to the environment:

``` bash
PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
```

**Comment by nicowilliams** [comment]
It's not PCRE, but Oniguruma.

**Comment by nicowilliams** [comment]
I don't believe you're doing anything wrong.  It's very possible that it's the `sub` builtin, which is jq coded and which use recursion.  It might need to be recoded.

    #
    # If s contains capture variables, then create a capture object and pipe it to s
    def sub($re; s; flags):
      def subg: [explode[] | select(. != 103)] | implode;
      # "fla" should be flags with all occurrences of g removed; gs should be non-nil if flags has a g
      def sub1(fla; gs):
        def mysub:
          . as $in
          | [match($re; fla)]
          | if length == 0 then $in
            else .[0] as $edit
            | ($edit | .offset + .length) as $len
            # create the "capture" object:
            | reduce ( $edit | .captures | .[] | select(.name != null) | { (.name) : .string } ) as $pair
                ({}; . + $pair)
            | $in[0:$edit.offset]
              + s
              + ($in[$len:] | if length > 0 and gs then mysub else . end)
            end ;
        mysub ;
        (flags | index("g")) as $gs
        | (flags | if $gs then subg else . end) as $fla
        | sub1($fla; $gs);

I think this was meant to take advantage of tail-call optimization (TCO), but it might not end up being applied.

**Comment by pkoppstein** [comment]
Using jq 1.6, the u+s time for the query

     cat specimen.jsonl | timeout 5s time jq -r '.content | gsub("[\r]"; "")' > /dev/null

is about 1.8 seconds on a late-2014 Mac Mini (3GHz).  So maybe things aren't too bad.

By the way, if portions of the jq documentation refer (or referred) to PCRE, it was because Oniguruma supports multiple regex "flavors", and the flavor selected for jq is "Perl NG" (i.e. Perl with named groups), which it would be reasonable to describe as a "Perl-compatible regular expression" flavor.  How close it is to Perl or PCRE is perhaps hard to say, but for clues, an authoritative source would be
https://github.com/kkos/oniguruma/blob/master/doc/SYNTAX.md

---

@itchyny - I've checked that the u+s time on a significantly enhanced version of sub/3 is much the same as for 1.6, so I think this issue can be closed. 

Postscript: actually, the new version is significantly faster (> 25%).
