### ISSUE TITLE
pcre/regex issues using test function with Cookbook example

### ISSUE THREAD

**Issue by nipsy** [jqlang/jq#1118]
I ran into some weird problems on my Debian/(testing|unstable) box trying to use jq and some of the PCRE functionality (specifically test).  So I decided to try the examples in the cookbook as a sanity check, and ran into some even stranger behavior:

```
$ echo ${json}
[{"genre":"deep house"}, {"genre": "progressive house"}, {"genre": "dubstep"}]
$ echo ${json} | jq -c 'map( select(.genre | test("HOUSE", "i")))'
[{"genre":"progressive house"}]
$ echo ${json} | jq -c 'map( select(.genre | test("house", "i")))'
[{"genre":"deep house"},{"genre":"progressive house"},{"genre":"progressive house"}]
$ jq --version
jq-1.5-1-a5b5cbe
$ echo ${json} | ~/git/jq/jq -c 'map( select(.genre | test("HOUSE", "i")))'
[{"genre":"progressive house"}]
$ echo ${json} | ~/git/jq/jq -c 'map( select(.genre | test("house", "i")))'
[{"genre":"deep house"},{"genre":"progressive house"},{"genre":"progressive house"}]
$ ~/git/jq/jq --version
jq-1.5rc2-151-g1a8a5ee
$ apt-cache policy jq libonig2
jq:
  Installed: 1.5+dfsg-1
  Candidate: 1.5+dfsg-1
  Version table:
 *** 1.5+dfsg-1 600
        600 http://http.debian.net/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
     1.4-2.1 650
        650 http://http.debian.net/debian testing/main amd64 Packages
libonig2:
  Installed: 5.9.6-1
  Candidate: 5.9.6-1
  Version table:
 *** 5.9.6-1 650
        650 http://http.debian.net/debian testing/main amd64 Packages
        600 http://http.debian.net/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
```

Using the Debian supplied version of jq currently in unstable and even the latest version from the repo directly, I get the same unexpected behavior.  I'm wondering if this is something happening within Oniguruma as that seems to be the only shared dependency which hasn't changed.

**Comment by pkoppstein** [comment]
The tests using test(_,_) are incorrect.  The "," should be a semicolon, e.g. `test("HOUSE";"i")`.

Please let us know if there is still a problem after your tests have been corrected. Thanks.

**Comment by nipsy** [comment]
Ha.  Makes all the difference in the world.  Any chance of getting that updated?  Seems kind of bad to provide incorrect documentation directly from the project space.

**Comment by pkoppstein** [comment]
> Any chance of getting that updated?

Done.

**Comment by itchyny** [comment]
Looks resolved by [this change](https://github.com/jqlang/jq/wiki/Cookbook/_compare/f731d3c380a8169c08d0cd0308a05140c0b49cd6...1dd2bbf89f5d8d7d52c1d8245ff1f302ca6a1d00), closing the issue.
