### ISSUE TITLE
Homebrew install references 404'ed install package

### ISSUE THREAD

**Issue by mtrimpe** [jqlang/jq#1125]
When installing jq with Homebrew I get this error:

```
==> Installing jq
==> Downloading http://stedolan.github.io/jq/download/source/jq-1.4.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "jq"
Download failed: http://stedolan.github.io/jq/download/source/jq-1.4.tar.gz
```

I assume this is because jq-1.4.tar.gz was accidentally removed somehow.

**Comment by buzzub** [comment]
I had the same problem but resolved it by updating brew. Try:
`brew update`
That should have worked for me but didn't, but reinstalling homebrew did:
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
jq 1.5 has now installed correctly.

**Comment by mtrimpe** [comment]
I'm not in a position to reproduce it anymore so if you feel it was a one-off issue then feel free to close the issue.

**Comment by allenGKC** [comment]
try brew update
