### ISSUE TITLE
Support for variable length array arguments

### ISSUE THREAD

**Issue by groner** [jqlang/jq#1126]
I'd like to be able to pass a variable length array argument in, without having to encode it as JSON before hand.

This is problematic for the argument parser, which needs to know when the list ends.  Some possible rules for this are:
#### The array consumes all remaining arguments.

`jq -n '$words' --arrayarg words everything hereafter is part of the array`

This is simple, but has limited use cases.  That may not be a problem if you don't mind invoking jq multiple times.

`jq -n '$words' --argjson words "$(jq '$words' --arrayarg words everything hereafter is a part of the array)"`
#### The array elements are prefixed with a length.

`jq -n '$words' --arrayarg words ${#words[@]} "${words[@]}" input.json`

This would be ok for some scripting cases, but seems needlessly difficult in cases where I just want to pass in static arguments and let jq handle the quoting.
#### The array elements are terminated by options.

`jq -n '$words' --arrayarg words the words continue until they do not --arg something else`
`jq -n '$words' --arrayarg words the words continue until they do not -- input.json`

Some option parsing libraries support variable length options in this way.  The downside is you can't have include elements that look like arguments.  That's not very good for a tool like jq which should be able to handle just about any data.
#### The array elements are bounded by a user specified sentinel.

`jq -n '$words' --arrayarg words @@ words inside @@ input.json`

This is as flexible as the length prefix, but less error prone, as long as the user is able to choose a sentinel that won't occur in their data.

**Comment by pkoppstein** [comment]
@groner - Isn't the `--arg VAR VALUE` option good enough?  For example:

    $ jq -n --arg x "a b c" '$x | split(" ")'
    [
      "a",
      "b",
      "c"
    ]

**Comment by groner** [comment]
@pkoppstein That certainly works in some situations (including the examples above).

I'm building a tool that works with fairly arbitrary user provided data.  I don't want it to break when someone provides an argument with a space in it.  I could probably come up with a separator that is sufficiently random, but this starts to become inconvenient to implement.

**Comment by wtlangford** [comment]
It's worth noting that it is unlikely we add a command line flag for this.
We tend to avoid that as much as possible for various philosophical reasons.

I'm going to refrain from commenting on whether or not we should add this,
as @nicowilliams is the one with the philosophical issues on command line
flags.

That aside, if you can guarantee no raw newlines in your arguments, another
option would be: `echo -e "a\nb\nc\nd" | jq -R '[.,inputs]'`, which will
give you an array of those strings.

**Comment by wtlangford** [comment]
Another note: jq doesn't treat `\0` as a string-terminator.  Going the
xargs route and splitting on NUL `split("\u0000")` might work well for you.

**Comment by groner** [comment]
I suppose nulls over stdin is useful.  I wouldn't be handling anything with a null in it, in a shell script.  `printf '%s\0' ...` seems to work for this purpose on Linux and BSD.

`jq -n '$words' --argjson words "$(printf '%s\0' here are 'some tokens' | jq -Rc '. | split("\u0000")')"`

It still requires an additional invocation to create the array, but I think this is the best solution so far.

I think it's reasonable to be cautious around adding new flags (or features in general), but I think there's a real gap here.  One of the benefits of using jq for this sort of thing is that I can let it handle the encoding, which keeps my scripts fairly clean and robust.  Array arguments are an edge case where it is falling short, IMO.

Thanks for the ideas.

**Comment by pkoppstein** [comment]
@groner - To achieve what you want, it should not be necessary to pipe the output of one jq invocation into another.  Consider:
```
jq -nR  --arg words "$(printf '%s\\0' here are 'some tokens')" '$words | split("\\0")'
[
  "here",
  "are",
  "some tokens",
  ""
]
```

**Comment by groner** [comment]
@pkoppstein But that uses the string `\0` instead of a null byte.

```
:; jq -n  --arg words "$(printf '%s\\0' here are 'some tokens' 'or\0not')" '$words | split("\\0")'
[
  "here",
  "are",
  "some tokens",
  "or",
  "not",
  ""
]
```
