### ISSUE TITLE
Using jq output within json2csv

### ISSUE THREAD

**Issue by Bauhaus15** [jqlang/jq#1138]
Hi there,

i would like to use the output of jq as input for json2csv (https://github.com/jehiah/json2csv).
By using the  following command, i´m getting the expected output on the screen: `<import5.json jq -c`
But how can i use this output for another command (e.g. json2csv)? Is there a chance to safe the ouput to a file or even nicer using the output directly within json2csv?
I tried  `<import5.json jq -c | json2csv value,timestamp -o output.csv` to use the output of jq as input for json2csv.
Also i tried `<import5.json jq -c >ouput.json` to safe the output to a file.

I´m a total newbie in this field and would appreciate any help

Thanks in advance

**Comment by pkoppstein** [comment]
Try specifying the jq filter explicitly, along the lines of 

    jq -c . INPUTFILE | json2csv ...

or:

    <INPUTFILE jq -c . | json2csv ...

**Comment by Bauhaus15** [comment]
Thank you, i don´t get an error now, but it just writes an comma  ',' into the output csv file. 
If i try your suggestion with just one instance of the json file as input, it´s working fine. Also when i´m deleting the comma between the instances of the input by hand it´s working. 

Is there a way to format the result of jq without the comma, 
How do i need to changethe command: `<import.json jq -c .| json2csv -k four,five -o output.csv` 

Input which is working:

> {
      "One": "Result",
      "Two": 1,
      "three": 9088,
      "four": 6,
      "five": 0,
      "six": 0,
      "seven": 1460258309,
      "eight": 641588
    }
   {
      "One": "Result",
      "Two": 1,
      "three": 9088,
      "four": 6,
      "five": 0,
      "six": 0,
      "seven": 1460258309,
      "eight": 641588
    } <

Not working (original file format):
> {
      "One": "Result",
      "Two": 1,
      "three": 9088,
      "four": 6,
      "five": 0,
      "six": 0,
      "seven": 1460258309,
      "eight": 641588
    }**,**
   {
      "One": "Result",
      "Two": 1,
      "three": 9088,
      "four": 6,
      "five": 0,
      "six": 0,
      "seven": 1460258309,
      "eight": 641588
    } <
