### ISSUE TITLE
broken example in manual

### ISSUE THREAD

**Issue by jonpollackwastaken** [jqlang/jq#1144]
I'm just starting to learn jq, I love it but I'm a bit confused by the manual and example.  The example listed for join() throws an error both in my terminal and in jqplay.  Link below.

https://jqplay.org/jq?q=join(%22%20%22)&j=%5B%22a%22%2C1%2C2.3%2Ctrue%2Cnull%2Cfalse%5D

**Comment by saldecoco** [comment]
In jq version jq-1.5 the function `join` has a bug. Copy the last definition, from [builtin.jq](https://raw.githubusercontent.com/stedolan/jq/master/src/builtin.jq) in your script:

    def join($x): reduce .[] as $i (null;
            (if .==null then "" else .+$x end) +
            ($i | if type=="boolean" or type=="number" then tostring else .//"" end)
     )

**Comment by itchyny** [comment]
This issue seems be resolved as the reported jqplay link shows the result correctly (runs jq 1.6), so closing the issue.
