### ISSUE TITLE
How to not skip records with select embedded in constructor?

### ISSUE THREAD

**Issue by gdoteof** [jqlang/jq#1165]
I have been banging my head against this for a while.

Consider the following json:

```
{
"things" :
[        {
        "name": "foo",
        "params":[
            {
                "type": "t1",
                "key": "key1",
                "value": "val1"
            }

         ]
     },
      {
        "name": "bar",
        "params":[
            {
                "type": "t1",
                "key": "key1",
                "value": "val1"
            },
            {
                "type": "t1",
                "key": "category",
                "value": "thebarcategory"
            }
         ]
     }

]

}
```

Note, the "thing" `bar` has a key of type category, while the "thing" `foo` does not.

When I do `.things | .[] | {name: .name, category: (.params | .[] | select(.key=="category") | .value) }`

`foo` gets skipped entirely, where I would like to have it spit out `category: null`.

I have tried all manner of wrapping it in if statements and using the `//` operator to no avail.

Any insight is appreciated

**Comment by pkoppstein** [comment]
The following variant of your filter produces the results shown below, which seem to be in accordance with the description of what you want:

     .things | .[] | {name: .name, category: (.params | .[] | select(.key=="category")//null | .value) }

Output:

````
{
  "name": "foo",
  "category": null
}
{
  "name": "bar",
  "category": null
}
{
  "name": "bar",
  "category": "thebarcategory"
}
````

**Comment by gdoteof** [comment]
Thanks @pkoppstein I was able to get something similar but this still doesn't quite do what I need; notice your solution gives two `bars`s.

**Comment by pkoppstein** [comment]
With your input, the following filter produces one "foo" and one "bar", as shown below:
``` 
.things
| .[]
| if .params | any(.key == "category")
  then  {name, category: (.params | .[] | select(.key=="category") | .value) }
  else  {name, category: null}
  end
```

Output:
```
{
  "name": "foo",
  "category": null
}
{
  "name": "bar",
  "category": "thebarcategory"
}
```

**Comment by gdoteof** [comment]
Thank you @pkoppstein it makes sense this way; I did not consider the whole constructor being inside the if statement. 

I can make this work; it will be, unfortunately, a rather disgusting program, as I have about a dozen of these attributes that sometimes are there, and sometimes are not there.

**Comment by DomoSokrat** [comment]
This is probably to late to be of use for @gdoteof. But someone reading this issues might find this useful.

pkoppstein's first suggestion, but with added parens for grouping:
`.things | .[] | {name, category: ((.params | .[] | select(.key=="category"))//null | .value)}`
or with the alternative operator at the end:
`.things | .[] | {name, category: ((.params | .[] | select(.key=="category").value)//null)}`

Both give the desired output.
