### ISSUE TITLE
When using --raw-input jq splits lines longer than 4095 characters

### ISSUE THREAD

**Issue by Alexis-D** [jqlang/jq#1173]
Hey,

It looks like long inputs lines are getting split when using `-R`, this can reproduced with `jq-1.4` like this:

```
$ python -c 'import sys; sys.stdout.write("x" * 4095)' | jq -R . | wc -l
1
$ python -c 'import sys; sys.stdout.write("x" * 4096)' | jq -R . | wc -l
2
```

Notice how `jq` is fed a single line of input in both cases, but in the second case `jq` parses the input as two distinct lines.

**Comment by pkoppstein** [comment]
This is an old bug that was rectified long ago.  In particular, it does not exist in the current "official" version (jq 1.5) or the current version on "master".
