### ISSUE TITLE
how to get the intersection of two JSON arrays using jq?

### ISSUE THREAD

**Issue by mewalig** [jqlang/jq#1181]
Posted details at http://stackoverflow.com/questions/38364458/how-to-get-the-intersection-of-two-json-arrays-using-jq/38364583#38364583 and figured why not go straight to the source. Any ideas?

---

Given arrays X and Y (preferably both as inputs, but otherwise, with one as input and the other hardcoded), how can I use jq to output the array containing all elements common to both? e.g. what is a value of f such that

```
echo '[1,2,3,4]' | jq 'f([2,4,6,8,10])'
```

would output

```
[2,4]
```

?

I've tried the following:

```
map(select(in([2,4,6,8,10])))  --> outputs [1,2,3,4]
select(map(in([2,4,6,8,10])))  --> outputs [1,2,3,4,5]
```

**Comment by pkoppstein** [comment]
Note: this question was also asked, and answered, at http://stackoverflow.com/questions/38364458

**Comment by chenull** [comment]
so, this issue can be closed i guess
