### ISSUE TITLE
Core dump while piping from curl

### ISSUE THREAD

**Issue by jveiga** [jqlang/jq#1182]
``` bash
jq: jv_parse.c:290: stream_token: Assertion `k == JV_KIND_NULL' failed.
* Failed writing body (0 != 543)
```

while running 
`curl | jq -c --unbuffered --stream 'fromstream(1|truncate_stream(inputs))'`

**Comment by pkoppstein** [comment]
Thank you for the error report.  

1. Please provide a replicable example, e.g. with minimally sufficient output from the 'curl' invocation.

2. Please also provide the output of 'jq --version' and some details about the computing environment (e.g., the output of `uname -srvmpio`).

3. Normally, you'd include the -n option when using `inputs`.

4. Please note that `fromstream(1|truncate_stream(inputs))` is only suitable for inputs that are arrays, and will only output the elements that are JSON objects.  You might want to consider using `fromstream(0|truncate_stream(inputs))` -- but beware of the extra `null` it produces.
