### ISSUE TITLE
when parse fail, can jq show the error string ?

### ISSUE THREAD

**Issue by jinleileiking** [jqlang/jq#1190]

**Comment by jinleileiking** [comment]
show the datat jq parse .

**Comment by vazhnov** [comment]
Several variants are described here https://github.com/stedolan/jq/wiki/FAQ in chapter "𝑸: Is there a way to have jq keep going after it hits an error in the input file?"

**Comment by vazhnov** [comment]
But it would be great to have option "in case of parse error, return error code (non-zero) and all input".

**Comment by nicowilliams** [comment]
@vazhnov Use jq's `-e` option for that.
