### ISSUE TITLE
Docs: Suggest yq for manipulating YAML data

### ISSUE THREAD

**Issue by mcandre** [jqlang/jq#1191]
jq is awesome for grokking JSON data! Could the documentation include a link to [yq](https://github.com/preaction/ETL-Yertl) for handling YAML data?

**Comment by kislyuk** [comment]
I would suggest linking to https://github.com/kislyuk/yq instead.

**Comment by pkoppstein** [comment]
https://github.com/kislyuk/yq has been added to the answer regarding YAML on the jq FAQ.

**Comment by alxarch** [comment]
I just released [yjq](https://github.com/alxarch/yjq) with similar functionality.
It's written in Go and the release page provides binaries for all major os/arch.
It also supports YAML Input -> JSON output and JSON Input -> YAML output.

**Comment by rwxrob** [comment]
The https://github.com/mikefarah/yq project is currently leading in stars and deployments, but isn't perfect. Still, it should have a mention.

**Comment by SleepyBrett** [comment]
Since json is just a subset of yaml i'd rather just see jq switch internally and be able to take input in either form and be able to set a flag to output in yaml.

**Comment by rwxrob** [comment]
Just want to mention that I use [`gojq`](https://github.com/itchyny/gojq) now. I only use `jq` when it is the only thing on the system. I know it is a competing project, but feel it is worth mentioning given the recent comments.

**Comment by magmax** [comment]
why aren't you considering to add YAML support on jq?
YAML is just a superset of JSON, so just changing the loader to a YAML one everything should work in the same way.

**Comment by itchyny** [comment]
Since #467 is about YAML support of jq and is still open, closing this issue, yq is mentioned in both [FAQ](https://github.com/jqlang/jq/wiki/FAQ) and [Alternative jq implementations](https://github.com/jqlang/jq/wiki/Alternative-jq-implementations).
