### ISSUE TITLE
Terminating jq processing when condition is met

### ISSUE THREAD

**Issue by s3c1t** [jqlang/jq#1194]
I am using jq to search for specific results in a large file. I do not care for duplicate entries matching this specific condition, and it takes a while to process the whole file. What I would like to do is print some details about the first match and then terminate the jq command on the file to save time.

jq '. | if ... then "print something; exit jq" else ... end'

**Comment by itchyny** [comment]
The [`--stream` option](https://jqlang.github.io/jq/manual/#Streaming) exists for this use case, so closing the issue.
