### ISSUE TITLE
jq-win32.exe 1.5 crashes with 38+ chars filenames

### ISSUE THREAD

**Issue by dolmen** [jqlang/jq#1205]
With [`jq-win32.exe` 1.5](https://github.com/stedolan/jq/releases/download/jq-1.5/jq-win32.exe) on Windows 10 64 bits, jq crashes when the path to a jq script given with the `-f` option is at 62 characters or more (may be also if a bit less longer, I've not yet strictly tested the limit). If the path is somewhat shorter, everything is fine.

**Update**: the practical limit is discovered: maximum _37 chars_

**Comment by dolmen** [comment]
The crash also occurs for "long" input file paths.
This seems to be a general very low limit on file paths.

**Comment by Coolthulhu** [comment]
Same thing seems to happen to 64 bit version, on Windows 7:
```
jq-win64.exe . abcdefghijklmnopqrstuvwxyz0123456789
Segmentation fault
```

**Comment by mmendelson222** [comment]
Seems to still be a problem on Win 64 (ver. 1.5).

**Comment by Hrxn** [comment]
Yes, same here.

**Comment by nicowilliams** [comment]
Can you try `master`?

**Comment by Hrxn** [comment]
Didn't try git master, pulled a build from here:
https://ci.appveyor.com/project/stedolan/jq/build/1.0.88

This one actually works, no crash with really long filenames anymore..

**Comment by adam-c-anderson** [comment]
I just installed jq today from Chocolatey and had this exact problem. Is the fix not yet published? It's been nearly a year since last activity on this issue.

**Comment by pkoppstein** [comment]
> Is the fix not yet published?

You can obtain a Windows version (compiled) following the directions here:
https://github.com/stedolan/jq/wiki/Installation#windows-using-appveyor

**Comment by Alanscut** [comment]
hi @dolmen  
This bug has been fixed in the mater branch, you can try it again.
```
jq-version : master

# ./jq/jq.exe . test12345678974add_faq0000000wqweqacffaf
{
  "A": 1
}

```

**Comment by itchyny** [comment]
Looks like fixed in the master branch, closing the issue.
