### ISSUE TITLE
gsub with empty regex doesn't terminate

### ISSUE THREAD

**Issue by 4z3** [jqlang/jq#1206]
Calling `gsub` with an empty regex will run forever. Example:

``` console
$ jq -n '"" | gsub(""; "")'
```

Not sure if this is a bug or expected behavior, but terminating with an error might be more appropriate :)

**Comment by pkoppstein** [comment]
The bug was fixed by ad8d1a8 around Dec 9, 2015; see #1033 

That is, it was fixed AFTER the release of jq 1.5

**Comment by 4z3** [comment]
I can reproduce this with current master (0b8218515eabf1a967eba0dbcc7a0e5ae031a509).

**Comment by 4z3** [comment]
I can reproduce this bug with current master (0b8218515eabf1a967eba0dbcc7a0e5ae031a509).

**Comment by agguser** [comment]
Seems that empty matches also cause this bug.
```
$ jq -n -r '"abc\nabc" | gsub("^"; "+")'   # not terminate!

$ jq -n -r '"abc\nabc" | sub("^"; "+")'   # work if not 'g'
+abc
abc

$ jq -n -r '"abc\nabc" | gsub("^."; "+")'   # weird!
+++
abc
```

**Comment by itchyny** [comment]
Related issue: #2148
