### ISSUE TITLE
jq-win32.exe 1.5 was compiled without ONIGURUMA regex libary

### ISSUE THREAD

**Issue by QiWei** [jqlang/jq#1211]
jq was compiled without ONIGURUMA regex libary. match/test/sub and related functions are not available.

**Comment by jmathew** [comment]
This appears to still be an issue with the binaries that are linked here. 

https://stedolan.github.io/jq/download/

I've read a few issues that mention a switch to a different library and a new re-release of 1.5 but they were probably put on the github releases page which no longer exists.

**Comment by itchyny** [comment]
This is an outdated issue, so closing.
