### ISSUE TITLE
jq 1.5 is 6 times larger than 1.4

### ISSUE THREAD

**Issue by fonio** [jqlang/jq#1221]
~ $ ls -lh jq*
-rwxr-xr-x 1 487K Nov 26  2015 jq
-rwxr-xr-x 1 2.9M Aug 31 08:31 jq-linux64

jq downloaded using wget http://stedolan.github.io/jq/download/linux64/jq
jq-linux64 downloaded from the https://stedolan.github.io/jq/ download button

(btw - shouldn't http://stedolan.github.io/jq/download/linux64/jq provide the latest version?)

**Comment by alingse** [comment]
refer this release notes  https://github.com/stedolan/jq/releases/tag/jq-1.5

there are a lot of feature has been add in v1.5.

just compare the manual  `https://stedolan.github.io/jq/manual/v1.4/` vs 
`https://stedolan.github.io/jq/manual/v1.5/ `

**Comment by WonderRat** [comment]
Try delete debug info (strip works on jq-win32.exe)
