### ISSUE TITLE
jq map_values returning null on valid select statement

### ISSUE THREAD

**Issue by GerryWilko** [jqlang/jq#1222]
JQ seems to be behaving rather strangely with the following query:

`map_values(select(.timeStamp >= 1470171031444))`

Against the following dataset:

```
{
    "-KOC04rcDAjqTiGnpiR8" : {
        "timeStamp" : 1470170947102
    },
    "-KOC0PPQZULopR0kUmwd" : {
        "timeStamp" : 1470171031444
    },
    "-KOC0YtL_67Kc0cio-0v" : {
       "timeStamp" : 1470171070119
    },
    "-KOC0d6laPqdEnaWPQ50" : {
       "timeStamp" : 1470171091535
    }
}
```

This query returns `null`. Even though it should show the last three nodes. If I remove the select then it returns true against the value for the last 3 as expected but when using select is fails.

Any ideas?

Thanks in advance.
Gerard

**Comment by pkoppstein** [comment]
It appears that you misunderstand `map_values`.  My guess is that what you want to achieve can be accomplished using `with_entries` instead:

    with_entries( select(.value.timeStamp  >= 1470171031444) )

With your input, the result is:
````
{
  "-KOC0PPQZULopR0kUmwd": {
    "timeStamp": 1470171031444
  },
  "-KOC0YtL_67Kc0cio-0v": {
    "timeStamp": 1470171070119
  },
  "-KOC0d6laPqdEnaWPQ50": {
    "timeStamp": 1470171091535
  }
}
````

**Comment by GerryWilko** [comment]
Thank you. Could you explain why the previous `map_values` doesn't work? I had been using `map` before but needed the key too so when the docs say "Similarly, map_values(x) will run that filter for each element, but it will return an object when an object is passed." I assumed the same query would return the same result with the key value pair.

**Comment by pkoppstein** [comment]
`map_values(f)` is defined as `.[] |= f`.  The tricky part here is `|=`. For example

    jq -n '{"a":1, "b":2} | (.a |= empty)'

produces `null`, not `{"b":2}`.

**Comment by StephenWithPH** [comment]
I stumbled upon this issue after having a similar problem. Of note, I have `jq-1.5-1-a5b5cbe` (what comes with Ubuntu).

According to the 1.6 playground (https://jqplay.org/s/jprJeMQtYl), this now works as expected! :tada:
