### ISSUE TITLE
manipulate output string

### ISSUE THREAD

**Issue by s3c1t** [jqlang/jq#1226]
i have sample json file as follow:
{"date1":"2013-08-21T21:45:58Z","date2":"2023-08-19T21:45:58Z"}
{"date1":"2000-01-01T07:00:00Z","date2":"2039-12-31T23:59:59Z"}
{"date1":"2012-04-05T01:55:03Z","date2":"2013-04-08T20:49:46Z"}
how to get out as follow:
{"date1":"2013-08-21","date2":"2023-08-19"}
{"date1":"2000-01-01","date2":"2039-12-31"}
{"date1":"2012-04-05","date2":"2013-04-08"}

**Comment by pkoppstein** [comment]
Consider this transcript:
```
jq 'map_values(.[0:10])'
{"date1":"2013-08-21T21:45:58Z","date2":"2023-08-19T21:45:58Z"}
{
  "date1": "2013-08-21",
  "date2": "2023-08-19"
}
```
