### ISSUE TITLE
Empty strings are ignored

### ISSUE THREAD

**Issue by ghost** [jqlang/jq#1229]
When checking the value of the input, empty lines are ignored.  Take, for example, this query and the below input data (which in reality would actually be 5 different queries) - 

`state=$(echo "state_raw" | jq -r 'if ("\(.)" | test("none|null"; "i")?) or . == [] then "DOES_NOT_EXIST" else .[0]  end'`

```
null
[]

"None"
[ "CREATE_IN_PROGRESS" ]
```

In this case I get 4x results - `DOES_NOT_EXIST, DOES_NOT_EXIST, DOES_NOT_EXIST, CREATE_IN_PROGRESS`.

However, where is the 5th result?  My script asks if `[[ $state == "DOES_NOT_EXIST" ]]`, meaning that for the 3rd line in my example, the empty string, the incorrect code is executed.

I've tried using `"\(.)"` and Raw Input, but the results are not what I'm looking for.  Is there a way to force JQ to not ingore empty strings?

**Comment by wtlangford** [comment]
There's a subtlety here. Jq operates on json values and expects its input
to be a series of such. A blank line isn't a string, but rather extra
padding between two json values. You could likely combine raw input, an
empty string check, and tojson to achieve your desired effect

**Comment by pkoppstein** [comment]
jq can read JSON or lines of text.  Since whitespace outside of strings has no significance in JSON, it would appear that you should be using the -R option, which forces jq to read each line as a string.  An alternative might be to use a tool such as sed or awk to pre-process your input.
