### ISSUE TITLE
get all values with contains either of the values

### ISSUE THREAD

**Issue by sant527** [jqlang/jq#1233]
select(.created_time | contains([\"2016-09-15\",\"2016-09-14\"]))]

cannot have their containment checked

i am trying to get elements with contain either of the dates. [\"2016-09-15\",\"2016-09-14\"]

**Comment by yanhongwang** [comment]
@sant527 

Try select()?
https://github.com/djosephsen/real-world-jq/blob/master/aws/select-by-tag.md

Hong
