### ISSUE TITLE
Please make a release (security issues are fixed in git but not released)

### ISSUE THREAD

**Issue by bjornfor** [jqlang/jq#1241]
Without releases, each downstream packager has to do extra work by tracking git and/or manually patching the the source code. IMHO, that's a waste of resources. If upstream makes releases, that effort is O(1) instead of O(n) for all packagers.

For instance, https://github.com/NixOS/nixpkgs/pull/18908

**Comment by itchyny** [comment]
This issue was opened before the release [1.6](https://github.com/jqlang/jq/releases/tag/jq-1.6) in Nov 2018, so closing this issue. We're planning the next release right now.
