### ISSUE TITLE
how can i get the result??

### ISSUE THREAD

**Issue by amykkko** [jqlang/jq#1244]
input json :

{
  "id": "01",
  "owner": "amy",
  "patchSets": [
    {
      "file": "src/com/android/a.java",
      "line": 7,
      "reviewer": {
        "name": "amy",
        "email": "amy@gmail.com",
      },
      "message": "Hi."
    },
    {
      "file": "src/com/android/b.java",
      "line": 218,
      "reviewer": {
        "name": "John",
        "email": "john.kim@gmail.com",
      },
      "message": "Hello."
    }
  ]
}

expected output :
{
  "id": "01",
  "reviewer": "amy",
  "message": "Hi."
}
{
  "id": "01",
  "reviewer": "John",
  "message": "Hello."
}

**Comment by pkoppstein** [comment]
The input you have posted is not quite valid as JSON, and the answer to your question will depend on exactly how the input is corrected.  I would suggest that you post your question, with correct JSON input, at stackoverflow.com with the jq tag.

**Comment by amykkko** [comment]
modified the original question.

**Comment by pkoppstein** [comment]
@amykkko - Thanks for updating the question.  

The revised example input still isn't completely valid JSON, but it's close enough to give the following answer, which assumes the trivial changes required to make the input valid have been made:

```
$ jq '{id} + (.patchSets[] | {"reviewer": .reviewer.name, message})'  valid.json
{
  "id": "01",
  "reviewer": "amy",
  "message": "Hi."
}
{
  "id": "01",
  "reviewer": "John",
  "message": "Hello."
}
```

By the way, in future, you can use `jq .` to check the input.  And in the future, please post usage questions at stackoverflow.com with the tag `jq`.

**Comment by amykkko** [comment]
very good! thanks!
