### ISSUE TITLE
export wrong large long value

### ISSUE THREAD

**Issue by rocwenlinux** [jqlang/jq#1248]
./jq-linux64  --version
jq-1.5

./jq-linux64  -c '([.bignumber]) | @csv' inputfile.txt > outputfile.csv

inputfile.txt
{"bignumber":11012340123456789}{"bignumber":10456781234567891}

output:
11012340123456788
10456781234567892

Summary:
the last digit in the large value of long is changed. conversion is not accurate.

**Comment by itchyny** [comment]
This is already fixed in the master version (implemented by #1752 in Oct, 2019).
