### ISSUE TITLE
jv.c:1110: jv_object_set: Assertion `jv_get_kind(key) == JV_KIND_STRING' failed.

### ISSUE THREAD

**Issue by cagney** [jqlang/jq#1251]
I suspect the syntax isn't valid, however:

$ jq --version
jq-1.5
$ jq --raw-input '[.,input] | {([0]): [1]}'
jq: jv.c:1110: jv_object_set: Assertion `jv_get_kind(key) == JV_KIND_STRING' failed.
Aborted (core dumped)

the correct line is:

jq --raw-input '[.,input] | {(.[0]): .[1]}' <<EOF
label1
some raw text
label2
more raw text
EOF

**Comment by pkoppstein** [comment]
The problem has been fixed in "master" (i.e. after the first release of jq 1.5).

```
$ jq --version 
jq-1.5rc2-150-g1740fd0

$ jq --raw-input '[.,input] | {([0]): [1]}'
jq: error: Cannot use array ([0]) as object key at <top-level>, line 1:
[.,input] | {([0]): [1]}             
jq: 1 compile error
```
