### ISSUE TITLE
objects and iterables filters not working as expected

### ISSUE THREAD

**Issue by blezek** [jqlang/jq#1258]
Expected to be able to get only objects.  Received objects and strings.  In the examples, was expecting only `b` to be returned.  Instead got everything.  Perhaps I'm not using these filters correctly?

```
$ jq --version
jq-1.5
$ echo '{ "a":"string", "b":{ "key": 1 }}' | jq -r '.|iterables'
{
  "a": "string",
  "b": {
    "key": 1
  }
}

$ echo '{ "a":"string", "b":{ "key": 1 }}' | jq -r '.|objects'
{
  "a": "string",
  "b": {
    "key": 1
  }
}
```

However, the behavior seems to work fine in arrays:

```
$ echo '[[],{},1,"foo",null,true,false]' | jq '.[]|objects'
{}
```

**Comment by pkoppstein** [comment]
@blezek - `objects` simply checks whether its input is a JSON object.  That is, given a stream of JSON entities, it will select those that are JSON objects. So it looks as though you might want to try `.[] | objects' on your inputs.  You might also like to try your hand at `.. | objects`.
