### ISSUE TITLE
Node wrapper please?

### ISSUE THREAD

**Issue by kristianmandrup** [jqlang/jq#1267]
Could someone please wrap this library for use with Node.js :)

**Comment by slapresta** [comment]
There exists a wrapper for Node.js usage: https://github.com/sanack/node-jq

**Comment by matthewadams** [comment]
As of this writing, https://github.com/sanack/node-jq is implemented as a thin wrapper that uses `child_process` to invoke the `jq` executable externally.  This incurs process creation overhead unnecessarily.  I've entered https://github.com/sanack/node-jq/issues/86 to request that they refactor to be a native Node.js module.

Perhaps this issue should be renamed "Provide native Node.js module" that invokes the `jq` internals instead of using `child_process`.

**Comment by nicowilliams** [comment]
I think we want to leave bindings to others, unless they are willing to a) contribute the bindings to jq, and b) contribute maintenance of them.

**Comment by nicowilliams** [comment]
Also, ISTR a JavaScript/ECMAScript-native implementation of a jq-like DSL that is very well integrated into the host language and is superior to jq in a number of ways (naturally, since jq has some explicitly chosen limitations that ECMAScript does not).

**Comment by matthewadams** [comment]
@nicowilliams I understand.  Do you have a link to ISTR?  I'm having trouble finding it.

**Comment by pkoppstein** [comment]
@matthewadams - ISTR == I seem to recall :-)

**Comment by nicowilliams** [comment]
@kristianmandrup @matthewadams https://github.com/FGRibreau/jq.node

```
jq.node - like jq but WAY MORE powerful (300+ helpers 🔥 & 300K+ modules 😱) https://twitter.com/FGRibreau
```

**Comment by nicowilliams** [comment]
Looking for that I noticed this: http://programminghistorian.org/lessons/json-and-jq and it is fantastic!

**Comment by matthewadams** [comment]
@pkoppstein @nicowilliams TMAT (too many acronyms today)  :P

**Comment by danielsinai** [comment]
Working on something similar, currently facing some problems maybe a maintainer can take a look (am not a C programmer) 

Here is the repo: https://github.com/danielsinai/jq-node-bindings

**Comment by danielsinai** [comment]
https://github.com/port-labs/jq-node-bindings
This can be closed :) @stedolan

**Comment by itchyny** [comment]
Now that there is a node binging as commented above, closing this issue.
