### ISSUE TITLE
how can I inject an converted and updated string array back into the correct location?

### ISSUE THREAD

**Issue by gearoidr** [jqlang/jq#1269]
hi there

Would appreciate some help on what is probably a basic mistake using jq please

I'm have a json blob which has the following structure 

"request" : {
    "bodyPatterns" : [ {
      "equalToJson" : "{\"prodLines\":[{\"orderNumber\":123456788,\"name\":\"Test Name\"}]}" }

Because the element prodLines is a string array, I had to extract it using the following : 

cat $file | ./jq -r '.request.bodyPatterns[].equalToJson' | ./jq .prodLines[] 
in order to access the elements in the string array
I have done some manipulation to the elements within prodLines and have saved them to a variable $xy

When I try to add the values back into prodLines I am unable to access it correctly, I have tried variations of the following but with no luck

cat $file | ./jq --arg v "$xy" -r '.request.bodyPatterns[].equalToJson.prodLines = $v'
this returns the error Cannot index string with string "prodLines"

I've also tried 
cat $file | ./jq -r '.request.bodyPatterns[].equalToJson' | ./jq --arg v "$xy" '.aopLines = $v'

but this adds the value of $xy at the equalToJson level and replaces the rest of the file with that value

I'm sure I'm making some really stupid noob mistake but would really appreciate some input on how I can correctly do this please?

**Comment by eric-brechemier** [comment]
@gearoidr have you considered using the builtin `fromjson`? This would keep your processing within a single `jq` filter:

```
.request.bodyPatterns[].equalToJson | fromjson | .prodLines[]
```

**Comment by gearoidr** [comment]
thanks for the reply, I was getting an error when trying fromJson, but I was able to access the elements like the following
./jq -r '.request.bodyPatterns[].equalToJson' | ./jq -r '.prodLines[].name' 

this made it easier to add back into the original object

**Comment by gearoidr** [comment]
hmmm i've run into further issues now, if the json contains multiple names and I want to update each one and then re-add them to the array, it seems to recursively add the full array 3 times

cat $file | ./jq -r '.request.bodyPatterns[0].equalToJson' \
           | ./jq -r 'if .prodLines[].name | contains(("Initialize ")) then .prodLines[].name="\\S\\+\\p\\.+" else .prodLines[].name="\\S\\+" end' \
           | ./jq -r '.prodLines[].startDate = "\\S\\+" | .prodLines[].endDate = "\\S\\+" > xy

when the above run, it iterates through the 3 elements and updates the name and dates fields but then does it 2 more times, so it re-creates the array with 3 sets of 3 elements

**Comment by eric-brechemier** [comment]
@gearoidr can you post a short example of the expected output and input?

A few notes:

1. at this point of complexity, you should write your filters in a file, rather than on the command line
2. the `-r` flag should only be used at the last step (it could lead to parsing errors if strings are present at the top level of the output stream of an intermediate step)
3. you don't need to pipe `jq` to `jq`, you can apply pipes within the `jq` filter, like you did within each step. Use parentheses, where needed, to group operations that are part of a single step.

**Comment by nicowilliams** [comment]
You can use `fromjson`, `tojson`, and `|=` for this.
