### ISSUE TITLE
jq is for some reason altering my formatting

### ISSUE THREAD

**Issue by ghost** [jqlang/jq#1292]
For some reason, and I have no idea why, when I test out formatting of the following lines on [jqplay ](https://jqplay.org/#)it comes out looking different than when I run it on the command line.

[Here is what the original data looks like](http://pastebin.com/ew4AAkrY)

I am filtering that data with -c '.users[]'

Now, if I drop that data into the jqplay test site, with the '.users[]' filter and set it to compact, it produces the exact result I want, [it looks like this](http://pastebin.com/en8gSXbs)

But for some weird reason when I run the following in the command line it messes up the structure: 

`curl https://api.example.com/users/scroll -u 'dG9rOjg4YmUxMzr4XzJmNzZfNDkwY3934jU2X2mrM2MxZGEzYWI2MzoxOjA=': -H 'Accept:application/json'| jq -c '.users[]'`

[The output looks like this!
](http://pastebin.com/Bhqt9wQJ)

Which as you can tell, is nothing like how it turns out in the jqplayground feature. To make matters even more confusing, someone else ran it and it formatted it correctly. On top of that, about a week ago, it worked fine for me.

I've also tried removing jq and reinstalling it with no success. I'm running it on Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-51-generic x86_64) if that somehow helps.

This issue really needs to be fixed ASAP so any help would be greatly appreciated.

**Comment by pkoppstein** [comment]
@zachasman - I have verified (using several different versions of jq) that using the "original data" (as posted) together with "jq -c 'users[]'", the results are as you want.  So, given that you say that everything worked for you and someone else previously, it seems to me that jq is not the problem.  

I cannot test the "curl" part of your pipeline, but my guess is that that is the source of the variability. To eliminate another potential source of difficulty, however, I'd suggest you use the -M option of jq.

Perhaps you could verify that the output of the curl command is still as you expect?
