### ISSUE TITLE
documentation bugs: test(_;_)

### ISSUE THREAD

**Issue by pkoppstein** [jqlang/jq#1298]
The manual (both the 1.5 and development versions) have a line with several errors (six by one measure) in it:

> To match whitespace in an x pattern use an escape such as \s, e.g.
> test( “a\sb”, “x” )

The last line should be:

    test( "a\\sb"; "x")

That is:

1. The single backslash needs to be duplicated.
2. The "," must be ";".
3. The four fancy quotation marks should all be replaced by unfancy double-quotes.

**Comment by itchyny** [comment]
Duplication of #2197 and was already fixed by  #2229 (80052e5275ae8c45b20411eecdd49c945a64a412).
