### ISSUE TITLE
Run filter through ssh doesn't work

### ISSUE THREAD

**Issue by af-fess** [jqlang/jq#1308]
I try to run following command through `ssh`:

```bash
$ ssh eu10.comp.com "/home/maxim/bash.sh  | jq '. | .model'"
```
and its doesn't work.

However, without filtering works fine:
```bash
ssh eu10.comp.com "/home/maxim/bash.sh  | jq '.'"
```

If I enter to machine `eu10.comp.com` with `ssh` and run command:

```bash
 $ /home/maxim/bash.sh  | jq '. | .model'
```

It works!

any ideas?

**Comment by pkoppstein** [comment]
Try:

    ssh eu10.comp.com "/home/maxim/bash.sh  | jq .model"

**Comment by nicowilliams** [comment]
Certainly `. | .model` is the same as `.model`, so do that.  However, it seems there's a problem with quoting, but it's not obvious what.  What shell is being used on the remote side, and what is the result of the broken command?
