### ISSUE TITLE
I've just compiled jq with emscripten and made an online demo.

### ISSUE THREAD

**Issue by fiatjaf** [jqlang/jq#1405]
It may interest some people, I don't know. It can also serve the same role as jqplay.org.

Here's the repository: https://github.com/fiatjaf/jq-web
Here's the demo you can play with: https://fiatjaf.alhur.es/jq-web/

It's also a library you can just install with npm and use with browserify/webpack/whatever.

**Comment by fiatjaf** [comment]
(currently not working in Node.js until I solve an emscripten issue, but anyway using it on Node.js would be silly, right?)

**Comment by fiatjaf** [comment]
More demos: https://jq.alhur.es/jiq/, https://jq.alhur.es/finder/

**Comment by pkoppstein** [comment]
I'm currently using the Chrome browser and cannot get the /finder link to work at all.

https://jq.alhur.es/jiq/ seems to work properly on the first JSON that's given, but thereafter it doesn't, at least without a refresh.  It seems very slow though, even though I'm using quite a fast computer (Google Octane score: 26601)

But it's good to see jq working in a browser!

**Comment by fiatjaf** [comment]
Oops, there seems to be an error somewhere. `/finder` works here, but only if you write something different from `.` in the first column.

Both apps are slow, but that slowness doesn't reflect the actual `jq-web` slowness, it's just that I'm debouncing the updates (to avoid hitting `jq-web` too hard).

Thanks for trying them, though.
