### ISSUE TITLE
Docs uses plain strings as examples, not JSON

### ISSUE THREAD

**Issue by alkuzad** [jqlang/jq#1422]
I try to use jq for all my JSON manipulations now but docs are not helpful. All more advanced features involve plain strings and it's not always useful, example:

https://stedolan.github.io/jq/manual/#index(s),rindex(s)

In this example I would like to see how to use index function to get index of element in big array to use it in next filters. Instead I see very basic index usage which is not too helpful.

This makes jq hard to introduce to anyone, besides basic usage to extract part of jsons.

**Comment by Alanscut** [comment]
hi @alkuzad 
The jq manual has been improved a lot, and many examples have been added.

**Comment by alkuzad** [comment]
@Alanscut that is great to hear, altough on AWS I started to use builtin --query with JMESpath

That is example I wanted to see in docs:
```
jq 'numbers|index(15)'
input: {"numbers": [9, 15, 33, 21]} 
output: 1
```
