### ISSUE TITLE
visibility of labels: feature or bug?

### ISSUE THREAD

**Issue by fadado** [jqlang/jq#1427]
I discovered that expressions like `break $label` can be passed as arguments:

```
def when(p;a):
    if p then a else . end;

label $x
| range(100)
| when(.>11; break $x)
| .*2
```

Is this a non documented feature?

JJOR

**Comment by nicowilliams** [comment]
> I discovered that expressions like break $label can be passed as
> arguments:
>
> def when(p;a):
>     if p then a else . end;
>
> label $x
> | range(100)
> | when(.>11; break $x)
> | .*2
>
> Is this a non documented feature?
>

Feature!  Same as with $varname.  jq is lexically scoped :)
