### ISSUE TITLE
--arg key filter

### ISSUE THREAD

**Issue by kokuryuha** [jqlang/jq#1471]
I will totally chalk this up as being relatively new to Linux environments, but am seeking a bit of help and am unsure if this is even possible.

Relatively JSON in question:
```
{
  "task": {
    "Definitions": [
      {
        "name": "task1",
        "image": "image1",
      },
      {
        "name": "task2",
        "image": "image2",
      },
      {
        "name": "task3",
        "image": "image3",
      },
    ],
  }
}
```

I am trying to write a `jq --arg` line that can update the image key given a task name.  i.e. update `"name": "task2"` with `image2:$(date +"%Y%m%d%H%M")`

Obviously in this case something like this would work:
`jq --arg IMAGE image2:$(date +"%Y%m%d%H%M") '.task.Definitions[1].image=$IMAGE'`

This doesn't work if I need to be able to search out something for other tasks though.  I'd like to be able to replace `.task.Defintions[1]` with something that could take say `$taskname` and find the relative key to update `image:`, i.e. I need to find `task3` this time and update it's respective `image`

I have been able to search out things like this in basic filtering, but my problem is I need to pipe the entire JSON back into a command, which is what is complicating things.

**Comment by itchyny** [comment]
This is an outdated question, so closing but leaving an solution.
```bash
 $ jq --arg name "task2" --arg image "image2:$(date +%Y%M%d%H%M)" \
  '(.task.Definitions[] | select(.name == $name) | .image) = $image' <<'EOF'
{
  "task": {
    "Definitions": [
      {
        "name": "task1",
        "image": "image1"
      },
      {
        "name": "task2",
        "image": "image2"
      },
      {
        "name": "task3",
        "image": "image3"
      }
    ]
  }
}
EOF
```
```json
{
  "task": {
    "Definitions": [
      {
        "name": "task1",
        "image": "image1"
      },
      {
        "name": "task2",
        "image": "image2:202338031838"
      },
      {
        "name": "task3",
        "image": "image3"
      }
    ]
  }
}
```
