### ISSUE TITLE
Error trying to use jq from awk system()

### ISSUE THREAD

**Issue by sluongng** [jqlang/jq#1491]
I am having a log file with format like this
```
blah blah
Hello world | {"json":"this is hello"}
blah blah
blah blah
blah blah
```

I am running awk as follow
```bash
grep 'Hello World' file.log | awk -F "|" 'system( "jq " $2)'
```

and the error its giving me is 
```
jq: error: syntax error, unexpected ':', expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
bin:application   
jq: 1 compile error
```

**Comment by Ked-Ki** [comment]
`jq` takes the json it runs over from stdin, so you need to pipe to `jq`, not provide it as an argument. Try this:
```
grep Hello hello | awk -F '|' '{print $2 | "jq"}'
```
See the [gawk manual](https://www.gnu.org/software/gawk/manual/html_node/Redirection.html) for more info. (This works on standard awk as well, but the gawk manual is nicer, and you're likely running gawk anyway.)

**Comment by muhmuhten** [comment]
grep 'Hello hello' | awk -f \| '{print $2}' | jq ...

would make more sense. Note that using awk to split will break if the json contains any `|`. Consider sed:

    grep 'Hello hello' file.log | sed -n 's/[^|]*|//p' | jq ...

Or consider using jq with raw input to cut off the head and fromjson it:

    grep 'Hello hello' | jq -R 'match("(?<=\\|).*").string|fromjson|...'
