### ISSUE TITLE
Latest manual

### ISSUE THREAD

**Issue by fadado** [jqlang/jq#1515]
I have read the jq manual again in its [latest version](https://github.com/stedolan/jq/blob/master/docs/content/3.manual/manual.yml) and I am happy to see how it improves and clarifies various concepts. Anyway, I find some details to comment, some minor but others more important:

- The use of `length` to calculate the absolute value of a number remains undocumented:
```
jq -n '-3456 | length '
3456
```

- _function_ or _filter_ is used indistinctly, or by defining _filter_ as function without arguments. In my opinion it should be used _filter_ in all cases, except to explain that _subroutine_, _method_ or _function_ are concepts analogous but never identical to that of _filter_ in jq.

I assume that this last point represents great changes in the manual, but I recommend its reading mentally moving _function_ by _filter_&hellip;

**Comment by Alanscut** [comment]
hi @fadado 
Here is a description of the length usage in the latest manual.so We can convert ` -3456` to `"-3456"`
```
root@os: jq -n '"-3456"|length'
5
```
```
length
The builtin function length gets the length of various different types of value:
The length of a string is the number of Unicode codepoints it contains (which will be the same as its JSON-encoded length in bytes if it’s pure ASCII).
The length of an array is the number of elements.
The length of an object is the number of key-value pairs.
The length of null is zero.
```

**Comment by pkoppstein** [comment]
@itchyny - I don't understand why you closed this issue as the current "development version" documentation still does not explicitly mention `length` on numbers.  

jq, gojq and jaq are all consistent with respect to `length` on numbers returning the absolute value, so a reasonable basis for resolving this issue would be to view it as a documentation ER.

Thanks.

**Comment by itchyny** [comment]
Thanks, PR fixing this document is welcome.

**Comment by itchyny** [comment]
This behavior of `length` has been documented by #2625 (dd5ce98caf669bb44db5e526624c1a796325d45e).
