### ISSUE TITLE
combine jq filters

### ISSUE THREAD

**Issue by ashok2002** [jqlang/jq#1567]
How jq filter combines the filter outputs?  Following jq not generates output.json with respective input arg value ('jack').

input.json 
------------  
{
 "key1": "<value1>",
 "key2": "<value2>"
}  				  

		 jq --arg input "$username" \
                  'if .key1 == "<value1>"
                         then . + {"key1" : ($input) }
                  else . end' input.json |
                  'if .key2 == "<value2>"
                         then . + {"key2" : ($input) }
                  else . end'  >  output.json

output.json 
------------
{
 "key1": "jack",
 "key2": "jack"
}

**Comment by itchyny** [comment]
This is an ambiguous question and I'm not sure what you want to achieve even if an example is given. In general, you can use the pipe operator to combine jq filters; `jq 'FILTER1 | FILTER2' FILE`. So the following command could what you might want.
```bash
jq --arg input "$username" \
  'if .key1 == "<value1>" then . + {"key1" : ($input) } else . end |
   if .key2 == "<value2>" then . + {"key2" : ($input) } else . end' input.json > output.json
```
BTW updating multiple paths can be achieved as follows.
```bash
username=jack
jq --arg input "$username" '(.key1,.key2) = $input' <<'EOF'
{
"key1": "",
"key2": ""
}
EOF
```
```json
{
  "key1": "jack",
  "key2": "jack"
}
```
