### ISSUE TITLE
Rename (or alias) `select` to `filter`

### ISSUE THREAD

**Issue by ghost** [jqlang/jq#1581]
`map`, `reduce` and `filter` are very common terms many are familiar with, particularly those with a functional programming background. I was reading the docs and noticed `map` and `reduce`, but was going crazy looking for `filter` which is what I wanted. I eventually figured out that in JQ it's called `select`, but the naming threw me off. Or perhaps just add `filter` in the documentation and refer to `select` there.

**Comment by itchyny** [comment]
Accepting this proposal the query looks like `[1,2,3] | map(filter(. > 1))`, but is this desirable? The jq `select` filter is applied to element, used e.g. `[1,2,3] | map(select(. > 1))`. I think `filter` should be operated on arrays (or on collections generally), so `def filter(f): map(select(f))` makes sense?

**Comment by pkoppstein** [comment]
@itchyny - This is a very old ER which made a valid point about `select` but it has not had much traction and would perhaps at this point be best closed or replaced by an ER regarding an array-oriented `filter` as you suggest.  I could certainly live with an array-oriented `filter`, but it's quite likely to result in even more confusion and headaches without adding anything substantial.  If there is still some non-trivial run-time overhead associated with adding new builtin filters, I'd rather see new stream-oriented filters.

(What is the current view about the run-time costs of adding to builtin.jq?)

**Comment by itchyny** [comment]
Agreed with the expected confusion. This is an outdated feature request, we will not alias `select` to `filter` due to the reasons I commented above, so closing the issue.
