### ISSUE TITLE
number representation not prominent in doc

### ISSUE THREAD

**Issue by wabu** [jqlang/jq#1592]
The fact that jq "currently only has IEEE754 double-precision (64-bit) floating point number support" shows up only inside the "Math" section of the documentation. I'd expect a reference to the representation of numbers on all operations that are affected by this fact.

For example, the Identity filter is documented to "take[...] its input and produces it unchanged as output", which is only true for numbers representable by IEEE754 double-precision. As the JSON format spec does not restrict the numbers, the documentation of jq should clearly state this restriction for the Identify operator (as well as tonumber, fromjson, ...), not only inside the Math section.

Clearly documenting this should also help reducing the reoccurring bug reports ( #1399, #1387, #1357, ...) about this behavior.

**Comment by itchyny** [comment]
The manual has been improved a lot about number representation (e.x. #2735), so closing this issue.
