### ISSUE TITLE
jq segmentation fault with gcc 6 -- fixed by compiling with _GNU_SOURCE

### ISSUE THREAD

**Issue by patrickdepinguin** [jqlang/jq#1598]
I observe segfaults when running jq, even without any options (supposed to show the help text).
When I build jq with gcc 5.4.0, no issue is present. When switching to gcc 6.4.0 the issue appears.

I debugged the issue and found that this is related to a call to strdup from main.c, line 447:
```char *origin = strdup(argv[0]);```
The heap on this test run was in range: 55555575a000-55555577b000 but the variable stored in origin was only the lower 32-bit: 0x5575b5c0.

In the build log I found various warnings:
```
main.c:447:18: warning: implicit declaration of function 'strdup' [-Wimplicit-function-declaration]
   char *origin = strdup(argv[0]);
```
and similar for 'fileno'.

Adding the global flag '-D_GNU_SOURCE' to CFLAGS fixes this issue. In this case, the right definition from strdup will be obtained (I presume that without it, the return value is seen as 'int' and thus 32-bit).

It is unclear to me how you want this to be fixed.
In some files I find explicit definitions of _GNU_SOURCE, in others not. I guess it'd be easier to handle it at Makefile level, rather than in individual source files.

**Comment by patrickdepinguin** [comment]
Forgot to mention: this was tested with jq-1.5 on Gentoo Linux.

**Comment by MikePetullo** [comment]
I have the same problem on OpenWrt (https://github.com/openwrt/packages/issues/7785), and compiling jq with _GNU_SOURCE fixed things there too.

**Comment by nicowilliams** [comment]
Any ideas why this might be?  Sounds like a compiler bug, no?

**Comment by patrickdepinguin** [comment]
I'm pretty sure this is not a compiler bug but rather an application bug. Like I mentioned on the original report, the expected 64-bit char pointer is actually a 32-bit address. This looks to be caused by the missing declaration of strdup, which causes the compiler to default to 'int' as return type (32-bit type even on 64-bit systems).
When defining _GNU_SOURCE, the strdup declaration becomes available and the problem is solved.

See also 'man strdup' and the corresponding feature flags.

I personally think it would be better to define _GNU_SOURCE once in the makefiles for the entire project, rather than defining it in individidual files. But that is something for you to decide, and is not strictly necessary.

**Comment by nicowilliams** [comment]
On the Ubuntu system I was looking in `strdup()` is not marked as requiring `_GNU_SOURCE`, thus my confusion.

Alright, and of course we should also define `_DEFAULT_SOURCE`, since in newer glibc versions that one replaces `_GNU_SOURCE` and `_BSD_SOURCE`...

**Comment by neheb** [comment]
Note that musl defines it under many conditions: https://github.com/bminor/musl/blob/master/include/string.h#L60

**Comment by neheb** [comment]
Another thing, passing -Werror=implicit-function-declaration will show that this is a problem.

**Comment by emanuele6** [comment]
Is this still an issue?

**Comment by patrickdepinguin** [comment]
No, not since following recent commit 52d5988afb5999c71fd24484a93efefa2a9e9a8f:

```
commit 52d5988afb5999c71fd24484a93efefa2a9e9a8f (HEAD)
Author: Florian Weimer <fweimer@redhat.com>
Date:   Wed Jun 14 14:41:04 2023 +0200

    C99 compatibility enhancements for the configure script (#2519)
    
    * configure.ac: Enable system extensions
    
    Use AC_USE_SYSTEM_EXTENSIONS to build with _GNU_SOURCE (and similar
    macros on non-GNU systems), to avoid an implicit declaration of the
    strptime function.  This improves compatibility with future compilers
    which do not support implicit function declarations.
    
    * configure.ac: gettimeofday lives in <sys/time.h>
    
    The gettimeofday function is declared in <sys/time.h>, not <time.h>,
    according to POSIX and actual systems.  This avoids a configure
    probe failure with compilers which do not support implicit function
    declarations.
```

I bisected today between a17dd32 (where I knew I still saw the issue) and current head, using gcc 12.3.1.

Note that in order to trigger the issue, I had to add '-std=c99' to AM_CFLAGS in Makefile.am. Buildroot was already passing this flag when the issue was first reported, but at that time I didn't realize this to be a factor.

So , I will mark this issue as closed.
