### ISSUE TITLE
two backslashes needed in  'test("a\\sb")' 

### ISSUE THREAD

**Issue by pkoppstein** [jqlang/jq#1606]
The manual currently only shows one. Also, in the example, a semicolon is required, so the example should read:

    test( “a\\sb”; “x” )

**Comment by nicowilliams** [comment]
Actually, the source does show two.  The built manual shows one.  A layer of backslashes is removed by the doc build process -- but not always...

**Comment by itchyny** [comment]
Duplication of #2197 and was already fixed by  #2229 (80052e5275ae8c45b20411eecdd49c945a64a412).
