### ISSUE TITLE
bug: --slurp option with wildcard segfaults the application

### ISSUE THREAD

**Issue by xswordsx** [jqlang/jq#1618]
#### Environment
**OS:** Windows 10
**jq version:** 1.5
**terminal:** `cmd` under ConEmu (cmder)

#### Setup
```bash
mkdir ./some_random_path/
cd some_random_path
echo '{"a":1}' > file_1.json
echo '{"b":2}' > file_2.json
echo '{"c":3}' > file_3.json
cd ..
```

**Command:**
```bash
jq "." -cM --slurp ./some_random_path/file_*.json
```
|**expected**|**got**|
|-|-|
|`[{"a":1},{"b":2},{"c":3}]`|`segmentation fault`|

Running 
```bash
cat some_random_path/file_*.json | jq -scM
```
 works as expected

**Comment by Alanscut** [comment]
hi @xswordsx 
I tested jq-1.5 that  can handle the scenario you described.It is possible that your usage is wrong.you can try it again.
```
Administrator@desktop MINGW64 ~/Desktop/jq
$ ./jq-jq-1.5/jq.exe "." -cM --slurp ./test/file_*.json
[{"A":1},{"B":1},{"3":1}]
```
