### ISSUE TITLE
How do I find the key for the newest entry?

### ISSUE THREAD

**Issue by xxKeoxx** [jqlang/jq#1626]
I am trying to use jq to get the newest scene from my hue api.  Here is what the json looks like.  I only need the one with the newest date form the lastupdated entry.

Can someone help?

```
"FUX9A2m4LcuF6YG" : {
  "name": "KitchenDay",
  "lights": [
    "6",
    "7",
    "10",
    "11"
  ],
  "owner": "*****",
  "recycle": false,
  "locked": false,
  "appdata": {
    "version": 1,
    "data": "73aGD_r07_d99"
  },
  "picture": "",
  "lastupdated": "2018-02-28T23:43:06",
  "version": 2
}
"lwAoT6dX3oVzsDm": {
  "name": "KitchenDay",
  "lights": [
    "6",
    "7",
    "10",
    "11"
  ],
  "owner": "********",
  "recycle": true,
  "locked": false,
  "appdata": {},
  "picture": "",
  "lastupdated": "2018-02-25T03:35:57",
  "version": 2
}
```

**Comment by pkoppstein** [comment]
1. Whether you post questions here or at stackoverflow, it would be helpful for everyone if you could follow the mcve guidelines (http://stackoverflow.com/help/mcve).  In particular:

a. the input you have published in the question is invalid as JSON.  jq is not very good at handling mangled JSON.

b. you have not included the output you expect.

2. An answer to this question has already been posted at https://stackoverflow.com/questions/49062033/how-do-i-use-jq-to-pull-the-newest-hue-scene-from-the-json-dump

Specifically, if you correct the JSON in the obvious way, and apply the filter given there, you would get:

```
{
  "FUX9A2m4LcuF6YG": {
    "name": "KitchenDay",
    "lights": [
      "6",
      "7",
      "10",
      "11"
    ],
    "owner": "",
    "recycle": false,
    "locked": false,
    "appdata": {
      "version": 1,
      "data": "73aGD_r07_d99"
    },
    "picture": "",
    "lastupdated": "2018-02-28T23:43:06",
    "version": 2
  }
}
```

If you just want the key name ("FUX9A2m4LcuF6YG"), you could modify that filter and instead use:

    to_entries | max_by(.value.lastupdated) | .key

**Comment by xxKeoxx** [comment]
The json I supplied is the output of the following curl command: 
`curl -s http://[hue_ip]/api/[whitelistedid]/scenes/ | /usr/local/bin/jq -r -e '.'`
I just copied the sections to show the differences so sorry about the format.

I did try the suggestion, but I get errors when running it.  What I've been trying to do is search the output for the scene name and from that I only want the key of the newest one. (Using lastupdated)

When I run the suggested solution I get this error:
`jq: error (at <stdin>:0): string ("FUX9A2m4Lc...) has no keys`

Here is what I am running:
`curl -s ${BASEURL}/scenes/ | /usr/local/bin/jq -r -e --arg SCENENAME "${SCENENAME}" '. as $object | keys[] | select($object[.].name == $SCENENAME) | to_entries | [max_by(.value.lastupdated)] | .key'`

So I am clearly doing something wrong.

**Comment by Alanscut** [comment]
hi @xxKeoxx 
If the json format you provided is correct, you try this method to get the value of lastupdated.

```
test.json:

{
"FUX9A2m4LcuF6YG" : {
  "name": "KitchenDay",
  "lights": [
    "6",
    "7",
    "10",
    "11"
  ],
  "owner": "*****",
  "recycle": false,
  "locked": false,
  "appdata": {
    "version": 1,
    "data": "73aGD_r07_d99"
  },
  "picture": "",
  "lastupdated": "2018-02-28T23:43:06",
  "version": 2
},
"lwAoT6dX3oVzsDm": {
  "name": "KitchenDay",
  "lights": [
    "6",
    "7",
    "10",
    "11"
  ],
  "owner": "********",
  "recycle": true,
  "locked": false,
  "appdata": {},
  "picture": "",
  "lastupdated": "2018-02-25T03:35:57",
  "version": 2
}
}
--------result------
root@os-001: cat test.json | jq '.FUX9A2m4LcuF6YG.lastupdated , .lwAoT6dX3oVzsDm.lastupdated'
"2018-02-28T23:43:06"
"2018-02-25T03:35:57"


```
