### ISSUE TITLE
Is there a way to handle empty strings?

### ISSUE THREAD

**Issue by fearphage** [jqlang/jq#1648]
Currently I'm using the following to catch empty strings:

```jq
if . == "" then "--" else . end
```

Is there a more terse method of handling this case? I understand `//` only works with `false` and `null` per the documentation. Is there there another syntax that handles falsey values like the empty string?

**Comment by pkoppstein** [comment]
jq currently doesn't really have anything else to offer, but you might like to consider the following:

    def when(filter; action): if (filter?) // null then action else . end;

This is useful enough to be in a "standard library" for other reasons, and has the fringe benefit of allowing the `if ... then ... else . end` mouthful to be shortened, in your case to:

    when(""; "--")

**Comment by hemflit** [comment]
If you know the input objects will only be strings, and won't include newlines, then this is a workaround that's probably brief and readable enough:

```
scan(".+") // "--"
```

(To properly pass strings with newlines, the scan pattern would have to be `"(?:.|\n)+"` or `"\\p{Any}+"`; this is still shorter than the full if-then-else syntax, but maybe ugly enough to not be a worthwhile workaround.)
