### ISSUE TITLE
JQ: parse error: Invalid numeric literal at line 1, column 3

### ISSUE THREAD

**Issue by TimoC1982** [jqlang/jq#1653]
Hi Guys,

I ran into a little bit vexing jq Problem under windows. 
I have following json file: [https://codeshare.io/2jvLNL](url) that i modify with two different jq commands:
```
jq.exe ".sails[].arrival |= todateiso8601 | .sails[].departure |= todateiso8601" 
jq.exe  "[{nid, includesservices: .includedServices, title, nights, company: .operator.shortTitle, zone: .zones[0].title, schiffsbeschreibung: .ship.factsAndFigures} + (.sails[] | ({ sails_nid: .nid, arrival, departure } + (.cabins[] | { cabinname: .cabinType.title, cabintype: .cabinType.kindName, cabinnid: .cabinType.nid, catalogPrice, discountPrice, discountPercentage, currency } )))   ]"


```
The first command modify in the json the Arrival/departure time value and the second transforms the complete json into an new Array for an easy db Import. That commands runs fine on my old test enviroment and i started the install a new test enviroment. Both are running under Windows 10. Only the powershell versions (i use powershell to invoke jq) differs. On the old enviroment the commands works fine. On the new one i get an Invalid numeric literal at line 1, column 3 error. Any tips?

Regards
Timo

**Comment by bendem** [comment]
running zsh, I don't have an error with either, so I'm going to guess some argument handling changed between your powershell versions and the string is getting interpreted. Maybe try switching to single quotes to prevent powershell from interpreting it?

**Comment by TimoC1982** [comment]
Hi Bendell,
Thanks for your Input. i tried the json & the commands on jqplay and there works tboth fine. I also switched from double quotes to single quotes with no differents. I checked the configuration of both Systems. The old one haves:
```
PSVersion                      5.1.14393.1715
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1715
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

And the new one:

`PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1`

The PS Version differs. The rest is the same. I have no clue...

Regards
Timo

**Comment by TimoC1982** [comment]
Okay i tested on different Windows 10 Systems (with actual patchversion): the error is replicable. Only that old System that had an old Version is still functional.

**Comment by TimoC1982** [comment]
Problem still existing under Windows 10? No tips?

Regards
Timo

**Comment by bgshacklett** [comment]
I'm seeing similar behavior with PowerShell Core on macOS 10.13.4. Writing the command as one would write it for Bash fails with an error indicating that quoted text is being interpreted as an identifier:
```
> '{ "foo":"bar" }' | jq 'select(.foo | contains("bar"))'
jq: error: bar/0 is not defined at <top-level>, line 1:
select(.foo | contains(bar))
jq: 1 compile error
```
The quotes are getting stripped for some reason. PowerShell should not be going anything to the quotes here as the command is wrapped in single quotes which does not allow interpolation. With this in mind, I tried escaping with backslashes, which "fixes" the problem:
```
> '{ "foo":"bar" }' | jq 'select(.foo | contains(\"bar\"))'
{
  "foo": "bar"
}
```

**Comment by TimoC1982** [comment]
Hi @bgshacklett , i tried to excape with backslashes but it looks like that powershell on Windows didn't know that

@bendem 
I also tried to Change from double qoutes to single qoutes. Same issue.

Regards
Timo

**Comment by TimoC1982** [comment]
Hi,

@bgshacklett I tried that way (about file Input). Same error. The funny Thing is: I have two transformations. The first Transformation works always (idependent which of both runs first) only the second Transformation runs into that error.

Regards
Timo

**Comment by TimoC1982** [comment]
I reworked tue Statement and merge both Operation into one. Now it works. My Problem ist fixed but i think that is a General Problem.

**Comment by LachlanArthur** [comment]
If you're using Windows, check the encoding of the input file. jq can't read UTF-16 encoding, which is the default encoding used in PowerShell when redirecting terminal output to a file.

The fix is to convert the file to UTF-8 before passing it to jq.

**Comment by xmaihh** [comment]
it looks like my issue was related to powershell. i need to add `Select Content -Expand Content` which ended up like this.
```powershell
curl 'http://localhost:123456/json/list' | Select Content -Expand Content | jq .[].url > tabs.txt
```

**Comment by Nikongen** [comment]
A comment on this as it took me some time to find out.

## Problem

I was having trouble with jq-1.8.1 in Powershell 7.5.2 working with basically any valid json file.

```powershell
jq empty file.json
>>jq: parse error: Invalid numeric literal at line 1, column 3
```

## The issue

Files were created automatically on Linux by vscode (e.g. .vscode/launch.json) and transferred to a windows machine for testing a powershell script. This issue did not occur on my Linux machine using jq-1.6

ChatGPT gave me a hint: on Windows is almost always caused by a UTF-8 BOM or hidden characters in the file, not by the JSON structure itself. 
Already mentioned in https://github.com/jqlang/jq/issues/45, but search engines point to this issue if you search for the error message

## Solution

Remove BOM
 
```powershell
# Read JSON without BOM and overwrite
(Get-Content file.json -Raw) | Set-Content -Encoding utf8 file.json
jq empty file.json
# No error :)
```



## Some details on my usecase

I was using jq to set the Python Interpreter for the VS-Code Python Debugger using a script. Which worked fine on Linux.
I wanted to allow developing on Windows 11, so I built a powershell script to do the same. This is the content of the json file after processing with jq

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Testfile",
      "type": "debugpy",
      "request": "launch",
      "module": "myproject.test",
      "console": "integratedTerminal",
      "python": "/home/nikongen/.local/share/hatch/env/virtual/myproject/-tTkygWn/qfl/bin/python"
    }
  ]
}
```
