### ISSUE TITLE
Zero byte separator to mimic `find -print0`, pipe to xargs?

### ISSUE THREAD

**Issue by nathanielks** [jqlang/jq#1658]
Hello, hello!

Thank you SO much for jq. It makes my life significantly easier! Thanks! I have a question/feature request. I'd like the ability to use zero-byte separators instead of newlines to mimic the behavior of `find -print0` so I can pipe into `xargs`. I haven't found a way to pipe json to xargs without xargs stripping quotes or treating each line as a separate argument. Being able to separate entries via zero-byte strings would allow me to use the `-0` param in xargs and treat each json object as a separate argument. Here's a command for example:

```bash
aws cloudformation list-stacks \
  | jq -c '.StackSummaries[] | { StackName: .StackId }' \
  | xargs -0 aws cloudformation get-template --cli-input-json
```

**Comment by thedward** [comment]
How about this?

```sh
aws cloudformation list-stacks \
  | jq -cj '.StackSummaries[] | { StackName: .StackId } | tojson+"\u0000"' \
  | xargs -0 aws cloudformation get-template --cli-input-json
```

**Comment by nichtich** [comment]
So this issue can be closed, no?

**Comment by nicowilliams** [comment]
It might be useful to have this as a jq option anyways, so I'll keep it open.

**Comment by bsolomon1124** [comment]
And/or: `-j` takes an optional separator that defaults to `''`.

**Comment by emanuele6** [comment]
superseded by #2659
