### ISSUE TITLE
JV_PRINT_COLOR

### ISSUE THREAD

**Issue by vielmetti** [jqlang/jq#1667]
This patch

https://github.com/stedolan/jq/commit/2d05b5475c98ab46494f193f234e97a7803ddace

is in master but not in the latest releases. With it, there's a breaking change to libjq as jv.h replaces JV_PRINT_COLOUR with JV_PRINT_COLOR.

Impact: some lost time (as noted in https://github.com/jzelinskie/faq/issues/11) sorting out why `faq` builds with the latest rc but fails to build with master.

**Comment by bendem** [comment]
#1352

**Comment by itchyny** [comment]
This issue was opened before the release [1.6](https://github.com/jqlang/jq/releases/tag/jq-1.6) in Nov 2018, so closing this issue.
