### ISSUE TITLE
segfault when executing jq in openwrt LEDE 17.01.4

### ISSUE THREAD

**Issue by bricemiramont** [jqlang/jq#1676]
Hi,
I cross-compile a custom firmware for x86_64 target with jq package.
I use the jq-1.5 release 2 package (default one) in LEDE Reboot 17.01.4

everything compile just fine but when I execute jq in virtualbox or in my intel x86 box I have a segmentation fault.

Has anyone used jq in a x86 target ?
What is wrong ?

Message :
`
root@LEDE:/# jq
[ 3318.497302] jq [ 12169 ]: segfault at 174ab640 ip 00007f77174ddd5f sp 00007ffd6dd381e8 error 4 in libc.so[7f77174ac000+68000]
`

Thank you,

Brice

**Comment by haodong** [comment]
same problem.

**Comment by emanuele6** [comment]
Duplicate of #1598; Fixed by #2519
