### ISSUE TITLE
search by value

### ISSUE THREAD

**Issue by bagcoder** [jqlang/jq#1684]
Given the following input, can I search by value only, to extract the key/value pairs for any entries that FAIL?

{
  "test": {
    "A": "OK",
    "B": "OK",
    "C": "FAIL",
    "D": "OK",
    "E": "FAIL",
    "F": "OK"
  }
}

**Comment by pkoppstein** [comment]
The filter:

    .test | with_entries(select(.value=="FAIL"))

seems to meet your specs.  Tacking on `| keys_unsorted[]` would yield:

     "C"
     "E"

For future reference, please ask usage questions at stackoverflow.com with the jq tag: https://stackoverflow.com/questions/tagged/jq
