### ISSUE TITLE
More complex examples!

### ISSUE THREAD

**Issue by pozix604** [jqlang/jq#1692]
After getting familiar with _jq_, I'm starting to recognize that it has some incredible power. Previously, when I need to manipulate json in complex ways, I would resort to Python, but _jq_ may offer a better way.

That said, I'm having real difficulty grasping how to write more complex filters than one-liners. I see in the manual that it is possible to define functions and have flow control, but there are no examples that use multiple features at the same time that gives an idea how a complex filter can be assembled.

Is this somewhere else that I haven't found? Should it be in the manual? Are there examples elsewhere on the Internet I can look at?

**Comment by pkoppstein** [comment]
The jq [FAQ](https://github.com/stedolan/jq/wiki/FAQ) and [Cookbook](https://github.com/stedolan/jq/wiki/Cookbook) are usually the first places to look; you could then check http://rosettacode.org/wiki/Category:Jq
