### ISSUE TITLE
Confusing contains() behavior

### ISSUE THREAD

**Issue by mcandre** [jqlang/jq#1711]
When `contains()` is applied against an array of strings, then the user could reasonably expect that the array values are checked for exact-match against the search string. In fact, when `jq` runs this kind of query, the `contains()` is applied in a substring-match way against the array values, which can yield inaccurate output.

I suspect this is a result of how `contains()` is implemented recursively, where an array `contains()` then applies `contains()` across its individual elements. This almost makes sense, but unfortunately most people would say that `contains()` for strings and `contains()` for arrays would actually have completely different semantics: arrays should look for exact value matches and strings should look for substring matches.

As a workaround, I am using an raw combination of `. ==` with `select()`, piped to `length`, compared with zero :P

**Comment by pkoppstein** [comment]
@mcandre - Many people would agree with you, not only regarding the "unexpected" behavior of `contains` but also `index`.  It is worth noting, however, that viewing strings as arrays of characters is not so bizarre. This at least takes away some of the mystery.

In any case, besides the documentation in the jq manual, there is supplementary documentation in the jq [FAQ ](https://github.com/stedolan/jq/wiki/FAQ) -- see i.p.:

    𝑸: Given an array, A, containing an item, X, how can I find the least index of X in A?

For substring matches, also bear in mind the availability of `test/1`.

**Comment by pkoppstein** [comment]
Combining the objects into an array can be done in a single step, i.e. without the -s option

    $ jq -n '[inputs | {"object": . , "filename": input_filename, "lineNumber": input_line_number}]' *.json
```
[
  {
    "object": 1,
    "filename": "1.json",
    "lineNumber": 1
  },
  {
    "object": 2,
    "filename": "2.json",
    "lineNumber": 1
  },
  {
    "object": 3,
    "filename": "3.json",
    "lineNumber": 1
  }
]
```

**Comment by rgordill** [comment]
Exactly that. @mcandre, can you note here your workaround? I am facing exactly the same behaviour, because I am implementing a "selector" lookup.

**Comment by wader** [comment]
@rgordill for `==` i think you can do something like `... | select(. == ("a", "b", "c"))` for `!=` maybe something like `... | select([. != ("a", "b", "c")] | all)`. If it's a lot of strings to check i would guess it could be faster to build an object as use `has` somehow.

**Comment by rgordill** [comment]
I don't get the alternative.

My question is because I though contains() covers this scenario:

Input:

```
{
"check": "true",
"application: "demo-app"
}
```

contains({"application": "demo-app"})   -> true (ok)
contains({"application": "app"}) -> false (but actually throws true)

**Comment by wader** [comment]
Ah sorry, thought you wanted to compare exact values. Maybe in your case you can do something like this:
```jq
def contains_partial($v): (. + $v) == .;
```
Then use it like this:
```
{check: true, application: "demo-app"} | contains_partial({application: "demo-app"}) => true
{check: true, application: "demo-app"} | contains_partial({application: "app"}) => false
```

Alternatively something like `isempty(select(.application == "demo-app")) | not` should work also.
