### ISSUE TITLE
input filename bug with "_"

### ISSUE THREAD

**Issue by azev** [jqlang/jq#1721]
jq v. 1.5 / Windows 10 64bit

This command line crashes jq because it have `_` in the 1st filename
`jq -f merge.jq "file_1.json" --argfile o1 "file_2.json"`

This command line **does not** crashes jq because it does not have `_` in the **1st filename**
`jq -f merge.jq "file1.json" --argfile o1 "file_2.json"`

![s20180921143127](https://user-images.githubusercontent.com/6639188/45896563-e6daf780-bdaa-11e8-91f7-2d65c020650e.png)

**Comment by emanuele6** [comment]
Someone should check if this bug can still be reproduced

**Comment by wader** [comment]
`--argfile` was removed in 1.7 #2768 but might be good to try reproduce with some other input file option?

**Comment by emanuele6** [comment]
The issue is with the input file argument, not the `--argfile` argument:

> This command line crashes jq because it have `_` in the 1st filename
> `jq -f merge.jq "file_1.json" --argfile o1 "file_2.json"`
> 
> This command line **does not** crashes jq because it does not have `_` in the **1st filename**
> `jq -f merge.jq "file1.json" --argfile o1 "file_2.json"`

**Comment by wader** [comment]
Ah sorry misread

**Comment by emanuele6** [comment]
I tested [1.7.1's `jq-windows-amd64.exe` download](https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-windows-amd64.exe) on a windows 10 PC and I can't repro.
