### ISSUE TITLE
Bug in sub? different types of apostrophe

### ISSUE THREAD

**Issue by mfeblowitz** [jqlang/jq#1730]
**Describe the bug**

This is a very obscure bug. It appears to boil down to the type of apostrophe that appears in the text. A '  (U+0027) versus a ’ (U+2019). 

This occurs when the character is in the data - not on the jq script nor in the sub pattern.

The simplest form of the substitution is something like 
```
sub("Vx " ;  "")
```
For data without the apostrophe - (U+2019) - or with the other, the results are as expected:

```
"company s trading algorithms Vx  go"

"company s trading algorithms  go"
```
The "Vx" is gone. 

But put in the (U+2019) apostrophe upstream and it goes wrong:
```
"company ’s trading algorithms Vx  go"

"company ’s trading algorithmx  go"
```
Note that the V is gone - but  so are and space before it and the preceding "s". And the x remains. 

I'm guessing this has something to do with the character encoding, suggesting that the multi-byte(?) character is messing with offset counts.

Is there a recommended way of working around this, e.g., by transforming the incoming text so it doesn't corrupt the substitutions?

The data looks odd because I've trimmed down the real case to the bare bones. The original data -which exhibited the problem was this:
```
 "[ARG1: a company ’s trading algorithms] [V: go] [ARG2: awry]"
```
Surprisingly, neither the square brackets nor the colon played a role. The full scan pattern was supposed to trim the string down to 

```
 "a company ’s trading algorithms  go awry"
```
but instead ended up as:
```
"a company ’s trading algorithms: go: awy."
```

**To Reproduce**

Using this to change text:

See above

**Expected behavior**
See above
**Environment (please complete the following information):**
 - macOS version 10.13.6
 - jq version 1.5

**Additional context**

**Comment by pkoppstein** [comment]
> Is there a recommended way of working around this

I believe that upgrading to a later version than 1.5 is most likely to resolve the problem.

Since you're using a Mac, you might want to look at https://stackoverflow.com/questions/37668134/how-to-install-jq-on-mac-by-command-line

**Comment by mfeblowitz** [comment]
Standard ```brew install jq``` installs 1.5.3, which still has the problem. (Probably the same as what I had, since "jq --version" only provides 1.5 as the version). 

The development master (```brew install --HEAD jq```) has fixed the problem. 

Thanks
