### ISSUE TITLE
Can't specify FIELD_COLOR in JQ_COLORS env var

### ISSUE THREAD

**Issue by coding-at-work** [jqlang/jq#1739]
**Describe the bug**
Thanks to https://github.com/stedolan/jq/pull/1397 there is a way to specify the colours used in the `jq` output, but it's not possible to change the FIELD_COLOR (used for dictionary keys for example).

**To Reproduce**
`JQ_COLORS="1;30:0;31:0;32:0;33:0;34:1;35:1;36" ./jq -Cn '[{"a":true,"b":false},123,null]'
[{"a":true,"b":false},123,null]`

<img width="685" alt="not-all-red" src="https://user-images.githubusercontent.com/43142559/46801226-5749b880-cd5a-11e8-9744-d56942a7431d.png">

**Expected behavior**
Another field in the env var to override the color of field names.

**Environment (please complete the following information):**
 - OS and Version: macOS 10.14
 - jq version 1.6rc1

**Comment by nicowilliams** [comment]
@jdel Yes, PRs are welcome.  This wouldn't be difficult to implement, no.

**Comment by DavidBiesack** [comment]
Please also fix the [manual](https://stedolan.github.io/jq/manual/); it only defines colors up to 37, but the default uses 39 (which should be 37)

**Comment by t829702** [comment]
is this abandoned?    I'm looking for customizing some jq output colors just realized it doesn't change field_colors;  wonder    why the PR is stuck more than a year not merging?
