### ISSUE TITLE
jq can't manage arrays of more than 100 entries?

### ISSUE THREAD

**Issue by danbadjar** [jqlang/jq#1744]
**Describe the bug**
jq doesn't work managing arrays of more than 100 entries

Commands:

command | jq '.invoices[100]'

I obtain "null" as output.
If I use
command | jq '.invoices[99]' 
everything is working fine

My output provides an array of 108 records

Can anyone help me?
Thanks

**Expected behavior**
I should have the output of the entry number 100 in the array

**Environment (please complete the following information):**
Linux
 jq 1.5

**Comment by leonid-s-usov** [comment]
There must be some issue with your input, since 100 is not even close to array size limitation 
Here is a working snippet addressing 101st element in an array
https://jqplay.org/s/UuuPmqHpjT

**Comment by leonid-s-usov** [comment]
Well, here is a better fitting counter example to your case
``` jq -n '{ invoices: [range(1, 200)]}' | jq '.invoices[100]'```

Please examine the actual output of your `command`, and if it is still unclear, please post the full json of the input to the jq program.

**Comment by danbadjar** [comment]
Hello and thanks for your help.
With your example I can obtain the number "100" , I've tried to change the range and everything is working fine.
The last command outputs me "100", but how can I do to obtain the entire field list of the record #100 ?
Thanks

**Comment by LordMike** [comment]
@danbadjar perhaps your object at `[100]` is null ?

**Comment by Alanscut** [comment]
hi @danbadjar 
You can try without index，like this.
```
test.json:
{
  "releases": [
    {
      "id": "b8c015c8-2418-3e11-b71f-f9e391d94f6e",
      "date": {
        "year": 1995
      }
    },
    {
      "id": "60f38cbb-2c65-40d1-85fd-6d99ca3feb54",
      "date": {
        "year": 1998,
        "month": 6
      }
    },
    {
      "id": "d7838033-55fe-4fa4-949a-7bb96cc88839",
      "date": {
        "year": 1995,
        "day": 6,
        "month": 11
      }
    }
  ]
}

-------------------------test--------------------

root@os-001:jq# cat test.json | ./jq '.releases[]'
{
  "id": "b8c015c8-2418-3e11-b71f-f9e391d94f6e",
  "date": {
    "year": 1995
  }
}
{
  "id": "60f38cbb-2c65-40d1-85fd-6d99ca3feb54",
  "date": {
    "year": 1998,
    "month": 6
  }
}
{
  "id": "d7838033-55fe-4fa4-949a-7bb96cc88839",
  "date": {
    "year": 1995,
    "day": 6,
    "month": 11
  }
}

```

**Comment by danbadjar** [comment]
Out of date
