### ISSUE TITLE
`del(.a)` and `.a |= empty` do not behave the same

### ISSUE THREAD

**Issue by Twey** [jqlang/jq#1751]
The manual states that returning no values from the filter on the right of a filter-assignment has the same effect as `del`, but this doesn't seem to be the case: instead, it causes the whole input to be replaced with `null`:

```
[twey@fehu:/tmp]$ echo '{"a": 5}' | jq 'del(.a)'
{}

[twey@fehu:/tmp]$ echo '{"a": 5}' | jq '.a |= empty'
null
```

Quoth the [manual](https://stedolan.github.io/jq/manual/#Update-assignment:|=):
> If the right-hand side outputs no values (i.e., `empty`), then the left-hand side path will be deleted, as with `del(path)`.

I don't know whether this is a documentation bug, an implementation bug, or just poor understanding on my part, but I was certainly confused ☺

**Comment by fadado** [comment]
This is an old and fixed bug. Using jq-1.6rc1-17-g71865de-dirty:

```
$  echo '{"a": 5}' | jq 'del(.a)'
{}
$ echo '{"a": 5}' | jq '.a |= empty'
{}
```

By the way, the operator `|=` resolves into a call to `_modify` defined in [builtin.jq](https://github.com/stedolan/jq/blob/master/src/builtin.jq).  This is the builtin definition:

```
def _modify(paths; update):
    reduce path(paths) as $p (.;
	 label $out
	 | (setpath($p; getpath($p) | update) | ., break $out)
	 , delpaths([$p]));
```

To better understand `_modify` study this version:

```
def _modify(paths; update):
    reduce path(paths) as $p (.;
        first(setpath($p; getpath($p) | update) 
              , delpaths([$p])));
```

You can see that `delpaths` is only called if `update` produces `empty`!

JJOR

**Comment by leonid-s-usov** [comment]
There is still no test coverage for this though.

**Comment by emanuele6** [comment]
Outdated issue
