### ISSUE TITLE
'--exit-status' incompatible with '@sh' because @sh formats null inputs

### ISSUE THREAD

**Issue by zanerock** [jqlang/jq#1792]
**Describe the bug**

Formatting output with '@sh' (or @text of course) changes the behavior of '--exit-status/-e'. I wouldn't expect formatting to change a 'true/false' state.

**To Reproduce**

    $ catalyst-cli zane$ cat package.json | jq -e '.catalyst."version-check".ignore'; echo $?
    null
    1
but

    $ cat package.json | jq -e '.catalyst."version-check".ignore | @sh'; echo $?
    "null"
    0

**Expected behavior**

'@sh' should not change the exit value.

**Environment (please complete the following information):**
 - OS and Version: MacOS Mojave (10.14.2)
 - jq version: 1.6

**Comment by zanerock** [comment]
That makes sense.

I think something like `exitstatus` is what I would want in my use case as I would like to capture the output if not-falsy, but terminate if falsy. Right now i have to run jq once to check if a field exists and then a second time to extract the data if it does. What I want to do is a one-liner like:

    echo "$DATA" | jq -e '.field | exitstatus | @sh'

As is, I would still argue you have a bug somewhere, though it may be in the docs. :)

As for how `@sh` should treat null... as someone who uses bash a lot, I would actually really expect null to output as an empty string. That would be the logical equivalent since `null` is generally falsy and "" is falsy in bash.

This would actually be another way to solve the above problem without using the exit status at all. I'm using jq mostly in bash scripts and

    VAR=$(echo "$DATA" | jq '."non-existent-field"')

resulting in `$VAR == ""` would work well in the code and was actually what I was expecting. I understand that would break existing usage. Not knowing much about it, something adding `@bash` and deprecating `@sh` comes to mind.

**Comment by nicowilliams** [comment]
@zanerock sometimes I think it'd be nice to have a loadable shell builtin for jq...  Or even tighter shell integration with jq.  Make the shell better, more like the Windows PowerShell in a way.

Anyways, I'll do something about this in a few weeks, or if you have a PR... :)

**Comment by zanerock** [comment]
@nicowilliams Nothing I can't work around on my end, so no worries.
