### ISSUE TITLE
Print in one line objects with one entry

### ISSUE THREAD

**Issue by DexterMagnific** [jqlang/jq#1797]
Hi,

I have a wish for jq. I would like an option similar to -c but only if the object contains one entry.

Example:
```
 "Parameters": {
    "Enable": 1,
    "Gain": -96,
    "Volume": [
      { "Volume Step": 0 },
      { "WetdB": -12 },
      { "Threshold": 0 },
      { "MakeUp": 0 },
      { "Slope": 0 },
   ]
}
```

As you can see, the objects which contains `VolumeStep` and co do not have new lines after `{` and before `}`.

Thanks

**Comment by nicowilliams** [comment]
This is a dup of some other issue, and a frequently-requested feature.

**Comment by itchyny** [comment]
Closing as duplication of #643, #1400.
