### ISSUE TITLE
Rebuild manuals using fix from #1716

### ISSUE THREAD

**Issue by nicowilliams** [jqlang/jq#1811]

**Comment by itchyny** [comment]
The fix #1716 was included and built at 76c044f301c3d33b122974e405a80f2b0775dce7 on Mar 3, 2020 (stedolan also rebuilt to follow the repository transfer recently; d08a76eb5e498a3660a7d9d88f3e43ac0fbfb820, a91a3033b0b1fd6b90408a5d8e04052e5b4368ec), so closing the issue.
