### ISSUE TITLE
doc specifies wrong version for openSUSE

### ISSUE THREAD

**Issue by 6d77** [jqlang/jq#1831]
**Describe the bug**
The documentation at https://stedolan.github.io/jq/download/ states that the openSUSE repository would provide version 1.4. However the provided version is 1.5 for all Leap versions and 1.6 for Tumbleweed.

**Environment (please complete the following information):**
- openSUSE Leap 42.3, 15 provide jq version1.5
- openSUSE Tumbleweed provides jq version 1.6

See https://software.opensuse.org/package/jq for openSUSE version info.

**Comment by emanuele6** [comment]
> * jq is in the official [openSUSE](https://software.opensuse.org/package/jq) repository. Install using `sudo zypper install jq`.

Fixed by 9a590427db237d0aed5efe7eeaf13eb2bb3299d6 #2619
