### ISSUE TITLE
JQ DOCs: add section links to keywords

### ISSUE THREAD

**Issue by nyurik** [jqlang/jq#1848]
I would like to propose the [JQ manual](https://stedolan.github.io/jq/manual/) to have all keywords into links to the corresponding topic.  For example, every time `reduce` is written as a keyword (red text), it should link to `#Reduce` docs section.  This will make searching / navigating the docs far easier. Thank you!

P.S. for bonus points, navigating to a section via an anchor should also expand corresponding examples, but this might be a separate (and far more complex) task.

**Comment by nicowilliams** [comment]
Sure.  We might like to replace the manual with something more like [this](https://github.com/stedolan/jq/wiki/jq-Language-Description) enhanced with a description of the jq processor.
