### ISSUE TITLE
Released sources are not PGP-signed

### ISSUE THREAD

**Issue by eli-schwartz** [jqlang/jq#1853]
While it is nice that the prebuilt binaries have PGP signatures, the recommended installation method is usually to work through Linux distribution package managers if possible -- and these are not authenticated by PGP keys.

At least Arch Linux supports the ability to specify two sources: the tarball and a signature .asc file -- if signatures exist for a source artifact, then they will be validated using a PGP fingerprint baked into the build recipe. See e.g. https://wiki.archlinux.org/index.php/Makepkg#Signature_checking

It would be beneficial for jq to have a full chain of cryptographic trust from the upstream release all the way to end-user machines.

**Comment by eli-schwartz** [comment]
The reason I initially noticed this issue is because it seems the jq sources have been silently modified: https://bugs.archlinux.org/task/61876

**Comment by lanodan** [comment]
Seconding this one as artifacts should come with authenticated signatures.
With the note that signify (from OpenBSD but it has unofficial ports to other Unixes) can make it much simpler to setup.

**Comment by eli-schwartz** [comment]
Any word on this? There hasn't been a new release of jq since I submitted the issue, but if it's intended to be implemented starting with the next release then I would be grateful to know that. If it's still a matter of discussion, then what can we do to argue in favor of it?

**Comment by wtlangford** [comment]
Sorry for the delayed response!
I intend to add this to the process when we release the next version.
Things to note- I don't control the automatically-provided github assets, so I can't/won't PGP sign them (I can't guarantee the files won't change), but I can sign the tarballs that we provide.

**Comment by eli-schwartz** [comment]
Thanks! The manually uploaded source tarballs will be fine, and that is what many projects do.

Especially given that the automatically generated github assets will never contain things like:
- submodules
- `autoreconf -fi` artifacts
- anything that autotools lets you ship in a dist tarball via https://www.gnu.org/software/automake/manual/html_node/Fine_002dgrained-Distribution-Control.html

**Comment by itchyny** [comment]
Since the release [jq 1.7](https://github.com/jqlang/jq/releases/tag/jq-1.7), the tarball (jq-1.7.tar.gz) is PGP-signed ([jq-1.7.tar.gz.asc](https://github.com/jqlang/jq/blob/master/sig/v1.7/jq-1.7.tar.gz.asc)).
