### ISSUE TITLE
Docker image location on Docker Hub unclear

### ISSUE THREAD

**Issue by znerd** [jqlang/jq#1864]
**Describe the bug**
The README file does not clarify where the Docker image can be found.

**To Reproduce**
Check the README file.

**Expected behavior**
For a popular software project like `jq` (almost 14K stars on GitHub) I would expect there to probably be a Docker image. And, low and behold, there is a `Dockerfile` in the code repo. However, there is no mention of a Docker container image (location) in the README file.

**Suggested solution:**
If there is no (official) Docker container for `jq`, then I suggest to clearly state that in the README file.

If there is an official one, then it would be good to reference that from the README file, and how to use it.

**Environment (please complete the following information):**
 - OS and Version: any
 - jq version: latest (currently 1.6)

**Comment by ad-si** [comment]
This seems to be the official one: https://hub.docker.com/r/stedolan/jq
But it hasn't been updated in 4 years (!).
@stedolan Can we prioritize this issue a little and can you please release the latest version on Docker Hub 😉

**Comment by KeepMasterBranch** [comment]
The hacker known as 4chan built a docker image with a compromised binary that add randomly racial slurs to any json. Now I'm offended every time I use `jq`. :( Thanks for no up to date official docker images.
