### ISSUE TITLE
Instructions to build tarball unclear

### ISSUE THREAD

**Issue by rain-1** [jqlang/jq#1872]
It was difficult to build the 1.6 tarball from source with builtin-onigurama, the expected ./configure && make fails.

I had to do this extra step:

```
cd modules/onigurama
autoreconf -i
./configure
```

then jq-1.6 built correctly.

I had to guess the command `autoreconf -i`, so this info could be added to the README.

**Comment by nicowilliams** [comment]
@rain-1 ouch, yeah, that's going to require re-issuing the tarball.  Thanks for the report!

**Comment by wtlangford** [comment]
We need to be careful when re-issuing the tarball, because some package sources keep shasums of our tarballs.

**Comment by nicowilliams** [comment]
@wtlangford yeah.  Maybe it's best to just release 1.7 and be done.  We need to finish two big code reviews and a few PRs.
