### ISSUE TITLE
tonumber lossage?

### ISSUE THREAD

**Issue by zenspider** [jqlang/jq#1886]
**Describe the bug**

I assume this is because javascript defines all numbers as floats (doubles? long doubles?) and that's what you're using to represent numbers internally, even if they lex as integers... but I'm having a situation where `tonumber` is morphing a stream I'm filtering (my twitter archive & the IDs are huge).

**To Reproduce**

```
% echo '["282324313233842176"]' | jq ".[] | tonumber"
282324313233842180
```

**Expected behavior**

```
% echo '["282324313233842176"]' | jq ".[] | tonumber"
282324313233842176
```

I assume this is what is going on:

```ruby
>> "%b" % 282324313233842176.0
=> "1111101011000001000111011110010001110000100110000000000000"
>> "%b" % 282324313233842180.0
=> "1111101011000001000111011110010001110000100110000000000000"
```

but, I can't actually reproduce the result output using C's conversion functions:

```c
#include <stdio.h>
#include <stdlib.h>

int main() {
  const char * s = "282324313233842176";

  float  f      = strtof(s,  NULL);
  double d      = strtod(s,  NULL);
  long double l = strtold(s, NULL);

  printf("bad/jq =\n    282324313233842180\n");
  printf("s = %s\n", s);
  printf("f = %f\n", f);
  printf("d = %f\n", d);
  printf("l = %LF\n", l);

  return 0;
}
```

outputs:

```
bad/jq =
    282324313233842180
s = 282324313233842176
f = 282324315083374592.000000 (obviously wrong by a wide margin)
d = 282324313233842176.000000
l = 282324313233842176.000000
```

So... maybe this is just a width problem?

**Environment (please complete the following information):**
 - OS and Version: OSX, 10.13.6
 - jq version: 1.6

**Comment by wtlangford** [comment]
So jq's `strtod` is... special.

```c
jv dbl = jv_number(282324313233842176);
struct dtoa_context ctx;
jvp_dtoa_context_init(&ctx);
char buf[64] = {0};
printf("C prints: %f\n", jv_number_value(dbl));
char *s = jvp_dtoa_fmt(&ctx, buf, 282324313233842176);
printf("we print: %s\n", s);
jvp_dtoa_context_free(&ctx);
```
Gives us this:
```
C prints: 282324313233842176.000000
we print: 282324313233842180
```

This might actually be a bug. @nicowilliams, thoughts?

**Comment by zenspider** [comment]
I was trying to pull all that together. You were much faster than me. Thank you!

**Comment by nicowilliams** [comment]
Yeah, I would say this is a bug.

**Comment by Alanscut** [comment]
hi ， @zenspider 
Execute the same command in the master branch, this problem does not appear,the bug should be fixed.
```
echo '["282324313233842176"]' | jq ".[] | tonumber"

master  :
282324313233842176

version 1.6:
282324313233842180


```

**Comment by nicowilliams** [comment]
Yeah, but I bet it's only fixed when using the new `decnum` functionality by @leonid-s-usov...

**Comment by nicowilliams** [comment]
I believe jq has its own dtoa to in order to produce @stedolan's preferred output representation, or something like that.  We'd have to ask @stedolan, but he's hard to get a hold of.

**Comment by lamontj** [comment]
I am also running into this with 1.6.

```
echo '"8884390776842768416"' | jq 'tonumber'
8884390776842768000
```

**Comment by itchyny** [comment]
I thinks this is already fixed in the master HEAD, thanks.
```sh
 % jq --version
jq-master-50a7022
 % echo '"8884390776842768416"' | jq 'tonumber'
8884390776842768416
```

**Comment by zenspider** [comment]
Confirmed that this is fixed on HEAD. Is there a timeframe on releases on this project?

**Comment by zenspider** [comment]
I'll leave it to the maintainer to close this based on their process.

**Comment by emanuele6** [comment]
jq 1.7 released with the fix. closing
