### ISSUE TITLE
JQ 1.5/1.6 bigint

### ISSUE THREAD

**Issue by TimoC1982** [jqlang/jq#1890]
Hi Guys,

I have actually a situation were i run into the BIGINT Problem and the haziness with that in jq 1.5/1.6 (in a Windows enviroment).
I read the issue reports and thought that if i transform the number to a string, i can handle that. But i test it with a specific command and the result is the same

`[. | { last_update: .starbase_detailed_scan.last_update_time, user_name: .starbase_detailed_scan.owner_name, alliance_id: .starbase_detailed_scan.owner_alliance_id | tostring, drydocks: .starbase_detailed_scan.num_drydocks, tier: .starbase_detailed_scan.owner_level, defence_plattform: .starbase_detailed_scan.num_defence_platforms, shield_triggered: .starbase_detailed_scan.player_shield.triggered_on, shield_end: .starbase_detailed_scan.player_shield.expiry_time, parsteel: .starbase_detailed_scan.resources["2325683920"], tritanium: .starbase_detailed_scan.resources["743985951"], dilithium: .starbase_detailed_scan.resources["2614028847"], user_id: .starbase_detailed_scan.owner_user_id, defence_rating: .starbase_detailed_scan.defense_rating }] `

result:

> [{"last_update":"2018-12-23T19:26:24","user_name":"Hamita40","alliance_id":"774615702811599900","drydocks":3,"tier":19,"defence_plattform":3,"shield_triggered":"0001-01-01T00:00:00","shield_end":"0001-01-01T00:00:00","parsteel":183649,"tritanium":22459,"dilithium":7074,"user_id":"a2588903decc455283c88508f6a7fedf","defence_rating":25200}]

The Alliance_id is not correct. The correct id is: 774615702811599864

Is there any Workaround?

BR
Timo

**Comment by leonid-s-usov** [comment]
If your original ID is not a string initially, then conversion to string will not help, as the number will lose precision at the parsing stage

Maybe you could try and build from the source at [this rebased PR](https://github.com/stedolan/jq/pull/1752)? This should fix your problem.

**Comment by TimoC1982** [comment]
Hi Leonid, okay thanks for the info. No idea how to build a source that is runable under Windows... BR Timo

**Comment by nicowilliams** [comment]
@TimoC1982 you can get the latest `jq.exe` for @leonid-s-usov's contribution at https://ci.appveyor.com/api/buildjobs/y4fu4vqa49e6dy6o/artifacts/jq.exe (you can find this by going to the repo page https://github.com/stedolan/jq and clicking on the windows build status button at the top of the README, then click on the project's history, and look for @leonid-s-usov's PR, click on that build, then click on whichever build you need (32- or 64-bit), then click on artifacts, then save the artifact you're looking for.  I'd appreciate if you test it and let us know how that works for you.

**Comment by emanuele6** [comment]
jq 1.7 released with support for large literal numbers. closing
