### ISSUE TITLE
halt_error prints "jq: error:" in master

### ISSUE THREAD

**Issue by step-** [jqlang/jq#1902]
**Describe the bug**

In MSYS2 nightly builds `halt_error` prints "jq: error:" before any output. Can "jq: error:" be removed from output? The 1.6 release build from the official MSYS2 package repo doesn't print "jq: error:", and niether do the Linux builds.

**To Reproduce**

1. Download a Windows nightly.
2. `jq -n '"test" | halt_error(1)'`

```sh
$ nightly/win64/jq --version
jq-1.6-94-gaaf200f
$ nightly/win64/jq.exe -n '"test" | halt_error(1)'   # wrong: extra "jq: error: "
jq: error: test                                 
```

**Expected behavior**

```sh
$ /mingw64/nightly/jq --version
jq-1.6
$ /mingw64/bin/jq -n '"test" | halt_error(1)'    # expected output: next line
test                                            
```

**Environment (please complete the following information):**

 - Windows 10 Enterprise x64
 - jq-1.6-94-gaaf200f 2019-05-12

**Comment by nicowilliams** [comment]
Hmm, ok.  This was the result of a fix for a number of cases where errors were not identified as coming from jq, but I think you're right and `halt_error`'s message should not be prefixed with `jq: error: `.

**Comment by nicowilliams** [comment]
FYI, MSYS has nothing to do with it.
