### ISSUE TITLE
Consider behavior of {(empty): empty, ...} vs [empty, ...]

### ISSUE THREAD

**Issue by anthonyrisinger** [jqlang/jq#1903]
The object construction syntax looks to gather outputs in the same way array syntax does, but has no mechanism to cancel key production in the same way `empty` cancels item production in an array:

```console
$ jq -cn '[123, empty, 789]'
[123,789]
$ jq -cn '{a:123, (empty): empty, c:789}' # Expected
{"a":123,"c":789}
$ jq -cn '{a:123, (empty): empty, c:789}' # Actual
```

Are there options we can move on?

**Comment by pkoppstein** [comment]
> Are there options we can move on?

One option would be to adopt the "from_entries" point of view of object construction:

```
$ jq -cn '[{"key":"a", "value":1}, {"key": empty, "value": 2}] | from_entries'
{"a":1}
```

**Comment by anthonyrisinger** [comment]
Yeah heh, that's _exactly_ what I was looking to avoid :-)

Entries-related functions are fine (and I use them heavily too), but they
are super verbose and require oodles of intermediate kv objects... I was
reeeeeally hoping when I tried this, I'd finally have a succinct way to
build objects.

This change aligns `{key: empty}` with a the related "delete assignment"
pattern, ie. `(.key, ...) =| empty`.

**Comment by anthonyrisinger** [comment]
Yeah heh, that's _exactly_ what I was looking to avoid :-)

Entries-related functions are fine (and I use them heavily too), but they
are super verbose and require oodles of intermediate kv objects... I was
reeeeeally hoping when I tried this, I'd finally have a succinct way to
build objects.

This change aligns `{key: empty}` with a the related "delete assignment"
pattern, ie. `(.key, ...) =| empty`.

**Comment by nicowilliams** [comment]
Oof.  Making `{(empty):...}` work as you'd like (which I too would like) would require changing `src/parser.y` to prepend a `FORK` to each such `dictpair` then arrange to resolve the target branch to be the next such dictpair or the end of the object expression.  It's clearly the right thing to do.

**Comment by anthonyrisinger** [comment]
@nicowilliams do you think `empty` should have the same effect, for both key and value? I wrote it both ways over a few posts, but wasn't explicit.

The thing that surprised me the most when I tried this was `empty` canceling the entire output -- ok nly for objects -- no matter where it was.

I like "either `empty` cancels the pair", because it aligns with both delete-assignment [key] and array production [value].

**Comment by nicowilliams** [comment]
@anthonyrisinger `empty` as either key or value should have the effect that the one `dictpair` where it occurs is skipped.

**Comment by emanuele6** [comment]
This would be a very badly breaking change, and it also implies changing this behaviour of:
```jq
[ "foo", "bar" ] |
{ (.[]): "hi" }
```
so that it returns
```json
{"foo":"hi","bar":"hi"}
```
instead of
```json
{"foo":"hi"}
{"bar":"hi"}
```

Even though it would have been nicer if object were constructed that way, there is no way this is a reasonable change, right?
Can this issue be closed?
