### ISSUE TITLE
Merge arrays

### ISSUE THREAD

**Issue by init-5** [jqlang/jq#1906]
I have a json file like this (two lines, two arrays):
["Tickets","Tickets by Month"]
[["April",379],["December",395],["February",240],["January",339],["March",335],["November",486]]

I need this (one continuous line one array of arrays):

[["Tickets","Tickets by Month"],["April",379],["December",395],["February",240],["January",339],["March",335],["November",486]]

I have not been able to figure out how to make this happen, can anyone assist?

**Comment by pkoppstein** [comment]
Please ask usage questions such as this at stackoverflow.com with the jq tag: https://stackoverflow.com/questions/tagged/jq

That way, your question will most likely be answered more quickly, and others will more likely benefit from the answer(s).

**Comment by itchyny** [comment]
```bash
 $ jq -c <<EOF '[.] + input'
["Tickets","Tickets by Month"]
[["April",379],["December",395],["February",240],["January",339],["March",335],["November",486]]
EOF
[["Tickets","Tickets by Month"],["April",379],["December",395],["February",240],["January",339],["March",335],["November",486]]
```
