### ISSUE TITLE
In jenkins job i am not able to use this commanad jq -r 'to_entries | map("\(.key)=\(.value)") | .[]'

### ISSUE THREAD

**Issue by uday202** [jqlang/jq#1937]
i am trying to read secrets from secrets manager and mapping with jq is not working

	      sh "/root/bin/aws secretsmanager get-secret-value --region "us-east-1" --secret-id $environment/$repoName --query SecretString --output text | jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' >> /microservices/application.properties"

Error:
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 171: unexpected char: '\' @ line 171, column 183.
   xt | jq -r 'to_entries | map("\(.key)=\(

**Comment by pkoppstein** [comment]
1. As the error message makes clear, jq never gets to startup, so you've posted this problem report at the wrong place.  Yet another reason to use stackoverflow.com for usage issues.

2. It looks like you're trying to include double-quotation marks within a string defined by double-quotation marks, so if you're going to stick with that approach, you'll have to escape the inside quotes. It might also help with debugging to run a simple pipeline such as:

    /root/bin/aws secretsmanager get-secret-value --region "us-east-1" --secret-id $environment/$repoName --query SecretString --output text |
     jq -r 'to_entries | map("\(.key)=\(.value)") | .[]' 

3. If you haven't already done so, it would be a good idea to try to debug the problem yourself, e.g. by prefacing the whole string with `echo` and changing the ">>" to something like GTGT until you're confident the mechanics of quoting are in order.

4. FWIW, the jq filter itself looks OK, though `to_entries[] | "\(.key)=\(.value)"` would be better.

**Comment by uday202** [comment]
I am confused , can you explain detail please.
i kept all my secrets in secrets manager. i need those secret values to be append in aplication.properties from secrets manager. i am working in jenkins i need to append secrets to application.properties.

**Comment by saiyedsahilhussain** [comment]
"aws secretsmanager get-secret-value --secret-id main/env --query SecretString --output text| jq -r \\\"to_entries | .[] | \\\\\\\"\\\\(.key)=\\\\(.value)\\\\\\\"\\\" > /root/.env",
Hi  @uday202 you can try this syntax but make sure that i have used this in jenkins ssm remote deploy block you can adjust the slash according to your jenkins script . Get back to me if it works.
