### ISSUE TITLE
jq -r | join(" ") not working with windows batch file

### ISSUE THREAD

**Issue by vcloudguy** [jqlang/jq#1940]
**Describe the bug**

I am trying to run a jq query on a windows machine and it extracts values from output on a separate line

jq -r .Accounts[].Id
Output

204359864429
224271824096
282276286062
210394168456
090161402717
How do I run the jq query so that it combines the output on a single line separated by space

This is what I need-

204359864429 224271824096 282276286062 210394168456 090161402717

I tried adding 
jq -r '[.Accounts[].Id]|join(" ")'

<command> | jq -r '[.Accounts[].Id]|join(" ")' but it gave me a windows error
error: syntax error, unexpected $end (Windows cmd shell quoting issues?) at <top-level>, line 1: [.Accounts[].Id]|join( jq: 1 compile error

How do I run this command?

aws organizations list-accounts-for-parent --parent-id ou-6487-uu419l9c | jq -r '[.Accounts[].Id]|join(" ")'

Any help would be appreciated.

**Comment by pkoppstein** [comment]
This question has been asked and answered at https://stackoverflow.com/questions/56897802/jq-combine-output-on-a-single-line-separated-by-space
