### ISSUE TITLE
jq doesn't output multi-line filenames correctly

### ISSUE THREAD

**Issue by tobwen** [jqlang/jq#1941]
Sure, nobody likes multi-line filenames or should use them, but more and more standard tools get aware of the `\0` delimiter instead of linebreak `\n`. _jq_ is a very important tool for many users and it would be nice to have multi-line support in it. 

```
echo -n '[' > $'multi\nline.json'
$ jq *
jq: error: syntax error, unexpected IDENT, expecting $end (Unix shell quoting issues?) at <top-level>, line 2:
line.json
jq: 1 compile error
```

Expected output:
```
jq: error: syntax error, unexpected IDENT, expecting $end (Unix shell quoting issues?) at <top-level>, line 2:
"multi
line.json"
jq: 1 compile error
```
or even

```
jq: error: syntax error, unexpected IDENT, expecting $end (Unix shell quoting issues?) at <top-level>, line 2:
$'multi\nline.json'
jq: 1 compile error
```

**Comment by pkoppstein** [comment]
jq 1.5 and jq 1.6 at least seem to handle multi-line filenames properly, e.g.:

```
$ echo junk > $'multi\nline.json'
$ jq  . $'multi\nline.json'
parse error: Invalid numeric literal at line 2, column 0
$ jq -R input_filename $'multi\nline.json'
"multi\nline.json"
$ jq-1.5 -R input_filename $'multi\nline.json'
"multi\nline.json"
```
Perhaps the issues you've identified have more to do with the shell you're using than jq?

**Comment by tobwen** [comment]
> Perhaps the issues you've identified have more to do with the shell you're using than jq?

```
$ bash --version
GNU bash, version 4.3.30(1)-release (x86_64-pc-linux-gnu)

$ jq --version
jq-1.6-93-ge944fe8-dirty
```

Your snippet works, but _jq_ doesn't seem to have native globbing:
```
$ jq . "*"
$ jq . '*'
$ jq . \*

$ set -o noglob
$ jq . *
$ set +o noglob
```

Since a _for_ loop isn't an efficient solution, I have to stick to `xargs`, I think. But this is a breaker, since it stops on each error: https://github.com/stedolan/jq/issues/1942

**Comment by pkoppstein** [comment]
> Since a for loop isn't an efficient solution, I have to stick to xargs, I think.

The startup costs associated with jq are usually relatively minor, so unless the "*" expansion is overwhelmingly long, a for loop such as `for f in multi*.json ; do jq -R . "$f" ; done` should be fine. This also has the advantage of allowing the detection of a parsing error to be handled in the loop using the filename ($f).

**Comment by tobwen** [comment]
See https://github.com/stedolan/jq/issues/1942#issuecomment-508999835.

Sure, this is a valid answer, but having this run on a server with many not-so-quick cores, it's a sad situation.

**Comment by haguenau** [comment]
> `echo -n '[' > $'multi\nline.json'`
> `$ jq *`

Note that this treats the string `$'multi\nline.json'` not as an input file name to be opened and read, but as an inline jq _script_ (made of the two lines `multi` and `line.json`). I get the exact same error message if I input these same two lines as jq's input:

```
$ cat input.json
multi
line.json

$ cat input.json | jq .
parse error: Invalid numeric literal at line 2, column 0
```

Perhaps you meant to run `jq . $'multi\nline.json'` (note the dot) instead of `jq $'multi\nline.json'`? pkoppstein's examples indicate that jq appears to do the right thing when it needs to print filenames.
