### ISSUE TITLE
How to read a file line by line and then output all lines compounded with sth in jq?

### ISSUE THREAD

**Issue by fengnex** [jqlang/jq#1964]
If we need to read dynamic parameters from a static file and then generate one target (url) for each line of the file, how to use jq to implement it?
I mean, we use jq to read a file and then process its contents line by line; the output for each line is a distinct url generated with a line respectively.

Could anyone please provide one or several examples? Thank you very much!

**Comment by pkoppstein** [comment]
Please ask usage questions at stackoverflow.com with the `jq` tag.  Also, it would be helpful if you provided an example of what you are trying to achieve.  Alternatively, you could probably solve the problem yourself by consulting the [jq documentation](https://stedolan.github.io/jq/) (tutorial, manual, [FAQ](https://github.com/stedolan/jq/wiki/FAQ), etc).

**Comment by fengnex** [comment]
I have read jq documentation but still have no idea about that, will try using stackoverflow.com

**Comment by fengnex** [comment]
jq -R '{method: "POST", url: "http://:6060", body: {phoneNo: .}}' tels.txt
