### ISSUE TITLE
How to avoid print null in `jq` output?

### ISSUE THREAD

**Issue by pengyu** [jqlang/jq#1968]
`jq` prints `null` if nothing is found. Is there a way to print nothing if nothing is found? Thanks.

```
$ jq .b <<< '{"a": 1}'
null
```

**Comment by pkoppstein** [comment]
If by "nothing is found" you mean the object does not have the specified key, you would write something like this:

    $ jq 'if has("b") then .b else empty end' <<< '{"a": 1}'

You might like to write a wrapper, e.g.

    def dot($key): select(has($key))  | .[$key];

Sometimes the following suffices, though it has very different semantics:

    $ jq '.b // empty' <<< '{"a": 1}'

**Comment by auerswal** [comment]
To suppress `null` output lines I usually use `|select(.!=null)`:

    $ jq '.a | select(. != null)' <<< '{"a": 1}'
    1
    $ jq '.b | select(. != null)' <<< '{"a": 1}'
    $ 

To retrieve all values to a given key `k`, i.e., no output if the key is not found inside the JSON document, I use `..|.k?|select().!=null)`:

    $ jq '.. | .a? | select(. != null)' <<< '{"d": {"a": 1}}'
    1
    $ jq '.. | .b? | select(. != null)' <<< '{"d": {"a": 1}}'
    $
