### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by JimChrModder** [jqlang/jq#1981]
**Describe the bug**
I have git cloned the jq and followed the installation steps,but when I execute the make command I get these errors:
`✔ Successfully created virtual environment! 
Virtualenv location: /home/r4gn4r/.local/share/virtualenvs/docs-gUdHLmue
Traceback (most recent call last):
  File "build_manpage.py", line 4, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
make[2]: *** [Makefile:1854: jq.1] Error 1
make[2]: Leaving directory '/home/r4gn4r/Desktop/Tools/jq'
make[1]: *** [Makefile:1136: all-recursive] Error 1
make[1]: Leaving directory '/home/r4gn4r/Desktop/Tools/jq'
make: *** [Makefile:784: all] Error 2
`

**Expected behavior**
I ignored it,and continue the installation steps,but when I execute the command jq, terminal says that there is no jq command.

**Environment**
 - OS and Version: Parrot Linux
 - jq version 1.6

**Comment by richliu** [comment]
That's because no xml library in pipenv environment. 

Please try those command to install relative packages in pipenv 

pipenv shell 
$ pip3 install xml markdown pyyaml

**Comment by wtlangford** [comment]
Yes, sorry, this is a known issue right now. Can you tell me if the branch in #1995 builds without errors for you?

**Comment by itchyny** [comment]
This is likely resolved by the PR mentioned above, so closing.
