### ISSUE TITLE
how to handle broken json? the example needs better example

### ISSUE THREAD

**Issue by laptopmutia** [jqlang/jq#1983]
https://github.com/stedolan/jq/wiki/FAQ

I've read the questions about this from faq

"Is there a way to have jq keep going after it hits an error in the input file? Can jq handle broken JSON?"

but I still doesn't understand the things, I think it need better example and better explanations about how to keep going after we hits an error I don't understand how to use the catch/try from jq

for example I have these kind of errors on my json and I just want to make it one line/compact instead on pretty format
I don't mind if the broken json is removed though

```
[ 
   { 
      "color":"red",
      "text":"abcd",
      "number":"1234"
   },
   { 
      "color":"red",
      "text":"abcd",
      "number":"1234"
   },
   { 
      "color":"red",
      "text":"abcd",
      "number":"1234"
   },
   { 
      "color":"red",
      "textabcd",
      "number":"1234"
   },
   { 
      "color":"red",
      "text""abcd",
      "number":"1234"
   }
]

**Comment by Alanscut** [comment]
hi @laptopmutia 
 I tried to parse some clear illegal json, directly reported an error when parsing, and then the parsing terminated.but except for#1404.
