### ISSUE TITLE
Idea: possible to parse several json files and get a summary of the range of values in matching keys?

### ISSUE THREAD

**Issue by tansaku** [jqlang/jq#1988]
not sure if jq is the right tool for this, but I'm wondering that if I had a few files with matching JSON key content, e.g.

```json
{
  "key_one": "hello",
  "key_two": "sayonara"
}
```

```json
{
  "key_one": "konnichiwa",
  "key_two": "goodbye"
}
```

could I get a summary json that showed me all the values that had been used for each key across all the files, i.e.

```json
{
  "key_one": ["hello", "konnichiwa"],
  "key_two": ["goodbye", "sayonara"]
}
```

I can imagine programming this in a scripting language, but was wondering if jq could do it for me out of the box ...?

**Comment by simon-biber** [comment]
Yes, this can be done with jq. It was an interesting challenge. I use the -s parameter to read all the objects into an array, perform to_entries on each to break each entry into an object with its key and value, then flatten the results into a single array, group by keys, and produce a new object from each group, having the key being the first key, and the value being an array of all the values from the group, then add the results into a single object. 

This processes all files *.json in the current directory:
```
jq -s 'map(to_entries) | flatten | group_by(.key) | map({(first.key): map(.value)}) | add' *.json
```

**Comment by pkoppstein** [comment]
For reference, please note that a solution without using the -s option would be possible and likely preferable.
