### ISSUE TITLE
Remove nth element from array 

### ISSUE THREAD

**Issue by anilxoxo** [jqlang/jq#1998]
Suppose given an array [0, 1, 2, 3, 2, 4, 5, 6], I want to remove the element [2,5]
of the OUTPUT as [0,1,3,2,4,6]. or suggest removing any nth element in an array.
I tried but nothing happened.

**Comment by pkoppstein** [comment]
Compare and contrast:
```
def delete($n):
  index($n) as $ix
  | if $ix then .[:$ix] + .[$ix + 1:] else . end;
```

```deleteall($n):
  . - [$n];
```

In future, please ask usage questions at stackoverflow.com using the tag "jq": https://stackoverflow.com/questions/tagged/jq

**Comment by wtlangford** [comment]
Is the desire to delete particular values from the array or particular indexes?
```jq
# delete indexes
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] | del(.[2,5]) # [1,2,4,5,7,8,9,10]

# delete values
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] - [2, 5] # [1,3,4,6,7,8,9,10]
```

But as @pkoppstein said:
> In future, please ask usage questions at stackoverflow.com using the tag "jq": https://stackoverflow.com/questions/tagged/jq
