### ISSUE TITLE
jq shouldn't return 0 on parse error

### ISSUE THREAD

**Issue by oguz-ismail** [jqlang/jq#2016]
```
$ echo -1\" | jq
-1
jq: parse error: Unfinished string at EOF at line 2, column 0
$ echo $?
0
$
$ echo -1\" | jq -e
-1
jq: parse error: Unfinished string at EOF at line 2, column 0
$ echo $?
0
```
There is no way to detect a parsing error without reading+parsing stderr - which is not reliable at all-, and that makes it really hard to use jq in shell scripts.

---
Reproducible on both `jq-1.6-104-ge74eab8` and `jq-1.5+dfsg-2`.

**Comment by blieque** [comment]
I agree, but I can't reproduce this in `jq-1.6`. I get this, with `-e` and without. Is this a regression in a development build of 1.6?

```sh
$ echo \" | jq -e
parse error: Unfinished string at EOF at line 2, column 0
$ echo $?
4
```

**Comment by oguz-ismail** [comment]
> Is this a regression in a development build of 1.6?

I guess it is. jq-1.6 on Termux doesn't have this problem either
