### ISSUE TITLE
'Autoconf -fi' failed to execute in windows

### ISSUE THREAD

**Issue by xiaobai-pan** [jqlang/jq#2035]
**Describe the bug**
'Autoconf -fi' failed to execute in windows.

**To Reproduce**

$ autoreconf -fi
Can't locate Autom4te/ChannelDefs.pm in @INC (you may need to install the Autom4te::ChannelDefs module) (@INC contains: /mingw/share/autoconf /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /c/MinGW/bin/autoreconf-2.68 line 40.
BEGIN failed--compilation aborted at /c/MinGW/bin/autoreconf-2.68 line 40.

**Environment (please complete the following information):**
 - OS and Version:  Windows 7
 - jq version :1.6

**Comment by itchyny** [comment]
Looks like autoconf is missing. Closing because we have reproducible builds in GitHub Actions. Feel free to suggest any document improvements.
