### ISSUE TITLE
Documentation is not correct about behaviour of recurse builtin

### ISSUE THREAD

**Issue by dakusui** [jqlang/jq#2036]
**Describe the bug**
jq-1.6 documentation says,

>recurse(f) is identical to recurse(f; . != null) and can be used without concerns about recursion depth.

however, from jq-1.6, the filter for null was abolished, which is good and consistent, I believe.

**To Reproduce**

Just see the documentations and search for definition for the one parameter ```recurse``` function.

- https://stedolan.github.io/jq/manual/v1.6/#Builtinoperatorsandfunctions
- https://stedolan.github.io/jq/manual/#Builtinoperatorsandfunctions

**Expected behavior**

The description should be like following

> ```recurse(f)``` is identical to ```recurse(f; true)``` and can be used without concerns about recursion depth.

since ```recurse(f)``` is defined ```def recurse(f): def r: ., (f | r); r;``` in ```builtin.jq```

**Environment (please complete the following information):**
 - ALL
 - jq version : 1.6 or leter

**Additional context**
None

**Comment by dakusui** [comment]
Hmm,
Judging from the behavior of jq-1.6, I think I was wrong.
But strangely, the definition of the ```recurse/1``` function has changed not to handle ```null``` in a special way...
Maybe there's a logic that I don't know...

**Comment by dakusui** [comment]
I think I misunderstood the behavour of jq-1.6.
Please mark this ticket "invalid".

**Comment by nicowilliams** [comment]
I don't quite understand what the documentation says about this either...

**Comment by dakusui** [comment]
To me, the statement looks trying to justify the jq's behavior where ```null```s are ignored by ```recurse``` built-in and therefore also ignored by ```paths/1``` builtin, which internally uses it...

From the commit you made 3 years ago at this line, 

https://github.com/stedolan/jq/blame/master/src/builtin.jq#L18

I thought they (and you) intended to abolish such an inconsistent behavior and treat ```null``s as others are, but on my local, it's showing a following behavior and puzzling me.

```
$ jq --version
jq-1.6
$ echo '{"k":null}' | jq -r -c 'paths(scalars)'
$ echo '{"k":null}' | jq -r -c 'paths'
["k"]
$
```

**Comment by dakusui** [comment]
Re-opening this issue since something in documentation should be improved apparently.

**Comment by TWiStErRob** [comment]
Bump, this is really confusing on an otherwise already advanced topic.

Ref https://unix.stackexchange.com/a/654730/23398
