### ISSUE TITLE
add command inside if in jq

### ISSUE THREAD

**Issue by gianfabiopezzolla** [jqlang/jq#2053]
Hi there,

I have this following script:

```
sqtoken="myToken"
project_name=proj_name
sonar_search=`curl -u $sqtoken: http://my.sonar.it/api/projects/search?projects=$project_name`

echo $sonar_search | jq 'if (.components == []) then empty else .components end'
```

I need to add a _curl -X POST http://_ inside the first if in jq,
How can I do that?

Thanks a lot

**Comment by leonid-s-usov** [comment]
@nicowilliams this is your moment :)
@sagolab please see pr #1843 , it will add the possibility of running external process from within JQ

**Comment by SAGOlab** [comment]
@leonid-s-usov  ok thanks a lot. So is not possible yet..

**Comment by nicowilliams** [comment]
Yeah, #1843 is the thing for this.  Soon.

**Comment by emanuele6** [comment]
I don't understand the question.

Anyway you can easily run commands piping to `sh`.

Here is an example: (I don't think it's correct since `.components` would be an array, but I don't know how else to interpret the question.)

```sh
curl -fGu "$sqtoken:" --data-raw "projects=$project_name" \
    http://my.sonar.it/api/projects/search |
jq -r '
    .components |
    select(. != []) |
    @sh "curl -gfX POST http://\(.components)"' |
sh
```

Closing...
