### ISSUE TITLE
jq: 1 compile error

### ISSUE THREAD

**Issue by KingArtus** [jqlang/jq#2054]
i use JQ under ubuntu, and it actually works fine, but when trying to transform a complex json file i get problems, is it possible that it is not possible to transform complex files?

[input.txt](https://github.com/stedolan/jq/files/4138918/input.txt)
[output.txt](https://github.com/stedolan/jq/files/4138919/output.txt)

i olwas get jq: 1 compile error

**Comment by leonid-s-usov** [comment]
Hi,
please provide your jq filter and the command line you use to run it

**Comment by Alanscut** [comment]
hi @KingArtus 
Can you provide more information?  such as: your expected result, jq version

**Comment by pkoppstein** [comment]
@KingArtus - input.txt is valid JSON and is parsed successfully as such.  output.txt, despite appearances, is not valid JSON and jq produces a decent error message.
