### ISSUE TITLE
Seeking funding? (CZI EOSS grant)

### ISSUE THREAD

**Issue by brainwane** [jqlang/jq#2055]
jq is clearly a great and popular project! I was wondering whether you're seeking funding to make more frequent releases, improve docs, etc.? 

I bet a bunch of researchers use jq, so I wanted to let you know about [the Chan Zuckerberg Initiative's Essential Open Source Support for Science](https://chanzuckerberg.com/eoss/), which funds open source projects that are in some way foundationally useful to biological and medical researchers. They award [between $50,000 and $250,000, for 1-year projects](https://chanzuckerberg.com/rfa/essential-open-source-software-for-science/). (In the award I just helped pip apply for, they awarded $200,000.)

There are [various other grants available for popular open source projects](https://www.harihareswara.net/sumana/2019/12/04/0) in case that's helpful, but I especially wanted you to know about EOSS!

**Comment by nicowilliams** [comment]
Core contributors have day jobs and need no additional funding -- additional non-work/life/sleep hours, yes, but the only way to contribute those is to contribute new contributors!  :)

Of course, we'll accept quality contributions, and we do not care how those are funded, provided the contributors are allowed to make said contributions.  So if anyone who would like to contribute can get funding via the above-linked initiative, have at it.  :)

**Comment by emanuele6** [comment]
Closing
