### ISSUE TITLE
Add flag to edit file in-place (like sed's -i / --in-place)

### ISSUE THREAD

**Issue by jntesteves** [jqlang/jq#2066]
# Add flag to edit file in-place (like sed's -i / --in-place)

A common pattern with automated command-line text editors is to edit configuration files in-place. For example, with jq:
```
cp ~/.docker/config.json ~/.docker/config.json~ && cat ~/.docker/config.json~ | jq --tab --arg proxy 'http://proxy.example.com:8080' '.proxies = {default:{httpProxy:$proxy,httpsProxy:$proxy}}' > ~/.docker/config.json
```

This copies docker's configuration file `~/.docker/config.json`, then streams the copy through `jq` and overwrites the original file. That's quite a long line because of explicitly copying the file and then explicitly overwriting. Other text tools, like `sed -i` and `perl -i` offer a flag to automate this process. From sed's help:
```
-i[SUFFIX]
--in-place[=SUFFIX]
This option specifies that files are to be edited in-place. GNU sed does this by creating a temporary file and sending output to this file rather than to the standard output.1.

This option implies -s.

When the end of the file is reached, the temporary file is renamed to the output file’s original name. The extension, if supplied, is used to modify the name of the old file before renaming the temporary file, thereby making a backup copy2).

This rule is followed: if the extension doesn’t contain a *, then it is appended to the end of the current filename as a suffix; if the extension does contain one or more * characters, then each asterisk is replaced with the current filename. This allows you to add a prefix to the backup file, instead of (or in addition to) a suffix, or even to place backup copies of the original files into another directory (provided the directory already exists).

If no extension is supplied, the original file is overwritten without making a backup.
```

The same jq script above, with this flag, would look like:
```
jq --in-place=~ --tab --arg proxy 'http://proxy.example.com:8080' '.proxies = {default:{httpProxy:$proxy,httpsProxy:$proxy}}' ~/.docker/config.json
```

**Comment by wtlangford** [comment]
Once upon a time, we had a flag that did this, but it caused problems. Unlike sed, jq programs can operate on multiple values from the input at once, and those values could have come from separate files. In that case, we don't know where to write output values.

Instead of trying to solve this problem ourselves, we generally recommend using [sponge](https://linux.die.net/man/1/sponge).

With sponge, your script would become:
```bash
jq --tab --arg proxy 'http://proxy.example.com:8080' '.proxies = {default:{httpProxy:$proxy,httpsProxy:$proxy}}' ~/.docker/config.json | sponge ~/.docker/config.json
```

**Comment by itchyny** [comment]
Dup of #105, so closing.
