### ISSUE TITLE
to_entries behaviour in Windows bash

### ISSUE THREAD

**Issue by goffinf** [jqlang/jq#2083]
jq version:  1.6  (same behaviour for 1.5)
platform: Windows 10 Pro
environment: mysys2 bash

Description:

Input JSON file: **numbers.json**

`{"one": {"value": "1"},"two": {"value": "2"},"three": {"value": "3"}}`

Using this query returns the keys one, two and three:

`jq --raw-output 'to_entries[] | .key'`

From jqplay.org (confirmed locally):

```
one
two
three
```
Putting the above into a bash script: **jq-in-test.sh**
```

#!/bin/bash

CONFIG_FILE=numbers.json;
KEYS=$(jq -r 'to_entries[] | .key' $CONFIG_FILE);

echo "KEYS = $KEYS";

for IMAGE in $KEYS; do
    echo "IMAGE = $IMAGE";
done;
```
Run on Linux **and** Windows bash results in the expected output:

```
$ ./jq-in-test.sh
KEYS = one
two
three
IMAGE = one
IMAGE = two
IMAGE = three
```
However, if I now introduce a test to try and find one of the keys (say 'two') the behaviour between Linux and Windows bash is different (Windows does NOT work):

Updated script: 

```
#!/bin/bash

CONFIG_FILE=numbers.json;
TARGET_IMAGE=two;

KEYS=$(jq -r 'to_entries[] | .key' $CONFIG_FILE);

echo "KEYS = $KEYS";

for IMAGE in $KEYS; do
  echo "IMAGE = $IMAGE";
  echo "TARGET_IMAGE = $TARGET_IMAGE"
  if [ "$IMAGE" == "$TARGET_IMAGE" ] || [ -z $TARGET_IMAGE ]; then
      echo "MATCH FOUND for $IMAGE ...";
  else
     echo "NO MATCH FOUND for $IMAGE ...";
  fi;

done;
```

On LINUX this produces the correct result ('two' is matched):

```
$ ./jq-in-test.sh
KEYS = one
two
three
IMAGE = one
TARGET_IMAGE = two
NO MATCH FOUND for one ...
IMAGE = two
TARGET_IMAGE = two
MATCH FOUND for two ...
IMAGE = three
TARGET_IMAGE = two
NO MATCH FOUND for three ...
```
On Windows bash not only is the match not found but there appears to be something odd about the keys returned by jq (note the output which should say NO MATCH FOUND ...  shows ...ATCH FOUND  except for the last key):

```
$ ./jq-in-test.sh
KEYS = one
two
three
IMAGE = one
TARGET_IMAGE = two
 ...ATCH FOUND for one
IMAGE = two
TARGET_IMAGE = two
 ...ATCH FOUND for two
IMAGE = three
TARGET_IMAGE = two
NO MATCH FOUND for three ...
```
If I choose to try and match the last key ('three') the match is found but there's still something funny going on with the KEYS:

```
#!/bin/bash

CONFIG_FILE=numbers.json;
TARGET_IMAGE=three;

KEYS=$(jq -r 'to_entries[] | .key' $CONFIG_FILE);

echo "KEYS = $KEYS";

for IMAGE in $KEYS; do
  echo "IMAGE = $IMAGE";
  echo "TARGET_IMAGE = $TARGET_IMAGE"
  if [ "$IMAGE" == "$TARGET_IMAGE" ] || [ -z $TARGET_IMAGE ]; then
      echo "MATCH FOUND for $IMAGE ...";
  else
     echo "NO MATCH FOUND for $IMAGE ...";
  fi;

done;
```

Output: (on Windows - works fine on Linux):

```
$ ./jq-in-test.sh
KEYS = one
two
three
IMAGE = one
TARGET_IMAGE = three
 ...ATCH FOUND for one
IMAGE = two
TARGET_IMAGE = three
 ...ATCH FOUND for two
IMAGE = three
TARGET_IMAGE = three
MATCH FOUND for three ...
```
I'm not sure whats going on here, perhaps its line endings or something else, but its certainly odd. The only workaround I have at the moment that works on both Linux and Windows is to use -j to output the keys as a single string, and add a delimiter which I can then split to create a bash array and then iterate that (but it would be MUCH cleaner to use the keys gathered by jq as/is). I need to run a script like this on both Windows and Linux.

Heres the not so elegant work-around, but hopefully you will either be able to tell me whats going on here and how to fix it, or maybe provide a better jq based work around

**arr-jq-test.sh**

```
#!/bin/bash

set -e

CONFIG_FILE=numbers.json;
TARGET_IMAGE=two;

KEYS=$(jq -j 'to_entries[] | .key + "#"' $CONFIG_FILE);

echo "KEYS = $KEYS";

IFS='#' read -ra keys_array <<< "$KEYS"

for IMAGE in ${keys_array[*]}; do
    echo "IMAGE = $IMAGE";

  echo "TARGET_IMAGE = $TARGET_IMAGE"
  if [ "$IMAGE" == "$TARGET_IMAGE" ] || [ -z $TARGET_IMAGE ]; then
      echo "MATCH FOUND for $IMAGE ...";
      #exit 0;
  else
     echo "NO MATCH FOUND for $IMAGE ...";
  fi;

done;
```

On WIndows and Linux bash this produces the correct output:

```
$ ./arr-jq-test.sh
KEYS = one#two#three#
IMAGE = one
TARGET_IMAGE = two
NO MATCH FOUND for one ...
IMAGE = two
TARGET_IMAGE = two
MATCH FOUND for two ...
IMAGE = three
TARGET_IMAGE = two
NO MATCH FOUND for three ..
```

Kind Regards

Fraser.

**Comment by goffinf** [comment]
A bit more info.  I removed the '...' from the echo statements and that got rid of the messed up test at the start of the output lines.

The match still doesn't work, but my colleague pointed me this issue about mysys2 line ending compatibility : https://github.com/stedolan/jq/issues/1870

**Comment by goffinf** [comment]
Its definitely line endings ... if in bash I strip them from the IMAGE var everything works as expected (can even add the ...'s back in .. and even use the Windows jq.exe rather than the pacman jq package.

I'm going to do a bit more testing and if nothing else bad happens I'll close this ticket.

Still open to other suggestions though :-)

**Comment by pjeby** [comment]
You might try setting `IFS=$'\n\r\t '` in your script, which should tell bash to treat carriage returns as whitespace when doing word splitting.

There's also a safer way to map jq arrays to bash: use the `@sh` format specifier in jq to output values that can be used in an eval.  For example:

```shell
IFS=$'\n\t\r ' eval "KEYS=($(jq -r 'to_entries[] |  .key | @sh' "$CONFIG_FILE"))"

for IMAGE in "${KEYS[@]}"; do
...
done
```

The `@sh` wraps each key in quotes with any necessary escaping, so the keys can be iterated over even if they contain spaces, newlines, or anything else.  The `eval` is then safe because it's only reading quoted strings.  (The `IFS` is still needed, though, because the excess carriage returns will still end up added to each string, otherwise.)
