### ISSUE TITLE
Not contains in array works strange

### ISSUE THREAD

**Issue by tveritinova** [jqlang/jq#2086]
**Describe the bug**
I'm trying to get entries which has field that not contains specific value. But after adding "not", something goes wrong and it outputs all values.

**To Reproduce**
```
echo '[{"a":[123]}, {"a":[]}]' | jq '.[] | .a += [999] | select(.a[] | contains(123) | not)'
{
  "a": [
    123,
    999
  ]
}
{
  "a": [
    999
  ]
}
```

```
echo '[{"a":[123]}, {"a":[]}]' | jq '.[] | .a += [999] | select(.a[] | contains(123))'
{
  "a": [
    123,
    999
  ]
}
```

**Expected behavior**
I expect that for the first command above I will get only the entire `{ "a": [999]}`

**Environment (please complete the following information):**
 - macOS Mojave 10.14.6 
 - jq-1.6

**Additional context**

**Comment by pkoppstein** [comment]
This is a usage question.  We ask that such questions be asked on stackoverflow.com with the jq tag:  https://stackoverflow.com/questions/tagged/jq

Please adhere to the stackoverflow.com question-asking guidelines: http://stackoverflow.com/help/mcve

Thank you.

**Comment by itchyny** [comment]
This issue is an outdated question so closing. I think the correct query is `.[] | .a += [999] | select(.a | contains([123]) | not)`. Using multi-value query in `select` argument will yield unexpected outputs so I don't recommend to do that.
