### ISSUE TITLE
tests fail when rake has other version than 10.4.2 

### ISSUE THREAD

**Issue by dima4p** [jqlang/jq#2087]
**Describe the bug**
tests fail when rake has other version than 10.4.2 

**To Reproduce**
run `make check` while rake has different verions (I had 12.3.2)

**Expected behavior**
all tests should succeed 

**Environment (please complete the following information):**
 - OS and Version:
$ cat /etc/os-release 
NAME=Slackware
VERSION="14.2"
ID=slackware
VERSION_ID=14.2
PRETTY_NAME="Slackware 14.2"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
HOME_URL="http://slackware.com/"
SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
- jq version 1.6

**Additional context**
`gem i rake -v=10.4.2` helped

**Comment by itchyny** [comment]
We now have no dependency on Ruby so should never happen again.
