### ISSUE TITLE
jq command not working on 1.3 version

### ISSUE THREAD

**Issue by sathe06** [jqlang/jq#2114]
cat sk_008.txt | jq -Rn "{Result:[inputs]}"
jq: Unknown option -Rn
Use jq --help for help with command-line options,
or see the jq documentation at http://stedolan.github.com/jq

jq --version
jq version 1.3

**Comment by sathe06** [comment]
I dont know whether its right place to ask question, can someone please guide me where i made mistake

**Comment by sathe06** [comment]
above command was working on 1.6 version

**Comment by itchyny** [comment]
This was implemented at f9349becab9f4f79559976c21e4197b6745d77e5 (see #346), which was after 1.4. There's no backport in jq so please use the latest release.
