### ISSUE TITLE
Potentially contradictory docs?

### ISSUE THREAD

**Issue by max-sixty** [jqlang/jq#2124]
Am I missing something very obvious, or are these two commands the same?

<img width="709" alt="image" src="https://user-images.githubusercontent.com/5635139/81763098-4192fc80-9483-11ea-9240-6ad8bc6242cf.png">

From https://stedolan.github.io/jq/manual/#if-then-else

**Comment by itchyny** [comment]
Thanks for report. It looks like a mistake at 8a02b2c9c191015d8f1e5e27404e2682d76b6a91 (#1825). BTW, comparison against an empty string should profit in performance than using the length function.

**Comment by itchyny** [comment]
The document was fixed at #2271 (cc4efc49e1eedb98289347bf264c50c5c8656e7c) in May 2021, so closing the issue.
