### ISSUE TITLE
jq How to convert UTC time to Beijing time?

### ISSUE THREAD

**Issue by zhouhuihua526** [jqlang/jq#2128]
jq How to convert UTC time to Beijing time?
For example: 2020-05-14T09: 44: 19Z -------> 2020-05-14T17: 44: 19Z

**Comment by itchyny** [comment]
```sh
 % echo '2020-05-14T09:44:19Z' | TZ=Asia/Shanghai jq -Rr 'fromdate | strflocaltime("%Y-%m-%dT%H:%M:%SCST")'
2020-05-14T17:44:19CST
```

**Comment by pkoppstein** [comment]
Even better, use %Z:
```
echo '2020-05-14T09:44:19Z' | TZ=Asia/Shanghai jq -Rr 'fromdate | strflocaltime("%Y-%m-%dT%H:%M:%S%Z")'
2020-05-14T17:44:19CST
```

**Comment by zhouhuihua526** [comment]
用jq play 
Filter【. | TZ=Asia/Shanghai】
JSON【"2020-05-14T09:44:19Z"】
Result【jq: error: TZ/0 is not defined at <top-level>, line 1:
             . | TZ=Asia/Shanghai    
             jq: error: Asia/0 is not defined at <top-level>, line 1:
             . | TZ=Asia/Shanghai       
             jq: error: Shanghai/0 is not defined at <top-level>, line 1:
            . | TZ=Asia/Shanghai            
             jq: 3 compile errors
            exit status 3】

**Comment by zhouhuihua526** [comment]
Use jq play to execute TZ = Asia / Shanghai and report an error

**Comment by pkoppstein** [comment]
> 用jq play ...

One of the limitations of jqplay is that it does not allow one to specify environment variables.  

If you want to use jqplay or a system in which environment variables cannot be set, you'd have to resort to manual adjustments.

**Comment by zhouhuihua526** [comment]
> > 用jq play ...
> 
> One of the limitations of jqplay is that it does not allow one to specify environment variables.
> 
> If you want to use jqplay or a system in which environment variables cannot be set, you'd have to resort to manual adjustments.

How can I adjust it manually?

**Comment by pkoppstein** [comment]
> How can I adjust it manually? 

For details, see the section on ["Dates"](https://stedolan.github.io/jq/manual/#Builtinoperatorsandfunctions) in the jq manual, and documentation on the libc data/time functions.

For future reference, please ask jq usage questions at stackoverflow.com, using the jq tag: https://stackoverflow.com/questions/tagged/jq

**Comment by zhouhuihua526** [comment]
> > How can I adjust it manually?
> 
> For details, see the section on ["Dates"](https://stedolan.github.io/jq/manual/#Builtinoperatorsandfunctions) in the jq manual, and documentation on the libc data/time functions.
> 
> For future reference, please ask jq usage questions at stackoverflow.com, using the jq tag: https://stackoverflow.com/questions/tagged/jq

There is no way to convert UTC time to Beijing time in the jq manual about "date". Is there a link to the documentation about libc data / time functions?

**Comment by itchyny** [comment]
The document says `The strflocaltime does the same, but using the local timezone setting` so specify the timezone environment variable (`TZ`) and use `strflocaltime` function. That's the only way to convert timezone in jq. If you want to specify environment variables in jqplay, send a feature request to the maintainer of jqplay.

**Comment by pkoppstein** [comment]
In jq, you can easily convert the string representation of the time to seconds since the Epoch, make the 8-hour adjustment, and convert back to the CST string.
