### ISSUE TITLE
jq How to format json data after getting key-value pairs of multiple attributes from list?

### ISSUE THREAD

**Issue by zhouhuihua526** [jqlang/jq#2129]
jq How to format json data after getting key-value pairs of multiple attributes from list?
E.g:
{"Start": "true",
"end": [{"name": "yml", "good": false, "user": "z", "sex": {"re": "zz"}, {"name": "XML" , "good": true, "user": "w", "sex": {"re": "ww"}}, {"name": "json", "good": false, "user": " s "," sex ": {" re ":" ss "}}]}
Expected results:
[
  {"name": "yml", "user": "z", "re": "zz"},
  {"name": "XML", "user": "w", "re": "ww"},
  {"name": "json", "user": "s", "re": "ss"}
]
Instead of
[{"name": "yml", "user": "z", "re": "zz"}, {"name": "XML", "user": "w", "re": "ww "}, {" name ":" json "," user ":" s "," re ":" ss "}]

**Comment by itchyny** [comment]
Ambiguous question with broken example JSON, but I propose a solution and closing the issue. Use `walk` and `with_entries` to trim both keys and values.
```bash
 $ jq '[.end[] | walk(with_entries(.[] |= (ltrimstr(" ") | rtrimstr(" ")))? // .) | {name, user, re: .sex.re}]' <<'EOF'
{"Start": "true","end": [
  {"name": "yml", "good": false, "user": "z", "sex": {"re": "zz"}},
  {"name": "XML" , "good": true, "user": "w", "sex": {"re": "ww"}},
  {"name": "json", "good": false, "user": " s "," sex ": {" re ":" ss "}}]}
EOF
```
```json
[
  {
    "name": "yml",
    "user": "z",
    "re": "zz"
  },
  {
    "name": "XML",
    "user": "w",
    "re": "ww"
  },
  {
    "name": "json",
    "user": "s",
    "re": "ss"
  }
]
```
