### ISSUE TITLE
Assertion `jv_get_kind(objects) == JV_KIND_ARRAY' failed

### ISSUE THREAD

**Issue by andrewisplinghoff** [jqlang/jq#2144]
**Describe the bug**
Assertion error ```jq: jv_aux.c:579: jv_sort: Assertion `jv_get_kind(objects) == JV_KIND_ARRAY' failed.``` occurs when trying to remove empty `schema` elements from a Swagger json. The syntax might be wrong, I've just been experimenting. I do not think that showing an assertion to the user is the expected behaviour no matter if valid input was provided or not.

**To Reproduce**
Extract swagger_formatted.json from [swagger_formatted.zip].(https://github.com/stedolan/jq/files/4804195/swagger_formatted.zip)

```
$ jq "delpaths(.paths[] | select(.post != null) | .post.responses[] | select(.schema != null and .schema == {}) | .schema)" swagger_formatted.json
jq: jv_aux.c:579: jv_sort: Assertion `jv_get_kind(objects) == JV_KIND_ARRAY' failed.
Aborted
```

**Expected behavior**
To my understanding, failed assertions should never be shown to the user. Instead a helpful error message should be provided if an invalid jq script was provided by the user.

**Environment (please complete the following information):**
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.12 (stretch)
Release:        9.12
Codename:       stretch
```
```
$ jq --version
jq-1.5-1-a5b5cbe
```

**Comment by itchyny** [comment]
Your assertion error is not reproducible with **jq 1.6** so be sure to update the version. Also your query seems incorrect, `delpaths([path(.path[] ... .schema)])` is correct.

**Comment by andrewisplinghoff** [comment]
@itchyny Thanks for looking into this so quickly. If the behaviour with with the current version is fine please just close ticket, sorry to bother you.
