### ISSUE TITLE
Issue 501 was closed by mistake

### ISSUE THREAD

**Issue by afontenot** [jqlang/jq#2161]
I'm reporting that https://github.com/stedolan/jq/issues/501 was closed by mistake. @wtlangford appears to have accidentally closed it instead of a different issue; see this comment here, which appears to have been an intended reply to some other thread: https://github.com/stedolan/jq/issues/501#issuecomment-396596232

Just flagging this for attention since people in that issue have tried to get it reopened for several months to no avail. Feel free to close this once the other issue is reopened (or the reason for closing it is made apparent).

**Comment by itchyny** [comment]
Reopening #501, so closing this issue.
