### ISSUE TITLE
foreach: doc recommendation

### ISSUE THREAD

**Issue by gabrielsroka** [jqlang/jq#2169]
I found the `foreach` example a little hard to understand. Can we have something more Hello World-ish?, eg
https://jqplay.org/s/4GNwRCpQLX
```
jq 'foreach .[] as $item (0; . + 1; "\(.) - \($item)")'

input: ["apple", "banana", "cherry"]

output:
"1 - apple"
"2 - banana"
"3 - cherry"
```

Also, i'm curious why it starts at 1, not 0 -- this seems different than a foreach loop, eg, in JavaScript or Python. Would you be able to explain (here and/or in the docs)? Is this a bug?

(speaking of JavaScript, the "s" is not capitalized in the docs)

Thanks!

**Comment by asharpe** [comment]
I too thought the example in the docs required a lot of effort to grok, and even simply changing the inputs to more clearly show the relationship to the outputs is helpful!  Eg. using the example script in the doc

```
input: [1,2,"c",4,null,"a","b",3,null]
output: [[1,2,"c",4],["a","b",3]]
```

Regarding the "starts at 1" question, I think you've just misunderstood the flow of the foreach syntax.  If you read your example as per the flow, you'd see that the first `UPDATE` expression runs immediately after `INIT`, and you have `1` at that point already!

It'd also be good to be able to detect end of input somehow.

**Comment by wader** [comment]
Yes simpler examples is probably good and maybe show all foreach/reduce variants? https://jqplay.org/s/Ew6UEumvc_i
```jq
[foreach empty as $i (0; .+$i)],
[foreach (1,2,3) as $i (0; .+$i)],
[foreach (1,2,3) as $i (0; .+$i; .+10)],
reduce empty as $i (0; .+$i),
reduce (1,2,3) as $i (0; .+$i)
```
Outputs
```
[]
[1,3,6]
[11,13,16]
0
6

```
