### ISSUE TITLE
Overriding a builtin: a bug or a feature?

### ISSUE THREAD

**Issue by leonid-s-usov** [jqlang/jq#2170]
**Describe the bug**
it's possible to override builtin functions by defining filters with a matching name. It's even possible to change the binary operations this way

**To Reproduce**
```
 » ./jq -n 'def _plus($a;$b): $a-$b; def two: 2; two+1'                    
1
```

**Expected behavior**
I'm not sure, but maybe some builtins, like those that implement basic operations at least, should take precedence?

**Comment by pkoppstein** [comment]
@itchyny - please remove the bug tag. This is most definitely a feature, and an important one, e.g. it allows builtins to be added without breaking existing user code.  A case can of course be made for adding a flag that would change the behavior, e.g. to raise a warning or error, but @stedolan and @nicowilliams have expressed in varying degrees a fairly or very strong disinclination for new command-line options, so it would in my view be reasonable to close this issue.

**Comment by nicowilliams** [comment]
Maybe instead of a flag a module option, so that the desire for non-overridden builtins can be expressed in jq.  Or, even better, we really ought to have builtin, non-overridable _modules_ named `jq::v1_6`, `jq::v1_7`, etc., which would also give us the great benefit of being able to backwards-incompatible changes in builtins!

**Comment by nicowilliams** [comment]
I do think that being able to override builtins is a feature in most cases, but it is also a footgun.

**Comment by itchyny** [comment]
Isn't it a bug that operators are compiled to user's defined filters?

**Comment by nicowilliams** [comment]
> Isn't it a bug that operators are compiled to user's defined filters?

Or it's a feature.  We shouldn't have made those polymorphic -they should have been for numbers only- and then one could override them with polymorphic ones when one wants polymorphism.

**Comment by itchyny** [comment]
Thanks for explanation. We can close this as a feature.

**Comment by pkoppstein** [comment]
@itchyny, @nicowilliams - I'm puzzled.  I can reproduce the result shown in the original post in this thread, but the following produces `[3] 3`, showing that 1+2 is still 3.  What am I missing?
```
def myplus($a;$b): _plus($a;$b);

def _plus($a;$b): [ myplus($a;$b) ];

_plus(1;2), (1+2)
```

**Comment by nicowilliams** [comment]
@pkoppstein you're missing constant-folding, which happens at compile time, and which assumes that `_plus` and others are not overridden.

```
jq -cn --argjson n 5 '
def myplus($a;$b): _plus($a;$b);

def _plus($a;$b): [ myplus($a;$b) ];

_plus(1;$n), (1+$n)'
[6]
[6]
```

**Comment by nicowilliams** [comment]
Constant-folding does make it a footgun to override arithmetic built-ins _in particular_.

**Comment by pkoppstein** [comment]
@nicowilliams - Thanks.  Shouldn't this be documented in the manual?

**Comment by nicowilliams** [comment]
> @nicowilliams - Thanks. Shouldn't this be documented in the manual?

I don't see why.  Constant folding is an optimization.  We don't document that `+` becomes a function call or what the name of the builtin function is that it calls (`_plus`).  We could -but don't yet have to- document that one can shadow builtins.  Leaving undocumented things undocumented that don't yet need documenting is a way to let us have more freedom in making changes later.
