### ISSUE TITLE
@tsv format string escaping

### ISSUE THREAD

**Issue by ghost** [jqlang/jq#2184]
**Describe the bug**
I think there's a problem with the output of single quote (apostrophe) from `... | [@sh] | @tsv `. It is escaped as if the entire output string were in double quotes.

**To Reproduce**

```
#!/bin/sh
{ json=$(cat); } <<'HERE'
{"ls":["O'Neill","d'oh"]}
HERE
printf '%s\n' "${json}" | jq -r '.[] | [@sh] | @tsv'
```
Output:
```
'O'\\''Neill' 'd'\\''oh'
```
**Expected behavior**

`printf '%s ' 'O'\''Neill' 'd'\''oh'`
would output the expected
`O'Neill d'oh `

**Environment:**
 - Ubuntu 20.04, dash 0.5.10, jq 1.6

**Comment by ajasmin** [comment]
@tsv is documented as escaping backslashes


    # jq -rn '["\\"] | @tsv'
    \\


>     @tsv:
> 
> The input must be an array, and it is rendered as TSV (tab-separated values). Each input array will be printed as a single line. Fields are separated by a single tab (ascii 0x09). Input characters line-feed (ascii 0x0a), carriage-return (ascii 0x0d), tab (ascii 0x09) and backslash (ascii 0x5c) will be output as escape sequences \n, \r, \t, \\ respectively.


Since jq's @tsv format has \n, \r, \t escape sequences for tabs and newlines, the backslash becomes special and you have to escape it as well.

Replace `@tsv` by `join("\t")` and you should get the expected result.

**Comment by pkoppstein** [comment]
Closing this, as `@tsv` is intended to work as documented, for good reason.
