### ISSUE TITLE
jq does not pretty print when output is not a terminal

### ISSUE THREAD

**Issue by giannis-tsakiris-elsevier** [jqlang/jq#2185]
if I do :

echo file.json | jq .

I get a formatted (pretty printed) version of the json contained in the file.

But if I do:

VAR=&#96;echo file.json | jq .&#96;
echo $VAR

then the output stored in $VAR is not pretty-printed.

**Comment by ajasmin** [comment]
This looks like a shell quoting issue. Try `echo -E "$VAR"`

**Comment by giannis-tsakiris-elsevier** [comment]
> This looks like a shell quoting issue. Try `echo -E "$VAR"`

Thank you.
