### ISSUE TITLE
JQ version 1.6 utility is not compatible with Windows 10

### ISSUE THREAD

**Issue by pauelm** [jqlang/jq#2204]
Steps:
1. Go to https://stedolan.github.io/jq/
2. Click "Download jq 1.6" dropdown -> select "Windows (64-bit)"
3. Copy the executable to desired application folder.
4. Rename the file to "jq.exe" (IF you plan on using it with Bash on Windows).

5. Open a DOS console -> navigate to path of jq.exe
6. Type in "jq" -> ENTER  (or double-click it).

Expected Results:
The console should output command line options for JQ, (since no parameters were given).

Actual Results:
The following error message is thrown:
![image](https://user-images.githubusercontent.com/56095344/98072533-1a5a2e00-1e1b-11eb-916f-dbcacc718e98.png)

NOTE: 
When going all the way back to 32-bit flavor of JQ version 1.3, the error message above is NOT thrown.

**Comment by kkm000** [comment]
Is it possible that the downloaded file got corrupted? I downloaded the same version just now, and it worked for me. From Git bash:
```
$ ./jq-win64 <<< '{}'
{}
$ md5sum.exe jq-win64.exe
af2b0264f264dde1fe705ca243886fb2 *jq-win64.exe
$ cmd <<<ver
Microsoft Windows [Version 10.0.19041.610]
. . .
```
