### ISSUE TITLE
How to remove double quotes only for specific fields ?

### ISSUE THREAD

**Issue by toonetcreation** [jqlang/jq#2225]
Hi,

I have done this with JQ and works fine : 

`.[] | [.id,.customer_id,.customer_identity,.title] | @csv`

I get this result : 

`5464015,1088020,"My title","My description"`

What I need is to remove double quotes to get this result :

`5464015,1088020,My title,My description`

How can I do that?

Thanks
L.

**Comment by ajasmin** [comment]
Instead of `@csv` you could use `join("\,")`. You'll have to think about how to escape `,` if that's a concern.

**Comment by toonetcreation** [comment]
like this ?

`jq -rn  [.id,.customer_id,".customer_identity",".title"] | join(",")'`
