### ISSUE TITLE
Feature Request: a THIS operator for structure indices

### ISSUE THREAD

**Issue by sf-greensill** [jqlang/jq#2228]
Hi there.

First a big thank you for an invaluable tool!

Imagine if you will, you get some data like:
`{
    "Maps": [
        {
            "Value": "1", 
            "Key": "A"
        }, 
        {
            "Value": "2", 
            "Key": "B"
        }, 
        {
            "Value": "3", 
            "Key": "C"
        }
    ]
}`

Do something like:  `echo $sampled | jq -s '.[].Maps|{(.[0].Key): .[0].Value, (.[1].Key): .[1].Value, (.[2].Key): .[2].Value}'`

Your desired output in this case is:

`{
    "A": "1",
    "B": "2",
    "C": "3",
}`

Instead, I suggest an operator like `THIS`:  `echo $sampled | jq -s '.[].Maps|{(.[!].Key): .[!].Value}'`

**[EDIT]**
_An offset would work similarly:_  `echo $sampled | jq -s '.[].Maps|{(.[!+1].Key): .[!].Value}'`

`{
    "B": "1",
    "C": "2",
    "A": "3",
}`

_This is based on the modification of the indices not the data elements._
**[/EDIT]**

When we look at: `echo $sampled | jq -s '.[].Maps|{(.[].Key): .[].Value}'` the output is as expected:
`{
    "A": "1",
    "A": "2",
    "A": "3",
    "B": "1",
    "B": "2",
    "B": "3",
    "C": "1",
    "C": "2",
    "C": "3",
}`

This would again be the same expected result for:  `echo $sampled | jq -s '.[].Maps|{(.[!].Key): .[].Value}'` and `echo $sampled | jq -s '.[].Maps|{(.[].Key): .[!].Value}'` .

The purpose of the `THIS` operator would be to select two or more elements at the same level in a structure with matching `THIS` operators.

**WARNING** Bonus Feature Extension
Speculatively, this semantic might tenuously lend itself to a `FOR` like operation?  I'm reaching here but hear me out, please.

`jq --lda lamda "echo ${sampled} | jq -s '.[].Maps[!].Value'" -r '.[]' <(web-api --id $lambda)`

I realise that this is really stretching things, maybe a bit too far.  I'm expecting to hear the snap at any moment.

The way that I imagine this would work. The primary jq instance in lambda mode would set an environmental variable as named by the label after the flag.  The lambda instance steps through its data structure where the `THIS` operator occurs. Each step returning the result to the named variable (without the `THIS` operator the lambda instance would only have one step).  The primary calling jq instance runs for that step and append its result set to its final output.  The lambda operation only completing once the lambda instance has exhausted its data structure.

Another term other than lambda may be more appropriate?

Equivalent to bash:
`for row in $(echo "$sampled" | jq -sr '.[].Maps[].Value') ; do`
`      jq -s '.[]' <(web-api id=$row);`
`done`

Thank you for taking the time read this.

Respectfully,

Stephen.

**Comment by pkoppstein** [comment]
@itchyny - The OP might not have understood that there is well-established “jq way” to achieve the type of transformation described in the first part of the original post: using `map` one can, for example, write:


     .Maps|map({(.Key):.Value})|add
     
This is also nicely succinct. 

 I suspect that the "speculative" proposal is likewise occasioned by lack of fluency in jq. So I’d recommend closing this issue, with the understanding that the OP is welcome to provide a less speculative proposal.
