### ISSUE TITLE
Try/catch doesn't work with field updates

### ISSUE THREAD

**Issue by burtgulash** [jqlang/jq#2230]
**Describe the bug**
try/catch doesn't seem to be working well with field updates.

**To Reproduce**
% echo '{"x":"123"}' | jq -c '.x = (.x | try tonumber catch "error")'
{"x":123}
% echo '{"x":"123"}' | jq -c '.x |= (try tonumber catch "error")'
{"x":"error"}

**Environment (please complete the following information):**
% jq --version
jq-1.6

**Comment by odnoletkov** [comment]
Seems like a duplicate of #2220 and #2140

**Comment by itchyny** [comment]
And this is already fixed in the master version.
```sh
 % jq --version
jq-master-a17dd32

 % echo '{"x":"123"}' | jq -c '.x = (.x | try tonumber catch "error")'
{"x":123}

 % echo '{"x":"123"}' | jq -c '.x |= (try tonumber catch "error")'
{"x":123}
```

**Comment by emanuele6** [comment]
jq 1.7 released with the fix.
```bash
$ jq --version
jq-1.7
$ echo '{"x":"123"}' | jq -c '.x = (.x | try tonumber catch "error")'
{"x":123}
$ echo '{"x":"123"}' | jq -c '.x |= (try tonumber catch "error")'
{"x":123}
```
closing
