### ISSUE TITLE
`error` ignores null input

### ISSUE THREAD

**Issue by odnoletkov** [jqlang/jq#2231]
**Describe the bug**
Both `error/0` and `error/1` do nothing for `null` (not empty!) input

**To Reproduce**

```
$ jq -n error
$ echo $?
0

$ jq -n 'error(null)'
$ echo $?
0
$
```

**Expected behavior**

Errors should never be ignored, should write stderr message and cause non-zero exit code

```
$ jq -n error
jq: error (at <unknown>) (not a string): null
$ echo $?
5
```

**Environment (please complete the following information):**

```
$ jq --version
jq-1.6
$ uname
Darwin
$ sw_vers -productVersion
11.0.1
```

**Comment by itchyny** [comment]
The behavior was changed by the following two commits before 1.5.

- a68958e5dcfee19478c1812ea73b01625c734029 fixing #466.
- b963ebaf1d0dc1ef5558a7dc4404e35cb4085fae changing the behavior of `jv_invalid_with_msg(jv_null())`.

```sh
 % ./jq-1.4 -n 'error(null)'
jq: error: null
 % ./jq-1.5 -n 'error(null)'

```
This seems to behave like `empty` (backtracking).
```sh
 % ./jq-1.4 -n '[1,error(null),2]'
jq: error: null
[
  1,
  2
]
 % ./jq-1.5 -n '[1,error(null),2]'
[
  1,
  2
]
```
I am not sure we can change the behavior from now whether it is intended or not.

**Comment by dmiraj** [comment]
This works on my side. Perhaps putting the `message` between a double quote will return the message you desired:
$ jq -n 'error("null")'
jq: error (at <unknown>): null

**Comment by itchyny** [comment]
This issue is about the input is `null` value, not just want a error message of null. Dirty workaround is to use `if . == null then tostring else . end | error`.

**Comment by odnoletkov** [comment]
> I am not sure we can change the behavior from now whether it is intended or not.

Do you mean we can't change it because of backwards compatibility? I.e. someone might be relying on this behavior of `error` ignored for `null` input? This seemed like a clear bug to me because:

* `null` and `empty` behave very differently almost everywhere in jq. The only exception I can remember is the `//` operator
* Ignoring errors is major source of issues in practice

@nicowilliams did you intend to change this behavior in above commits? Do you think this should be fixed or maybe just documented?

**Comment by itchyny** [comment]
This is an expected behavior of `error` filters. We should add some notes to the manual. I also noticed that `error/0` is not documented yet.

**Comment by nicowilliams** [comment]
> @nicowilliams did you intend to change this behavior in above commits? Do you think this should be fixed or maybe just documented?

The change to `error` to make it like `empty` when its input is `null` was unintentional.  I can see how that change can both: break backwards-compatibility with earlier versions of jq, and also be useful.  It's been like this in `master` for 9 years now, so I think we'll leave it as it is as changing it now would also be a backwards-incompatible change.  @itchyny has updated the documentation of `error` to match it's behavior.

**Comment by itchyny** [comment]
#2823 changed the behavior to throw an error this case.
