### ISSUE TITLE
Null output and exit code 0 on broken json

### ISSUE THREAD

**Issue by fednikx** [jqlang/jq#2236]
**Describe the bug**
jq returns a null output and exit code 0 while parsing a broken json

**Expected behavior**
I would expect an error message and exit code 4

**Environment:**
 - OS and Version: Linux, centos7, Debian 10
 - jq version: 1.5

**To Reproduce**
```
[root@2457d8a607a3 /]# echo '{"broken":"json"' | jq ; echo $?; jq --version
0
jq-1.5

**Comment by dcrouch79** [comment]
Upgrade to version 1.6

```
$ echo '{"broken":"json"' | jq ; echo $?; jq --version
parse error: Unfinished JSON term at EOF at line 2, column 0
4
jq-1.6
```
