### ISSUE TITLE
The string syntax in jq is different from JavaScript

### ISSUE THREAD

**Issue by hexagonrecursion** [jqlang/jq#2237]
**Describe the bug**
[The manual](https://github.com/stedolan/jq/blob/80052e5275ae8c45b20411eecdd49c945a64a412/docs/content/manual/manual.yml#L521-L522) says that strings in the jq language are written the same way as in JavaScript, but this is not the case. 

**To Reproduce**
jq fails to parse single quoted strings:
```
$ node -p "'foo'"
foo
$ jq -n "'foo'"
jq: error: syntax error, unexpected INVALID_CHARACTER, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
'foo'
jq: 1 compile error
```

jq fails to parse \XXX octal escapes:
```
$ node -p '"\101"'
A
$ jq -n '"\101"'
jq: error: Invalid escape at line 1, column 4 (while parsing '"\1"') at <top-level>, line 1:
"\101" 
jq: 1 compile error
```

jq fails to parse the \' escape:
```
$ node -p \"\\\'\"
'
$ jq -n \"\\\'\"
jq: error: Invalid escape at line 1, column 4 (while parsing '"\'"') at <top-level>, line 1:
"\'" 
jq: 1 compile error
```

jq fails to parse the \v escape
```
$ node -p '"\v"'


$ jq -n '"\v"'
jq: error: Invalid escape at line 1, column 4 (while parsing '"\v"') at <top-level>, line 1:
"\v" 
jq: 1 compile error
```

jq fails to parse \u{X} ... \u{XXXXXX} escapes:
```
$ node -p '"\u{41}"'
A
$ jq -n '"\u{41}"'
jq: error: Invalid \uXXXX escape at line 1, column 4 (while parsing '"\u"') at <top-level>, line 1:
"\u{41}" 
jq: 1 compile error
```

jq fails to parse \xXX escapes
```
$ node -p '"\x41"'
A
$ jq -n '"\x41"'
jq: error: Invalid escape at line 1, column 4 (while parsing '"\x"') at <top-level>, line 1:
"\x41" 
jq: 1 compile error
```

The list above is probably not exhaustive.

**Expected behavior**
The misleading documentation should be changed.

**Environment (please complete the following information):**
```
$ jq --version
jq-1.6
$ cat /etc/fedora-release 
Fedora release 32 (Thirty Two)
```

**Additional context**
The js string syntax is described here: https://tc39.es/ecma262/#sec-literals-string-literals

**Comment by pkoppstein** [comment]
@itchyny - The OP explicitly stated that this issue should be interpreted as a documentation bug report, not a functional ER.  Since @nicowilliams in particular has been emphatic that the j in jq should not lead us astray in the direction of javascript as opposed to JSON, I would suggest changing the tag of this issue accordingly.

**Comment by itchyny** [comment]
Thanks, and we don't have plan to support single quote string literals (don't we?), so closing now.

**Comment by pkoppstein** [comment]
@itchyny - unless the documentation has been fixed, it might be best to leave this open. Meanwhile, I’ll add the docs tag.
