### ISSUE TITLE
Question: expression in a file?

### ISSUE THREAD

**Issue by mrjcleaver** [jqlang/jq#2243]
It seems I have to put the expression on the command line. e.g.

>jq "[.result.account[] |  {accountName, id, numberOfEmployees, industry, billingCountry}]" 1data.json 1data2.json > 1and2.json

Is there a way to have jq read the expression from a file e.g.

expression.jq
`
[.result.account[] 
| {accountName, id, numberOfEmployees, industry, billingCountry}]
`

>jq -expression expression.jq 1data.json 1data2.json > 1and2.json

Thanks,
   Martin

**Comment by pkoppstein** [comment]
The -f option is documented in the online [manual](https://stedolan.github.io/jq/manual/), but it ought also to be documented by `jq --help`.

So this IR should count as an ER :-)

**Comment by mrjcleaver** [comment]
Re: it being an enhancement request, https://github.com/stedolan/jq/issues/new/choose provided only "Bug" or "Blank" as options.

So, yes, --help doesn't show -f as an option. The wording in the manual needs an explicit call out and example I feel. If you can mention how this can help with quoting issues on Windows and maybe provide linkage to https://stedolan.github.io/jq/manual/#example66 that would help people with related context.

Cheers, Martin

**Comment by pkoppstein** [comment]
As of 99a381b5aa2678243f9ccb919d4cf932e4e69810, the -f command-line option is mentioned by --help.
