### ISSUE TITLE
try in a map not working as expected

### ISSUE THREAD

**Issue by lhns** [jqlang/jq#2267]
**Describe the bug**
`try` in a `map` is not working as expected on the latest commit.
It does work fine in version 1.5 from the debian repository but that version is pretty slow.

**To Reproduce**
```sh
jq -n '["1", "a", "2"] | map(try tonumber catch null)'
```
```json
[
  1,
  null,
  null
]
```

**Expected behavior**
```
[
  1,
  null,
  2
]
```

**Environment (please complete the following information):**
 - OS and Version: debian 10
 - jq version 1.6 built from latest commit a17dd3248a666d01be75f6b16be37e80e20b0954 (there was a new commit since I built it but only the docs have changed)

**Comment by emanuele6** [comment]
This bug is not present in `jq 1.6`, and it has been fixed on master by c4d39c4d22f2b12225ca1b311708f7e084ad9ff8; so closing
