### ISSUE TITLE
Require binary for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [jqlang/jq#2275]
This is a feature request and not a bug report.

I was trying to build **zarplata/concourse-git-bitbucket-pr-resource** image on arm64 platform but it requires a jq binary which is not available for the arm64 platform.
I have built the binary successfully by following below steps:

- Cloned the package and ran git submodule update --init to get oniguruma and also installed libtool, autoconf make.

- Ran autoreconf -fi and then ./configure --with-oniguruma=builtin.

- Ran make -j8 and make check.

Do you have any plans to release binary for arm64?

It will be very helpful if the binary is released for arm64.

**Comment by yi2020** [comment]
I think I may have run into something similar, but want to check here before I open a new issue. Is this related to the above issue:

```
ImportError: dlopen(/Users/yoni/code/cloudrail/venv/lib/python3.8/site-packages/_pyjq.cpython-38-darwin.so, 2): Symbol not found: _jq_compile_args
  Referenced from: /Users/yoni/code/cloudrail/venv/lib/python3.8/site-packages/_pyjq.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/yoni/code/cloudrail/venv/lib/python3.8/site-packages/_pyjq.cpython-38-darwin.so
```

**Comment by tscolari** [comment]
+1 for arm64 Linux support.
Creates a bottle neck on tooling that has jq at heart :(

**Comment by odidev** [comment]
To deploy package **mspnp/microservices-reference-implementation** on arm64,  **Jq** binary for arm64 is also required. I have successfully build the jq binary on my local arm64 server with the latest commit. If required, I am happy to contribute in releasing the jq binary for arm64.
