### ISSUE TITLE
Multiple consecutive newlines are causing memory error and crash with --raw-input

### ISSUE THREAD

**Issue by rincewindcz** [jqlang/jq#2276]
**Describe the bug**
When trying to escape string containing multiple consecutive newline characters, jq is crashing with `malloc(): unaligned tcache chunk detected` or `free(): invalid pointer`. Valgrind shows Invalid read of size 4.

**To Reproduce**
`printf "hello \n\n world" | jq --ascii-output --raw-output --raw-input .`

**Expected behavior**
jq should not crash

**Environment (please complete the following information):**
 - OS and Version: Arch Linux, Ubuntu 20.04 LTS
 - jq version: jq-1.6

**Additional context**
Tested also on Windows 10, jq-1.6 and it is not crashing, but I'm unable to verify if it's due to luck or the memory error is missing there.

**Comment by itchyny** [comment]
This was fixed by a1f1231a73c221155d539a281181ef37f874869d on Nov 20, 2018, after 1.6.
