### ISSUE TITLE
Document difference between expanding to an array or to an object using an 'if' statement.  

### ISSUE THREAD

**Issue by dekerser** [jqlang/jq#2277]
Hi,

I'm not sure if this is a bug, or whether it should just be documented as a "Pitfall".
I was quite confused by it, but perhaps it is because I'm relatively new to jq. I couldn't find any documentation on it perhaps I missed it, or was searching for wrong keywords ...

The input is a line, from a log:
```
{
  "date": "2021/02/25 11:14:59",
  "FRITZ!DECT 301 #3": {
    "name": "FRITZ!DECT 301 #3",
    "battery": "30",
    ....
  }
}

```
I want to see the date and the "battery" status, which is produced as strings with the following filter:
[(.date) , .[].battery?](https://jqplay.org/s/m2dr0MvjLa)

Suppose we want to return it as an array we would change it too:
[[(.date) , .[].battery? ]](https://jqplay.org/s/-07JwNNdis)
Or as an object:
[{(.date) : .[].battery? }](https://jqplay.org/s/JOZp_fkeIW)

I wanted to use an if statement, instead of the '?' construct, so first for the array output, which works fine:
[[ .[] | if type == "object" then .battery else . end ]](https://jqplay.org/s/z_hkAB-B99)
Here the confusion started when I tried to output an object, as my first attempt, changing '[' to '}' brackets, gave a compile error:
[{ .[] | if type == "object" then .battery else . end }](https://jqplay.org/s/Pm_2tHuzAg)

After quite some research the following seemed to be the correct way to generate an object:
[{ (.date) : (.[] | if type == "object" then  .battery  else empty end) }](https://jqplay.org/s/lNXdAS_FP8) 

So while implicit expanding to an array works fine with an 'if' construct, it fails for expanding to an object. Only when we explicitly force it to the ":" format the output succeeds. The "asymmetry" is unexpected, at least by me :-), and I think  should be documented or perhaps if possible repaired. The man page and its examples, do seems to "state" that the {,} and [,] constructs are symmetric. Of course the problem arises here because we need {:}, which is also in the '{}' manual topic.

p.s. Big fan of jq! Great how it e.g. allows to handle complex data structures in 'bash' by storing "json" data in shell variables...

**Comment by pkoppstein** [comment]
@itchyny - in my view, this issue should simply be closed. No-one has offered a PR in the 2+ years since the issue was raised, and adding another example along the lines suggested would be akin to bloat.

If anyone feels strongly that more documentation about this example would help, then a PR would be one option, and adding to the jq FAQ or Cookbook would be another.
