### ISSUE TITLE
Problem to extract json text with JQ

### ISSUE THREAD

**Issue by lionelcanon** [jqlang/jq#2290]
Hello everybody,

I have a problem to extract Json text with the command $FILECONTENT=$(cat $JSON_FILE_RESULT | .\jq-win64.exe .fichier)
JQ delete the character ' \\'so the json text is corrupt :(

can you help me please ?
Thank you :)
[qlik_-_un_test_simple.zip](https://github.com/stedolan/jq/files/6195783/qlik_-_un_test_simple.zip)

**Comment by hellow554** [comment]
maybe use `\\` instead?
