### ISSUE TITLE
seg fault when regex split a string with connector punctuation at word boundary (jq 1.6 macOS)

### ISSUE THREAD

**Issue by elder-n00b** [jqlang/jq#2301]
**Describe the bug**
I get segmentation fault trying to split a string containing a Unicode "connector punctuation" character at word boundaries. 
I then tried with a Cyrillic letter (Ԕ) and got the same result.

**To Reproduce**
`echo '"a b﹏c d"' | jq 'split("\\b";"")'` ("Segmentation fault: 11" or "jq quit unexpectedly" when calling jq from VSCode)
https://jqplay.org/s/Y1mXHvy9mx ("signal: segmentation fault")

**Expected behavior**
`["a","b﹏c","d"]` or at least not a segfault.

**Environment**
 - jq 1.6
 - macOS 10.11.6
 - Terminal reports `LC_CTYPE=UTF-8`
 
**Additional context**
Most probably an Oniguruma thing.
- I have read [kkos/oniguruma/blob/master/doc/RE](https://github.com/kkos/oniguruma/blob/master/doc/RE) and there is no Unicode note about `\b`.  
- I noticed `y{?}: Text Segment mode` and tried to provide the flag but I get `Regex failure: undefined group option` from jq.  
- I did not find any way to set or even know if jq's Oniguruma is expecting Unicode or not, though `man jq` indicates that jq should indeed deal with Unicode.
- I searched issues on [kkos/oniguruma](https://github.com/kkos/oniguruma) but did not find anything relevant.
- I found another regex word boundary unexpected behavior: spurious empty strings when splitting a "normal" string (only a-z and space). https://jqplay.org/s/ez12mYzISR

Attached segfault report from macOS (jq called from VSCode).
[ERROR__jq_regex_segfault.txt](https://github.com/stedolan/jq/files/6327163/ERROR__jq_regex_segfault.txt)

**Comment by vintnes** [comment]
This is fixed on master.

```
$ jq -V;  jq -nc '"a b﹏c d" | split("\\b";"")'
jq-1.6
Segmentation fault

$ jq/jq -V;  jq/jq -nc '"a b﹏c d" | split("\\b";"")'
jq-1.6-137-gd18b2d0-dirty
["","a"," ","b﹏c","","","c",""," ","d"]
```

Workaround for 1.6: use `split/1`

```
$ jq -V;  jq -nc '"a b﹏c d" | split("\\b")'
jq-1.6
["a b﹏c d"]
```

**Comment by vintnes** [comment]
This has been fixed on master.

```
$ jq -V;  jq -nc '"a b﹏c d" | split("\\b"; "")'
jq-1.6
Segmentation fault

$ jq/jq -V;  jq/jq -nc '"a b﹏c d" | split("\\b"; "")'
jq-1.6-137-gd18b2d0-dirty
["","a"," ","b﹏c","","","c",""," ","d"]
```
