### ISSUE TITLE
oniguruma need update ?

### ISSUE THREAD

**Issue by tst2005** [jqlang/jq#2308]
I see [modules/oniguruma @ 6fa38f4](https://github.com/stedolan/jq/tree/master/modules) seems quiet old.
There are some security issues fixed during 4 years (see [oniguruma changelog](https://github.com/kkos/oniguruma/releases)).

It is not clear for me if oniguruma is really used...
what is the status of it ?

**Comment by itchyny** [comment]
You can find where it is used [by page search in the document](https://stedolan.github.io/jq/manual/#:~:text=oniguruma). It is used for `test`, `match`, and `capture` filters. If you think the dependency is old, you can send pull request and join developing jq. Thanks.

**Comment by itchyny** [comment]
The dependency was updated in #2596, so closing.
