### ISSUE TITLE
limit(0; is broken

### ISSUE THREAD

**Issue by ajmalton** [jqlang/jq#2316]
limit(0;range(10)) yields 0

I tried this on jq-1.6 on two platforms, and also on jqplay.

It ought to be empty, of course.

**Comment by vintnes** [comment]
Fixed on master

    $ jq --version; jq -n 'limit(0; range(1))'
    jq-1.6
    0

    $ jq/jq --version; jq/jq -n 'limit(0; range(1))'
    jq-1.6-137-gd18b2d0-dirty

**Comment by pkoppstein** [comment]
Fixed by Commit 9a0d5be790f0c89c02ffde11144157f067b19fd1
