### ISSUE TITLE
travis-ci.org is shutting down

### ISSUE THREAD

**Issue by martinvonwittich** [jqlang/jq#2318]
I clicked on the [![Build Status](https://travis-ci.org/stedolan/jq.svg?branch=master)](https://travis-ci.org/stedolan/jq) button in the readme. The site says:

>  Please be aware travis-ci.org will be shutting down by end of May 2021. Please consider migrating to travis-ci.com.

More details can be found here: https://blog.travis-ci.com/2021-05-07-orgshutdown

**Comment by itchyny** [comment]
We have switched to GitHub Actions in #2596. But still, icon and CI configuration remain in the repository.
