### ISSUE TITLE
jq foreach使用问题

### ISSUE THREAD

**Issue by zhouhuihua526** [jqlang/jq#2326]
Hello, I want to delete the null value in the list, how to achieve it?
such as:
[
   [
     {"name":"JSON", "good":true},
     {"name":"XML", "good":false}
   ],
   null,
   [
     {"name":"yml", "good":false}
   ]
]
Need to delete the second item null

**Comment by wader** [comment]
Try something like `map(select(. != null))` https://jqplay.org/s/RBGbCKXanI
