### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by scottyob** [jqlang/jq#2327]
1.6 is a bit old, and the changes in master around introducing decNumber for supporting 64-bit numbers would really help us.  Is master stable enough to do a release?

**Comment by scottyob** [comment]
please? :P

**Comment by hexagonrecursion** [comment]
There is a bounty for this issue on bountysource https://www.bountysource.com/issues/99158867-can-we-get-a-new-release

**Comment by jc-dgit** [comment]
As a data point, ongoing jq project maintainership structure is being discussed in #2305.

**Comment by emanuele6** [comment]
Yes
