### ISSUE TITLE
"Unknown option -----END" error while working with JSON with key/value pairs(that contain public key) in bash shell

### ISSUE THREAD

**Issue by Bhaskar1312** [jqlang/jq#2330]
D:\ProgramData\jq\jq.exe: Unknown option -----END
Use D:\ProgramData\jq\jq.exe --help for help with command-line options,
or see the jq manpage, or online docs at https://stedolan.github.io/jq

**Comment by Bhaskar1312** [comment]
D:\ProgramData\jq\jq.exe: Unknown option -----END
Use D:\ProgramData\jq\jq.exe --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq

**Comment by itchyny** [comment]
No reproducible example is given, so closing the issue.
