### ISSUE TITLE
Strange behavior on output parsing 

### ISSUE THREAD

**Issue by xl-tech** [jqlang/jq#2331]
**Describe the bug**
jq formatting floating point numbers to Scientific Notation differently for similar output.

**To Reproduce**
curl -s https://api-pub.bitfinex.com/v2/tickers?symbols=fUSD :
[["fUSD",0.00015455068493150685,0.000135,120,16992566.8081159,0.00009212,2,1248170.4817084703,-0.000004,-0.04,0.000096,170277504.11872676,0.000135,1e-8,null,null,353935968.57143486]]

curl -s https://api-pub.bitfinex.com/v2/tickers?symbols=fUSD|jq :
[
  [
    "fUSD",
    0.00015455068493150685,
    0.000135,
    120,
    16992566.8081159,
    9.212e-05,
    2,
    1248170.4817084703,
    -4e-06,
    -0.04,
    9.6e-05,
    170277504.11872676,
    0.000135,
    1e-08,
    null,
    null,
    353935968.57143486
  ]
]

curl -s https://api-pub.bitfinex.com/v2/tickers?symbols=fEUR :
[["fEUR",0.000047246575342465755,0.000075,120,155740.75316847,0.00002111,2,42180130.94364965,-0.00002127,-0.2127,0.00002211,11394595.81270521,0.00004864,0.00000416,null,null,42108608.0037314]]

curl -s 'https://api-pub.bitfinex.com/v2/tickers?symbols=fEUR'|jq :
[
  [
    "fEUR",
    4.7246575342465755e-05,
    7.5e-05,
    120,
    155740.75316847,
    2.111e-05,
    2,
    42180130.94364965,
    -2.127e-05,
    -0.2127,
    2.211e-05,
    11394595.81270521,
    4.864e-05,
    4.16e-06,
    null,
    null,
    42108608.0037314
  ]
]

So for fUSD 0.00015455068493150685 is not converted, but for fEUR 0.000047246575342465755 is converted to 4.7246575342465755e-05
For fUSD 0.000135 is not converted, but for fEUR 0.000075 is converted to 7.5e-05

**Expected behavior**
All number converted to Scientific Notation in the same way or not convert them at all :)

**Environment (please complete the following information):**
Ubuntu 18.04
jq --version: jq-1.5-1-a5b5cbe
also tested with ./jq-linux64 --version: jq-1.6

**Comment by vintnes** [comment]
This is fixed on master

```
~ jq -V
jq-1.6-137-gd18b2d0-dirty

~ jq . <<< 0.00015455068493150685
0.00015455068493150685
```

**Comment by vintnes** [comment]
Literal representation of big numbers is fixed on master, but note that performing math still causes implicit rounding.

```
~ jq -V
jq-1.6-137-gd18b2d0-dirty

~ jq . <<< 0.000047246575342465755
0.000047246575342465755

~ jq '. + 1' <<< 0.000047246575342465755
1.0000472465753425
```

**Comment by xl-tech** [comment]
Thank you, I'll try to compile latest version now.

**Comment by emanuele6** [comment]
jq 1.7 released with the fix. closing
