### ISSUE TITLE
Linker bug: the first function in a module gets lost (was: spurious "compile error")

### ISSUE THREAD

**Issue by pkoppstein** [jqlang/jq#2353]
There's a rather weird problem that appeared after the release of jq 1.6.  It concerns a "module" file (i.e. one that only has defs), and is easily demonstrated with just two lines:

def a: 0;
def b: a;

Here is a transcript showing all is well with jq 1.6 but not with jqMaster:
$ jq1.6 --version
jq-1.6
$ jq1.6 -n -f bug.jq
null

$ jqMaster --version
jq-1.6-129-g80052e5-dirty
$ jqMaster -n -f bug.jq
jq: error: a/0 is not defined at <top-level>, line 13:
def b: a;       
jq: 1 compile error

Fortunately the problem does not arise when the file is "include"d.

Environment: macOS 10.14.16

**Comment by wader** [comment]
Seems to be a regression since e843a4fdf9f6f446f5ddebf2c108cb7d4dda867b

With previous commit i get `null` for `jq -n -f <(echo 'def a: 1;def b: a;')`

Unrelated to this i also noticed this difference to gojq while poking around:
```sh
$ jq -n -f <(echo 'def a: b;1')
1
$ gojq -n -f <(echo 'def a: b;1')
gojq: compile error: function not defined: b/0
```

**Comment by wader** [comment]
Some progress, master with this patch seem to behave more correct, `make check` passes and `def a: 1;def b: a;` return `null`. But as i still don't fully understand e843a4fdf9f6f446f5ddebf2c108cb7d4dda867b it may undo what it was suppose to improve.

```diff
diff --git a/src/compile.c b/src/compile.c
index b713bc3..e650313 100644
--- a/src/compile.c
+++ b/src/compile.c
@@ -367,7 +367,7 @@ static int block_bind_each(block binder, block body, int bindflags) {
   return nrefs;
 }
 
-static block block_bind(block binder, block body, int bindflags) {
+block block_bind(block binder, block body, int bindflags) {
   block_bind_each(binder, body, bindflags);
   return block_join(binder, body);
 }
diff --git a/src/compile.h b/src/compile.h
index cccd661..7894814 100644
--- a/src/compile.h
+++ b/src/compile.h
@@ -72,6 +72,7 @@ int block_has_only_binders(block, int bindflags);
 int block_has_main(block);
 int block_is_funcdef(block b);
 int block_is_single(block b);
+block block_bind(block binder, block body, int bindflags);
 block block_bind_library(block binder, block body, int bindflags, const char* libname);
 block block_bind_referenced(block binder, block body, int bindflags);
 block block_bind_self(block binder, int bindflags);
diff --git a/src/parser.y b/src/parser.y
index a5fc9da..066f9f5 100644
--- a/src/parser.y
+++ b/src/parser.y
@@ -341,7 +341,7 @@ FuncDefs:
   $$ = gen_noop();
 } |
 FuncDef FuncDefs {
-  $$ = block_join($1, $2);
+  $$ = block_bind($1, $2, OP_IS_CALL_PSEUDO);
 }
 
 Exp:

```

**Comment by nicowilliams** [comment]
> But as i still don't fully understand https://github.com/jqlang/jq/commit/e843a4fdf9f6f446f5ddebf2c108cb7d4dda867b it may undo what it was suppose to improve.

It might indeed.  We used to have accidentally quadratic (worse, IIRC) linking performance.  @muhmuhten thankfully sent us a patch to make linking fast again.  It was truly awful before, so much so that we didn't want to add anymore builtins for a while!

**Comment by nicowilliams** [comment]
> There's a rather weird problem that appeared after the release of jq 1.6. It concerns a "module" file (i.e. one that only has defs), and is easily demonstrated with just two lines:
> 
> ```
> def a: 0;
> def b: a;
> ```

This lacks an actual program, therefore using `jq -f ...` with that file must fail.  The problem here is that the error message is incorrect.
