### ISSUE TITLE
Identify undefined values

### ISSUE THREAD

**Issue by juanrgm** [jqlang/jq#2365]
**Describe the bug**
You can't differentiate between null and undefined.

**To Reproduce**
```sh
# exit code 1 
$ echo '{"a": null}' | jq -re ".a"
null
# exit code 1
$ echo '{"a": null}' | jq -re ".b"
null
```

**Expected behavior**
Undefined values should return a special exit code.

**Environment (please complete the following information):**
 - OS and Version: Alpine Linux 3.12
 - jq version: jq-master-v20200428-28-g864c859e9d

**Comment by itchyny** [comment]
Unlike JavaScript, JSON (and jq) does not have `undefined`. The `--exit-status` (`-e`) flag can distinguish `false` so you can use `has` function.
```sh
❯ echo '{"a": null}' | jq -e 'has("a")'
true
❯ echo $?
0

❯ echo '{"a": null}' | jq -e 'has("b")'
false
❯ echo $?
1
```
But this may not be useful answer for more complex queries. I think https://github.com/stedolan/jq/issues/543#issuecomment-290261990 is related to this topic and interesting solution.

**Comment by itchyny** [comment]
As I commented above, the original examples can be distinguished by `has/1`, so closing the issue.
