### ISSUE TITLE
List as contains() target requires explicit definition or variable, not object reference

### ISSUE THREAD

**Issue by philhagen** [jqlang/jq#2379]
**Describe the bug**
Using the `contains()` operator with an array as the operand requires either an explicit list or a variable.  You can't reference an element within the JSON structure

**To Reproduce**
```
$ echo '{}' | jq '.a=["foobar", "foobaz", "blarp"] | .b=["baz", "bar"] | .a|contains(.b)'
jq: error (at <stdin>:1): Cannot index array with string "b"

$ echo '{}' | jq '.a=["foobar", "foobaz", "blarp"] | .b=["baz", "bar"] | .a|contains(["baz", "bar"])'
true
$ echo '{}' | jq '.a=["foobar", "foobaz", "blarp"] | .b=["baz", "bar"] | (.b as $wtf | .a | contains($wtf))'
true
```

**Expected behavior**
```
$ echo '{}' | jq '.a=["foobar", "foobaz", "blarp"] | .b=["baz", "bar"] | .a|contains(.b)'
true
```

**Environment (please complete the following information):**
 - OS and Version: macOS Monterey
 - jq version 1.6

**Comment by itchyny** [comment]
This is how jq pipe works, not a bug of `contains` function. The query `.a | contains(.b)` firstly extracts `a`, and then looks up `b` for the argument. You can assign the input object as a variable; `. as $x | $x.a | contains($x.b)'`.
