### ISSUE TITLE
SCRIPTING: Exit status code of jq is always 0, even if the section does not exists 

### ISSUE THREAD

**Issue by pthreat** [jqlang/jq#2383]
**Describe the bug**
cat file.json | jq .non-existent-section should exit with status code of failed (1) but it always exits with 0

**To Reproduce**

cat file.json | jq .non-existent-section 
echo $? # 0

cat file.json | jq .existing-section
echo $? # 0

**Expected behavior**

cat file.json | jq .non-existing-section 
echo $? # 1

cat file.json | jq .existing-section 
echo $? # 0

**Environment (please complete the following information):**
 - Debian 10
 - jq version 1.6

**Comment by emanuele6** [comment]
That is not what should happen, `.foo` when used on an `object` (or `null`) should return either the value of the "foo" field if it exists or `null`.

It is also shown in one of the examples listed in the section of the manual that describes the feature:
```
Object Identifier-Index: .foo, .foo.bar
    The simplest useful filter is .foo. When given a JSON object (aka  dic‐
    tionary  or  hash) as input, it produces the value at the key "foo", or
    null if there's none present.

    A filter of the form .foo.bar is equivalent to .foo|.bar.

    This syntax only works for simple, identifier-like keys, that is,  keys
    that  are all made of alphanumeric characters and underscore, and which
    do not start with a digit.

    If the key contains special characters, you need to  surround  it  with
    double quotes like this: ."foo$", or else .["foo$"].

    For  example  .["foo::bar"]  and .["foo.bar"] work while .foo::bar does
    not, and .foo.bar means .["foo"].["bar"].

        jq '.foo'
           {"foo": 42, "bar": "less interesting data"}
        => 42

        jq '.foo'
           {"notfoo": true, "alsonotfoo": false}
        => null

        jq '.["foo"]'
           {"foo": 42}
        => 42
```

`.foo` should fail when used on something that is not an object:
```shell
$ jq -rn '({}, [], 1, "", null) | "\(type):\t\(try .foo catch .)"'
object:	null
array:	Cannot index array with string "foo"
number:	Cannot index number with string "foo"
string:	Cannot index string with string "foo"
null:	null
```

That is different from `.foo?` that is equivalent to `empty` in the case where `.foo` would fail:
```shell
$ jq -rn '({}, [], 1, "", null) | "\(type):\t\(try .foo? catch .)"'
object:	null
null:	null
```
