### ISSUE TITLE
Divide large array into X array

### ISSUE THREAD

**Issue by stephane-r** [jqlang/jq#2388]
Hi community,

Do you know if we can divide large array into X array by using `jq` ? For example, an JSON array with 200 entries, divided in 5 subarray.

I've try with `[_nwise(length / 5 | floor)]`, but the number off array can not always be 5 :/

**Comment by itchyny** [comment]
How about `[_nwise(5)] | transpose | map(map(values))`, assuming input array does not contain `null`?

**Comment by stephane-r** [comment]
Hello @itchyny 

It same working, but i'm not really sur to understand 🤔. There can be no duplicate ?

**Comment by pkoppstein** [comment]
Use `ceil`: 

     [_nwise(length / 5 | ceil)]

**Comment by itchyny** [comment]
Using `ceil` does not work with `[range(6)]`.

**Comment by pkoppstein** [comment]
@itchyny - 6 is not large, as per the original question.

**Comment by stephane-r** [comment]
For now, my initial array have +200 entries ^^. The result between `ceil` and `transpose` are same, but not `floor` 🥲
