### ISSUE TITLE
Numbers longer 17 digits wiped by zeroes

### ISSUE THREAD

**Issue by Hubbitus** [jqlang/jq#2396]
**Describe the bug**
On windows (wsl) and https://jqplay.org/ numbers longer than 17 digits got 0 in rest.

**To reproduce**
```shell
$ echo '{"userId": 11111111112222222222}' | jq '.userId'
11111111112222222000
```
I can't reproduce that on my Fedora Linux machine, but that is 100% reproducible on windows (wsl2, ubuntu).

Also, please take a look at play https://jqplay.org/s/I-2MjR2xyq:
![image](https://user-images.githubusercontent.com/720349/148810148-71dc36f4-6481-4f66-a52a-5dd8b51ba887.png)

What also interesting, filtration also happened incorrectly (https://jqplay.org/s/hIYsvWo0co):
![image](https://user-images.githubusercontent.com/720349/148810362-db0758f3-23a2-40e6-81ef-684fda50d267.png)

**Expected behavior**
The last snippet return the single result 11111111112222222222

**Environment (please complete the following information):**
 - OS and Version: Windows (wsl, Ubuntu)
 - jq version 1.6

**Comment by bergus** [comment]
This seems expected. https://stedolan.github.io/jq/manual/#Math:

> jq currently only has IEEE754 double-precision (64-bit) floating point number support.

**Comment by itchyny** [comment]
This is a frequently asked question (#545 #1652 #1959 #2109 #2131 #2182 #2201) and is already fixed in the master version (implemented by #1752 in Oct, 2019).
```
 $ jq --version
jq-1.6-145-ga9f97e9
 $ echo '{"userId": 11111111112222222222}' | jq '.userId'
11111111112222222222
```

**Comment by Hubbitus** [comment]
Thank you

**Comment by emanuele6** [comment]
jq 1.7 released with the fix. closing
