### ISSUE TITLE
Question: PDF manual

### ISSUE THREAD

**Issue by ivanperez-keera** [jqlang/jq#2402]
I find reading the web manual really hard. Just the idea of traversing the documentation using a web seems like a steep hill to me.

Is there a manual in PDF I can download, or a book I can buy?

Thanks.

**Comment by emanuele6** [comment]
```
$ man -Tpdf jq > jq_manual.pdf
$ xdg-open jq_manual.pdf
```

**Comment by pkoppstein** [comment]
If you are looking for documentation that is strictly linear, then perhaps one or both of the following will be of interest to you, though neither is as comprehensive as the official manual:

1) https://github.com/stedolan/jq/wiki/jq-Language-Description

2) https://github.com/pkoppstein/jq/wiki/A-Stream-oriented-Introduction-to-jq

---
<sup>Disclaimer: I am the author of (2).</sup>

**Comment by wader** [comment]
@pkoppstein Thanks for (2), very well written article. I will surely use it and link people to it.
I've thought about writing some kind of "practical jq" article that walks thru some use cases, simliar to a practical fq article that i'm working on https://github.com/wader/fq/blob/f6f48cba3bcd22705cb8c391ed4a050a42b57824/doc/guides/fra-pcap-challenge-2021-09/README.md

**Comment by pkoppstein** [comment]
@wader - Comments and suggestions re 2 are welcome. Tx.

Anyone interested in a (linear) collection of practical (for the most part) applications of jq might find the jq Cookbook useful - https://github.com/stedolan/jq/wiki/Cookbook

For a (nonlinear) collection of more than 800 examples, see https://rosettacode.org/wiki/Category:Jq

**Comment by itchyny** [comment]
Although we don't provide a PDF manual, you can build from the man page as suggested above, and you can also use browser to print the page to a PDF file. I actually redesigned the manual page carefully for printer users in #2628.
