### ISSUE TITLE
Invalid numeric literal is accepted as valid.

### ISSUE THREAD

**Issue by davidfetter** [jqlang/jq#2413]
**Describe the bug**
jq accepts numbers followed only by a period as valid JSON. According to the [JSON spec](https://www.crockford.com/mckeeman.html), this is an error, as a fraction is either the empty string or a `.` followed by at least one digit.

**To Reproduce**
```
jq -n 23.
```

**Expected behavior**

```
jq: error: Invalid numeric literal at EOF at line 1, column 3 (while parsing '23.') at <top-level>, line 1:
23.
jq: 1 compile error
```

**Environment (please complete the following information):**
 - OS and Version: Fedora Linux 35
 - jq version 1.6 and a9f97e9e61a910a374a5d768244e8ad63f407d3e
I'm pretty sure this doesn't change the outcome

**Additional context**

**Comment by pkoppstein** [comment]
@itchyny - As indicated in my comment above, permissiveness is allowed by the relevant standards; for this reason and because there has been some discussion about a --strict flag, I think it would be appropriate to change the "bug" label to "feature request". It might also be helpful if the title of this thread was adjusted as well.

**Comment by itchyny** [comment]
I read the original comment again. This looks like a bug report about jq query syntax accepting relaxed format numbers. I don't think this is a bug, as long as we have no formal definition of jq syntax. And note that the query `[1.,.1]` is accepted both by jq and gojq. On jq-specific extension of JSON numbers (which could be claimed as a bug per JSON spec, by those who thinks jq should accept JSON strictly), we have #1389, #2414, and also #1404 (opinion divided among the maintainers). The numbers in jq query do not need to follow JSON spec, so closing this issue.
