### ISSUE TITLE
[bug] Wrong version number on alpine package

### ISSUE THREAD

**Issue by gabyx** [jqlang/jq#2417]
**Describe the bug**
`apk add jq` gives you a jq version `jq --version` as `jq-master-v3.15.0_alpha20210804-4073-gb39e1241e8` which is just not good. Not sure who maintains this package.

**Expected behavior**
`apk add jq` gives a jq with proper version output. `1.6.0` etc...

**Environment (please complete the following information):**
 - OS and Version: Linux, alpine latest.

**Comment by bfren** [comment]
The package is also quite old now - I actually build it myself because the master is so much faster.  It would be much easier if the official package could be updated / rebuilt - my Docker image build time has gone from 1m to 8-10m.

**Comment by nathansgreen** [comment]
@gabyx This is an issue with Alpine Linux. It's maintained within the Alpine Linux project. The build script is linked below. You can submit your own patch to the project and they will almost certainly accept it.
https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/jq/APKBUILD
