### ISSUE TITLE
Can't use the search bar in the documentation because it is too low under the table of contents in the side pane

### ISSUE THREAD

**Issue by adriancuadrado** [jqlang/jq#2419]
![image](https://user-images.githubusercontent.com/29214635/160304393-8969204d-31b6-4579-9df0-ef1ab4f18873.png)

I can't scroll down to see the results because the results of the search stay at the bottom of the page. Please move that search bar to the right side of the website or somewhere else where you can see the results or something.

**Comment by Sashank999** [comment]
Damn I didn't know there was a search bar. I was using Ctrl + F browser search always.
