### ISSUE TITLE
There is an example in the documentation that doesn't work

### ISSUE THREAD

**Issue by adriancuadrado** [jqlang/jq#2420]
![image](https://user-images.githubusercontent.com/29214635/160304589-bea5049e-c9a7-4606-a7fe-f8aa0ca20178.png)

```
$ jq '"f o o" as $foo | "b a r" as $bar | {$foo, $bar:$foo}'
jq: error: syntax error, unexpected ':', expecting '}' (Unix shell quoting issues?) at <top-level>, line 1:
"f o o" as $foo | "b a r" as $bar | {$foo, $bar:$foo}                                               
jq: error: May need parentheses around object key expression at <top-level>, line 1:
"f o o" as $foo | "b a r" as $bar | {$foo, $bar:$foo}                                     
jq: 2 compile errors
```

**Comment by itchyny** [comment]
I agree the development version manual is sometimes misleading for new comers, and hopefully it shows the latest released version by default (after we cut a new release). But this topic arises various concerns not only the URL structure, docs source structure, but leads to discussion on better releasing strategy. But thanks for pointing this out anyway.
