### ISSUE TITLE
rindex yields wrong results on overlapped occurrence

### ISSUE THREAD

**Issue by itchyny** [jqlang/jq#2433]
**Describe the bug**
`s | rindex(t)` yields wrong results when `t` appears in `s` with overlapped occurrence.

**To Reproduce**
```sh
 % jq -n '"ababa" | rindex("aba")'                      
0
```
**Expected behavior**
Considering `rindex` should yield the last occurrence index, the result should be `2` since `"ababa"[2:]` is `"aba"`.

**Environment (please complete the following information):**
 - OS and Version: macOS 12.4
 - jq version: jq-1.6-159-gcff5336 (cff5336ec71b6fee396a95bb0e4bea365e0cd1e8)

**Additional context**
The filter works well with overlapped occurrence in arrays.
```sh
 % jq -n '["a","b","a","b","a"] | rindex(["a","b","a"])'
2
```
This issue is an instance of the inconsistent behavior of `indices`.
```sh
 % jq -n '"abababa" | indices("aba")'
[
  0,
  4
]
 % jq -n '["a","b","a","b","a","b","a"] | indices(["a","b","a"])'
[
  0,
  2,
  4
]
```

**Comment by pkoppstein** [comment]
@emanuele6 - Any chance of fixing the def of`index/1` while you're at it?

The line in builtin.jq says it all: `def index($i):   indices($i) | .[0];       # TODO: optimize`
