### ISSUE TITLE
tar ball jq-jq-1.6.tar.gz miss file "configure"

### ISSUE THREAD

**Issue by zeroleo12345** [jqlang/jq#2448]
according the readme.md for complie from tar ball, it seem that lack of file "configure".
and in old version, "configure" file exist, like in jq-1.5.tar.gz

**Comment by zeroleo12345** [comment]
<img width="719" alt="image" src="https://user-images.githubusercontent.com/13072815/176181535-d06423d9-2a3f-4db8-b070-6b94430955ee.png">
oh yes. BTW, what's the difference in these 2 tar ball ?

**Comment by wader** [comment]
Not sure but i think "Source code (tar.gz)" is just the files in the repo (no configure file) and jq-1.16.{tar.gz,zip} are the result from automake dist (a configure script it generated).
