### ISSUE TITLE
NoScript XSS warning when following link to jq manual

### ISSUE THREAD

**Issue by jhnc** [jqlang/jq#2455]
**Describe the bug**

Following `#name` links to jq manual website give NoScript XSS warnings in firefox.

**To Reproduce**

The `map` description is at: https://stedolan.github.io/jq/manual/v1.6/#map(x),map_values(x)

NoScript reports:
> NoScript XSS Warning
>
> NoScript detected a potential Cross-Site Scripting attack from [...] to https<nop>://stedolan.github.io
> Suspicious data:
>(URL) https<nop>://stedolan.github.io/jq/manual/v1.6/#map(x),map_values(x)

This happens even if I encode `(),` &rarr; `%28%29%2C`

**Expected behavior**

No warning from NoScript

**Environment (please complete the following information):**
- Linux (xubuntu 20.04)
- jq 1.6 (website)

**Additional context**

**Comment by itchyny** [comment]
I don't think this is caused by section ids but probably due to CDN resources without subresource integrity. Anyway the manual does nothing wrong, and you can configure NoScript extension to trust the URL. Hopefully resolved by #2628.
