### ISSUE TITLE
jq can not parse `\\"`: parse error: Invalid numeric literal at line x, column y

### ISSUE THREAD

**Issue by blueray453** [jqlang/jq#2471]
I am using jq-1.6

I have checked https://github.com/stedolan/jq/issues/501

A program gives output like the following which jq can not parse because of `\\"`

```
[
    {
    "name": null,
    "wm_class_instance": "Navigator",
    "wm_class": "firefox",
    "title": "this is a \\"test string\\" to test bug - Google Search — Mozilla Firefox"
    },
    {
    "name": null,
    "wm_class_instance": "gnome-shell",
    "wm_class": "Gnome-shell",
    "title": "gnome-shell"
    }
]
```
It gives error
    
    parse error: Invalid numeric literal at line x, column y

I checked and if I replace `\\"` with `\"`, it works.

However, it is not in my control what the program will output.

What is the best solution here?

**Comment by pkoppstein** [comment]
jq expects valid JSON (or character strings when the -R command-line option is specified) as input.  There is no easy way to get jq to handle invalid JSON input such as yours.  You would either have to "preprocess" it in some way (perhaps using `sed` to perform the replacement), or fix the problem at the source.

**Comment by wader** [comment]
@pkoppstein beat me to it :)

If the issue is specifically `\\"` you might be able to do something like `jq -Rs 'gsub("\\\\\"";"\"") | fromjson'` but i suspect it might mess up some other cases
