### ISSUE TITLE
Could not handshake: The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by sanjanasekar** [jqlang/jq#2506]
Trying to build jq in our AWS CodeBuild using the following commands 

      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get update -y

But it failed with the following error 
```
Err:8 https://dl.bintray.com/sbt/debian  Release
  Could not handshake: The TLS connection was non-properly terminated. [IP: 52.41.41.147 443]
```

and finally ends with 

```
Reading package lists...
E: The repository 'https://dl.bintray.com/sbt/debian  Release' does not have a Release file.
[Container] 2022/11/23 23:31:11 Command did not exit successfully apt-get update -y exit status 100
```
Does anyone know how to fix this issue?

**Comment by sammcj** [comment]
I don't think that's got anything to do with jq, that looks like your operating systems packaging mirror.
