### ISSUE TITLE
`id` integer field showing the same value in result, when diffent in original json file.

### ISSUE THREAD

**Issue by melonaerial** [jqlang/jq#2509]
**Describe the bug**
For some json files there is strange behavior for `id` field. I see the same value in result view, but in input json file the id value are distinct. Here is the result what I see https://ibb.co/7GsQn2g  . Original json is below.
Result:
```
$ cat test_failure.json | jq
{
  "sections": [
    {
      "items": [
        {
          "id": 50000000014435120,
          "price": {
            "full": 3450
          }
        },
        {
          "id": 50000000014435120,
          "price": {
            "full": 3450
          }
        },
        {
          "id": 50000000014435120,
          "price": {
            "full": 3450
          }
        },
        {
          "id": 50000000014435120,
          "price": {
            "full": 3450
          }
        }
      ],
      "name": "cancelled"
    }
  ]
}
```

**To Reproduce**
json:
`{
  "sections": [
    {
      "items": [
        {
          "id": 50000000014435121,
          "price": {
            "full": 3450
          }
        },
        {
          "id": 50000000014435122,
          "price": {
            "full": 3450
          }
        },
        {
          "id": 50000000014435123,
          "price": {
            "full": 3450
          }
        },
        {
          "id": 50000000014435124,
          "price": {
            "full": 3450
          }
        }
      ],
      "name": "cancelled"
    }
  ]
}`

command:
`cat test_failure.json | jq`

**Expected behavior**
all id-s are different as in raw json.

**Environment (please complete the following information):**
 - Ubuntu 18.04
 -  jq-1.5-1-a5b5cbe

**Additional context**
I see this bug also in Firefox and Google Chrome. I think the use this library for preview of json.

**Comment by melonaerial** [comment]
@wader 
I think version is doesn't matter

```
$ jq --version
jq-1.5-1-a5b5cbe
$ echo 50000000014435122 | jq .
50000000014435120
```

But `id` length is matter. For `id`-s from this range  `500000000144351[2-4]` everything works fine. 
And for js console return the following:
```
Number.isSafeInteger(50000000014435112)  - false
Number.isSafeInteger(5000000001443512)    - true
```

So that's mean we use to big value for integer in json, we have to use string. I've got it. Thank you very much!

**Comment by pkoppstein** [comment]
@melonaerial - Please note that @wader is correct, in that for the preservation of literal numbers, you'll need a version of jq that is later than version 1.6, which unfortunately is still the most recent "released" version.  There are other reasons to upgrade to the latest "development" version as well.

**Comment by melonaerial** [comment]
@pkoppstein so then I will close the issue. OK?

**Comment by pkoppstein** [comment]
@melomaerial - That would be helpful. Have you been able to install a recent development version, or gojq, or ... ?

**Comment by emanuele6** [comment]
jq 1.7 released with the fix. closing
