### ISSUE TITLE
Name of MacOS binary ends in "-amd64"

### ISSUE THREAD

**Issue by Twangist** [jqlang/jq#2511]
On your download page https://stedolan.github.io/jq/download/, the name of the MacOS binary for v1.6 is "jq-osx-amd64". Apple has never used AMD CPUs, so what architecture is this binary actually for? If it really is for Macs, you should change it's misleading name.

**Comment by wader** [comment]
Yeah amd64 is a bit confusing in the context of apple hardware. I think it refers to the 64bit x86 ISA that AMD created and Intel later adopted.

**Comment by Twangist** [comment]
Makes a dim kind of sense :) But yes that clarifies — this really is a Mac binary. Do reconsider the filename, though.

**Comment by itchyny** [comment]
Understandable request in the point view of strictness, but I close the issue as many existing famous tools do the same. Considering these famous tools (written in Go) adopts the naming, we know what it means, and I don't think it is misleading.

- [cli/cli](https://github.com/cli/cli) (32.8k stars) [v2.32.0](https://github.com/cli/cli/releases/tag/v2.32.0) `GitHub CLI 2.32.0 macOS amd64`
- [derailed/k9s](https://github.com/derailed/k9s) (21.6k stars) [v0.27.4](https://github.com/derailed/k9s/releases/tag/v0.27.4) `k9s_Darwin_amd64.tar.gz`
- [argoproj/argo-cd](https://github.com/argoproj/argo-cd) (13.6k stars) [v2.7.8](https://github.com/argoproj/argo-cd/releases/tag/v2.7.8) `argocd-darwin-amd64`
