### ISSUE TITLE
is it possible to insert key value from 2nd array into 1st

### ISSUE THREAD

**Issue by chrismccoy** [jqlang/jq#2513]
Not sure if this is possible.

```
  "questions": [
    {
      "season": 1,
      "episode": 1,
      "question": "what is the name of the character played by Michael Richards?"
    }
  ],
  "episodes": [
    {
      "season": 1,
      "episode": 1,
      "title": "The Seinfeld Chronicles"
    },
    {
      "season": 1,
      "episode": 2,
      "title": "The Stake Out"
    }
  ]
```

looking to insert 2nd array title, if it matches the season and episode of 1st array

so it would add "title": "The Seinfeld Chronicles" to the questions array for season1 and episode1.

**Comment by wader** [comment]
Hey, maybe something like, not super efficient but seems to work
```
. as {$episodes} | .questions[] |= (. as $q | $episodes[] | select($q.episode==.episode and $q.season==.season) | $q+{title})
```
But i would suggest asking on stackoverflow

**Comment by chrismccoy** [comment]
> . as {$episodes} | .questions[] |= (. as $q | $episodes[] | select($q.episode==.episode and $q.season==.season) | $q+{title})

cool thanks, anyway to insert the title into the 3rd position? before the question?
