### ISSUE TITLE
Generate array always for specified xml element

### ISSUE THREAD

**Issue by ajit4sbi** [jqlang/jq#2514]
- Generate array always for specified xml element **"aitem"** even with single set . 
- It must open square braces as an array like aitem[{}] 
- Please also specify expression to write in /.jq file as a def, to maintain many single set items to be an array. 
 
```
<root>
    <aitem>
        <name>abc</name>
        <value>123</value>
    </aitem>
    <bitem>
        <name>bbbb</name>
        <value>2222</value>
    </bitem>
    <bitem>
        <name>BB</name>
        <value>22</value>
    </bitem>
</root>

```

### Normal Output aitem{} bitem[{}{}]

```
 {
  "root": {
    "aitem": {
      "name": "abc",
      "value": "123"
    },
    "bitem": [
      {
        "name": "bbbb",
        "value": "2222"
      },
      {
        "name": "BB",
        "value": "22"
      }
    ]
  }
}
```

### Expected Output , aitem[{}] bitem[{}{}] even its single set aitem must become array

```
{
  "root": {
    "aitem": [
    {
      "name": "abc",
      "value": "123"
    }
    ],
    "bitem": [
      {
        "name": "bbbb",
        "value": "2222"
      },
      {
        "name": "BB",
        "value": "22"
      }
    ]
  }
 }
```

**Comment by wader** [comment]
Hi, seems unrelated to jq. Did you mean to open an issue for https://github.com/kislyuk/yq, https://github.com/mikefarah/yq or https://github.com/wader/fq etc? but maybe you can post-process the JSON, something like `walk(if type == "object" then with_entries(.value |= if type == "object" then [.] end) end)` produces:
```json
{
  "root": [
    {
      "aitem": [
        {
          "name": "abc",
          "value": "123"
        }
      ],
      "bitem": [
        {
          "name": "bbbb",
          "value": "2222"
        },
        {
          "name": "BB",
          "value": "22"
        }
      ]
    }
  ]
}
```

**Comment by ajit4sbi** [comment]
@wader ,Thanks for your attention

yes i tried converting xml to json with yq first, helpful if you can provide solution for same within YQ

I am trying to process with JQ for proper json

Can we do xml>json conversion & serialize json with FQ , 

Do any of the YQ, JQ, FQ packages do conversion & serialize output based on XML or JSON schema

Please correct my command or how can i use same in definition file

> jq 'walk(if type == "object" then with_entries(.value |= if type == "object" then [.] end) end)' test.json

**Comment by wader** [comment]
Not sure about yq, and not sure which one of the two named yq your using. But with fq you can do:
```shell
$ fq 'walk(if type == "object" then with_entries(.value |= if type == "object" then [.] end) end)' test.xml
{
  "root": [
    {
      "aitem": [
        {
          "name": "abc",
          "value": "123"
        }
      ],
      "bitem": [
        {
          "name": "bbbb",
          "value": "2222"
        },
        {
          "name": "BB",
          "value": "22"
        }
      ]
    }
  ]
}
# and you can manipulate the json and get xml back as the values follow the xml<->json mapping rules
$ fq -r '.root.bitem += [{hello: 123}] | to_xml({indent:2})' test.xml
<root>
  <aitem>
    <name>abc</name>
    <value>123</value>
  </aitem>
  <bitem>
    <name>bbbb</name>
    <value>2222</value>
  </bitem>
  <bitem>
    <name>BB</name>
    <value>22</value>
  </bitem>
  <bitem>
    <hello>123</hello>
  </bitem>
</root>
```

**Comment by ajit4sbi** [comment]
@wader 

Working with FQ now, Any idea can i create xsd schema files & ask FQ to do accordingly as per schema file.

Requirement as below , would need two tasks doing in single command
- I would like to specify many ".aitem, .oitem, .sitem" like single set elements to be an array
- convert all numbers/floats/booleans to be without double quoted

**Comment by wader** [comment]
Hi, fq does not support decoding to json based on xsd at the moment, don't know if one of the yq:s does. It's not something i plan on adding myself at the moment, but feel free to work on it.
