### ISSUE TITLE
Old version under https://stedolan.github.io/jq/download/linux64/jq

### ISSUE THREAD

**Issue by fabb** [jqlang/jq#2518]
**Describe the bug**
https://stedolan.github.io/jq/download/linux64/jq points to an old version of jq (1.4).

**To Reproduce**
Click the link and check the version number with `./jq --version`

**Expected behavior**
The link should probably point to the latest version

**Environment (please complete the following information):**
Not relevant

**Additional context**
Maybe the version number here does not get correctly updated? https://github.com/stedolan/jq/blob/master/docs/site.yml#L7

**Comment by itchyny** [comment]
You can download the latest release version from https://github.com/jqlang/jq/releases/latest/download/jq-linux64 (and a like for other architectures).
