### ISSUE TITLE
Export bookmarks from Chrome to a directory structure

### ISSUE THREAD

**Issue by Evantage-WS** [jqlang/jq#2524]
Hi,

Is there a way with bash and jq to loop thru all the bookmarks of Chrome (~/Library/Application\ Support/Google/Chrome/Default/Bookmarks) and create the same logical structure on disk? 

So a folder in Chrome will become a folder on disk with the bookmarks of that chrome folder as a json file?

Thanks

**Comment by wader** [comment]
No pretty but i've used the technique of outputting shell commands from jq and pipe it to 'sh', so something like this:
```
jq -r '.roots.bookmark_bar | [.name,.] | recurse(. as [$path,$root] | $root | .children[]? | select(.type=="folder") | ["\($path)/\(.name)",.]) | . as [$path,{$children}] | @sh "mkdir -p \($path)", ($children[] as {$type,$name,$url} | select($type=="url") | @sh "echo \($url) > \($path)/\($name)")' path/to/Bookmarks
```
Will output `mkdir -p folder/path` for each folder, `echo url > folder/path/name` for each url.

But be aware of filenames with slashes etc probably needs some care.

**Comment by Evantage-WS** [comment]
Hi @wader,

Thanks for your reply and work. Just tried it, looks good, but I am wondering how to do get the directories and files created, because present it does not on my Macos

**Comment by wader** [comment]
You mean how to run the commands? i usually do something like:
```
jq ... | sh -x
```
Then `sh` will run each command, `-x` is to see each command before running it.

But please inspect the commands before running them.

**Comment by Evantage-WS** [comment]
Thanks, I will try that!
