### ISSUE TITLE
Using INDEX with stream doesn't work

### ISSUE THREAD

**Issue by wojteklu** [jqlang/jq#2528]
**Describe the bug**

I'm trying to transform array to object by specific key. It works fine without using stream, but not possible when stream is applied.

**To Reproduce**

How to reproduce:

Data:
```
[
  {
    "id": "1",
    "userId": "fa51531d"
    }
    ,
    {
    "id": "2",
    "userId": "a167869a"
  }
]
```

Command:
```
jq -n --stream 'fromstream(1|truncate_stream(inputs)) |  INDEX(.id)' test.json > result.json
```

**Expected behavior**

Data above should be transformed to:

```
{
  "1": {
    "userId": "fa51531d",
    "id": "1"
  },
  "2": {
    "userId": "a167869a",
    "id": "2"
  },
}
```

**Environment (please complete the following information):**
 - OS and Version: macOS
 - jq version 1.6

**Additional context**

I want to achieve the same result as with

> jq 'INDEX(.id)'

but using stream (because of big JSON file).

**Comment by wader** [comment]
Hey, maybe you want  the `INDEX(stream; index_expression)` variant?
```shell
$ jq -n --stream 'INDEX(fromstream(1|truncate_stream(inputs)); .id)' test.json
{
  "1": {
    "id": "1",
    "userId": "fa51531d"
  },
  "2": {
    "id": "2",
    "userId": "a167869a"
  }
}
```
