### ISSUE TITLE
gsub not works while or lookahead and normal pattern

### ISSUE THREAD

**Issue by fish2bird** [jqlang/jq#2532]
**Describe the bug**

I want output capture pattern if matched else empty
example input
```
not a cd cmd
cd /ok
```

I want extract `/ok` which follows `cd `, and replace invalid lines to empty, expected
```
""
"/ok"
```

my try is `jq -nR 'inputs|gsub("^(?!cd ).*$|^cd "; "")'`
`^(?!cd ).*$` works, `^cd ` also works, but failed while out them together.

**To Reproduce**
```

[root build]#(echo "not a cd cmd"; echo "cd /ok") | ./jq -nR 'inputs|gsub("^cd "; "")'
"not a cd cmd"
"/ok"
[root build]#(echo "not a cd cmd"; echo "cd /ok") | ./jq -nR 'inputs|gsub("^(?!cd ).*$"; "")'
""
"cd /ok"
[root build]#(echo "not a cd cmd"; echo "cd /ok") | ./jq -nR 'inputs|gsub("^(?!cd ).*$|^cd "; "")'
""
""

```

**Expected behavior**

jq works likes perl
```
[root build]#(echo "not a cd cmd"; echo "cd /ok")
not a cd cmd
cd /ok
[root build]#(echo "not a cd cmd"; echo "cd /ok") | perl -pe 's/^(?!cd ).*$|^cd //g'

/ok
[root build]#
```

**Environment (please complete the following information):**
 - OS: CentOS 7
 - jq version: jq-1.6

**Additional context**

**Comment by pkoppstein** [comment]
Use sub, not gsub.  `gsub` interprets ^ naively.

**Comment by chencang1980** [comment]
> Use sub, not gsub. `gsub` interprets ^ naively.

```
[root build]#(echo "not a cd cmd"; echo "cd /ok") | ./jq -nR 'inputs|sub("^(?!cd ).*$|^cd "; ""; "")'
""
"/ok"
```

But, My final aim is to replace multi occurrences in a line,  
for example `cd  asdf;  cd bbbb; cd ddd`  to `asdf;bbbb;ddd`

I also checked `sub(pattern; tostring;  "g")`, which failed as gsub
```
[root build]#(echo "not a cd cmd"; echo "cd /ok") | ./jq -nR 'inputs|sub("^cd "; ""; "g")'
"not a cd cmd"
"/ok"
[root build]#(echo "not a cd cmd"; echo "cd /ok") | ./jq -nR 'inputs|sub("^(?!cd ).*$"; ""; "g")'
""
"cd /ok"
[root build]#(echo "not a cd cmd"; echo "cd /ok") | ./jq -nR 'inputs|sub("^(?!cd ).*$|^cd "; ""; "g")'
""
""
```

**Comment by pkoppstein** [comment]
@chencang1980 wrote:

> My final aim is to replace multi occurrences in a line

So if you want to use jq, you'll either have to write your own gsub or choose a different parsing strategy.  How about splitting on the ';'?

**Comment by chencang1980** [comment]
> you'll either have to write your own gsub or choose a different parsing strategy

Thank you, My final workaround is capture + sed:

```
make_to_compile_commands_json ()
{
    make --always-make --dry-run \
        | grep -wE '^(cd .* && )?/?(\w+/)*(gcc|g\+\+|cc|c\+\+) .*-c ' \
        | ${JQ_PATH:-jq} -nR '[inputs|capture("^(cd (?<directory>.*) && )?(?<command>.* (?<file>[^ \\t]+))$")]' \
        | sed -e 's/: null,$/: ".",/g' \
        > compile_commands.json
}
```

There may be many traps in `sub/gsub`, whose document just say as PCRE......
Will document change or code change?

**Comment by itchyny** [comment]
Inaccurate documentation about PCRE was raised by #2439 before. No PR fixing this was created though.

**Comment by pkoppstein** [comment]
@itchyny - This issue (specifically `jq -nR 'inputs|gsub("^(?!cd ).*$|^cd "; "")'`) is resolved by PR https://github.com/jqlang/jq/pull/2624
