### ISSUE TITLE
https://jqplay.org/ Has this site been taken down?

### ISSUE THREAD

**Issue by hectoralicea** [jqlang/jq#2537]
https://jqplay.org/ 
Has this site been taken down?

**Comment by wader** [comment]
Sorry no idea, but check https://github.com/owenthereal/jqplay/issues/131

**Comment by runofthemill** [comment]
Not mine, but found https://jqkungfu.com/ as an alternative

**Comment by owenthereal** [comment]
https://jqplay.org is back online now. The reason was due to the underlying service provider.
