### ISSUE TITLE
Provide ARM Docker Image

### ISSUE THREAD

**Issue by siemendev** [jqlang/jq#2539]
Hi folks!
I love using "stedolon/jq" as a docker image, since we work in teams with win/mac/linux systems both on amd64 and arm64 architectures (at least the linux and mac guys). Using the docker image provides me the flexibility to use it in our makefiles for the environment setup without having to add another required installed software on the host.

Since the mac has rosetta, we can easily use the amd64 image as well. Linux on the other hand cannot use the amd64 image:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /usr/local/bin/jq: exec format error
```

So could you please consider adding more architectures (at least arm64) to the docker image?

Heres a little help on how to build for other architectures using qemu: https://drpdishant.medium.com/multi-arch-images-with-docker-buildx-and-qemu-141e0b6161e7

**Comment by wader** [comment]
Hi, the project is a bit stalled at the moment, see #2305
