### ISSUE TITLE
Incorrect formatting when piping from `kubectl exec`

### ISSUE THREAD

**Issue by CAJan93** [jqlang/jq#2552]
**Describe the bug**

Piping the result of of my `kubectl exec` into `jq .` is formatted incorrectly. I do not get this error if I first pipe the output to a file or `echo` the output. 
<img width="1529" alt="Screenshot 2023-03-07 at 18 21 21" src="https://user-images.githubusercontent.com/15103784/223499660-2fc3ec60-f297-4259-8cb0-0b0f7cf4cd6d.png">

**Expected behavior**

I would expect that this output would always be formatted correctly 

**Environment (please complete the following information):**
 - OS and Version: macOS 12.6
 - jq version: jq-1.6 
 - iTerm2: Build 3.4.19
 - etcdctl version: 3.5.6
 - etcdctl API version: 3.5

**Comment by wader** [comment]
Hi, that is a bit strange. Could you try `k exec ... | 2> stderr 1> stdout` and see if something fishy is written to stderr?

**Comment by itchyny** [comment]
You are attaching TTY in the command but that looks unnecessary. Drop `-t` flag (`-i` flag looks unused too) will fix the issue.
