### ISSUE TITLE
One example under Regular expressions (PCRE) doesn't work

### ISSUE THREAD

**Issue by hansonchar** [jqlang/jq#2558]
**Describe the bug**

Under [Regular expressions (PCRE)](https://stedolan.github.io/jq/manual/v1.6/#RegularexpressionsPCRE):

>Note that certain flags may also be specified within REGEX, e.g.
> *   jq -n '("test", "TEst", "teST", "TEST") | test( "(?i)te(?-i)st" )'
>
>evaluates to: true, true, false, false.

However, it resulted in failure using `jq-1.6`:

```jq
$ jq -n '("test", "TEst", "teST", "TEST") | test( "(?i)te(?-i)st" )'
jq: error (at <unknown>): Regex failure: invalid group name <>
```
**Expected behavior**

The example should work.

**Environment (please complete the following information):**
 - OS and Version: [e.g. macOS, Windows, Linux (please specify distro)]
 
 ```bash
$ jq --version
jq-1.6

$ uname -a
Darwin ... 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64
```

**Comment by wader** [comment]
I wonder if this could be some regression in oniguruma and it used to work? using `(?i-i)` seem to work:
```sh
$ jq -n '("test", "TEst", "teST", "TEST") | test( "(?i)te(?i-i)st")'
true
true
false
false
```

For what i can see jq does not do much with the regex more then passing it as an argument:
https://github.com/stedolan/jq/blob/cff5336ec71b6fee396a95bb0e4bea365e0cd1e8/src/builtin.c#L890

**Comment by hansonchar** [comment]
Should the `manual.yaml` files be updated to use `?i-i` instead of `?-i`?

* [manual](https://github.com/stedolan/jq/blob/master/docs/content/manual/manual.yml#L2331)
* [v1.6 manual](https://github.com/stedolan/jq/blob/master/docs/content/manual/v1.6/manual.yml#L2240)
* [v1.5 manual](https://github.com/stedolan/jq/blob/master/docs/content/manual/v1.5/manual.yml#L1994)

Or do you think this is a bug in `oniguruma` that should be fixed?  What is the expected behavior/syntax anyway?  Where is it specified?

**Comment by wader** [comment]
> Should the `manual.yaml` files be updated to use `?i-i` instead of `?-i`?

No it was mostly a workaround i found accidentally :) but it seem to indicate there might be something fishy with the oniguruma flag parsing code. Maybe we can come up with an alternative example if it turns out to be a oniguruma bug and even if it's fixed it might be confusing?

> 
> * [manual](https://github.com/stedolan/jq/blob/master/docs/content/manual/manual.yml#L2331)
> * [v1.6 manual](https://github.com/stedolan/jq/blob/master/docs/content/manual/v1.6/manual.yml#L2240)
> * [v1.5 manual](https://github.com/stedolan/jq/blob/master/docs/content/manual/v1.5/manual.yml#L1994)
> 
> Or do you think this is a bug in `oniguruma` that should be fixed? What is the expected behavior/syntax anyway? Where is it specified?

Not sure but i tried to install an old verison of jq and indeed it seems to work fine:
```
$ docker run --rm -ti debian:stretch sh -c 'apt-get update && apt-get -y install jq && jq -n "\"abc\" | test(\"(?-i)\")"'
...
Unpacking jq (1.5+dfsg-1.3) ...
Setting up libonig4:amd64 (6.1.3-2+deb9u2) ...
Setting up libjq1:amd64 (1.5+dfsg-1.3) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up jq (1.5+dfsg-1.3) ...
true
```

So maybe try reproduce the error with just oniguruma and if so report it upstream? could possibly be that it has already been fixed but i didn't find anything obvious related to in the commit log

**Comment by hansonchar** [comment]
I locally built and tested `oniguruma` latest master branch at commit `e35581d`, and it appears to support `(?-i)`.

I then locally built and tested `jq` latest master branch at commit `cff5336` which also works ie it supports `(?-i)`.

So this seems a problem specific to `jq-1.6`.

**Comment by hansonchar** [comment]
Furthermore this problem appears to affect the `jq` on `OSX` and `Ubuntu`, but not `AL2` (Amazon Linux):

## OSX

```
$ jq -n '("test", "TEst", "teST", "TEST") | test( "(?i)te(?-i)st" )'
jq: error (at <unknown>): Regex failure: invalid group name <>

$ jq --version
jq-1.6

$ otool -L $(which jq)
/usr/local/bin/jq:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
	/usr/local/opt/oniguruma/lib/libonig.5.dylib (compatibility version 6.0.0, current version 6.0.0)

$ uname -a
... Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64
```

## AL2

```
$ jq -n '("test", "TEst", "teST", "TEST") | test( "(?i)te(?-i)st" )'
true
true
false
false

$ jq --version
jq-1.5

$ ldd $(which jq)
	linux-vdso.so.1 (0x00007ffe8b1d2000)
	libjq.so.1 => /usr/lib64/libjq.so.1 (0x00007f06e7c26000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00007f06e78e6000)
	libonig.so.2 => /usr/lib64/libonig.so.2 (0x00007f06e767f000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007f06e72d2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f06e7e6b000)

$ uname -a
Linux ... 5.4.235-151.344.amzn2int.x86_64 #1 SMP Sat Mar 11 23:51:58 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

## Ubuntu (Ubuntu 20.04.5 LTS)

```
$ jq -n '("test", "TEst", "teST", "TEST") | test( "(?i)te(?-i)st" )'
jq: error (at <unknown>): Regex failure: invalid group name <>

$ jq --version
jq-1.6

$ ldd $(which jq)
ldd $(which jq)
	linux-vdso.so.1 (0x00007fff4ebf3000)
	libjq.so.1 => /lib/x86_64-linux-gnu/libjq.so.1 (0x00007ffac7e39000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffac7c47000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffac7af8000)
	libonig.so.5 => /lib/x86_64-linux-gnu/libonig.so.5 (0x00007ffac7a69000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffac7ea7000)

$ uname -a
Linux ... #66~20.04.1-Ubuntu SMP Wed Jan 25 09:41:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hansonchar** [comment]
The suspect is the shared library with names that start with `libonig.5`, such as `libonig.5.dylib` on OSX and `libonig.so.5` on Ubuntu.  

Weird.

**Comment by wader** [comment]
@hansonchar 👍 nice oniguruma debugging and bug report
