### ISSUE TITLE
invalid gmtime representation for 1970-01-01T00:59:59Z

### ISSUE THREAD

**Issue by adrium** [jqlang/jq#2567]
**Describe the bug**

`"1970-01-01T00:59:59Z"` can not be parsed with `fromdate` or `fromdateiso8601`

**To Reproduce**

    $ echo '"1970-01-01T00:59:59Z"' | jq fromdate
    jq: error (at <stdin>:1): invalid gmtime representation

**Expected behavior**

    $ echo '"1970-01-01T00:59:59Z"' | jq fromdate
    3599

**Environment (please complete the following information):**
 - OS and Version: macOS 13.3
 - jq version 1.6

**Comment by adrium** [comment]
Seems like a mac bug, it works in linux... Not sure what's the root cause, though

**Comment by pkoppstein** [comment]
It's not a Mac bug, at least not when running 12.6.1.  E.g.
```
$ echo '"1970-01-01T00:59:59Z"' | jq-1.5 fromdate
3599

$ echo '"1970-01-01T00:59:59Z"' | ~/Downloads/jq/jq-1.6 fromdate
3599
```

**Comment by itchyny** [comment]
It works well for me on macOS, confirmed both 1.6 and the master version.
