### ISSUE TITLE
FAQ have obsolete link for jq.alhur.es/finder/ 

### ISSUE THREAD

**Issue by sputnick-dev** [jqlang/jq#2581]
The page https://github.com/stedolan/jq/wiki/FAQ have wrong link for https://jq.alhur.es/finder/ - a multi-result-column `jq` explorer and query builder.

The project seems abandoned.

Is there any other query builder like this to replace from FAQ?.

**Comment by itchyny** [comment]
Not sure about replacement tool, but the link has been removed last month at [this change](https://github.com/jqlang/jq/wiki/_compare/b0b9c028a985707cb1a9cd259bff10c8df3c07e3...c7002c58ffa61e066c9625b95e1802a890706324), so closing the issue.
