### ISSUE TITLE
--exit-status returns 0 for empty string when trying to expand array and selecting for value

### ISSUE THREAD

**Issue by heinosasshallik** [jqlang/jq#2583]
**Describe the bug**

When you have an empty list and you use `select()` to search for a value in that list, then jq correctly returns and error code when using the `--exit-status` flag. However, when you do the same for an empty string, jq returns 0.

**To Reproduce**

Jq working as expected with an empty list:

```
└─[$]> echo "[]" | jq --exit-status '.[] | select(.test == "test")'; echo $?
4
```

But returning exit code 0 with an empty string:

```
└─[$]> echo "" | jq --exit-status '.[] | select(.test == "test")'; echo $?    
0
```

**Expected behavior**

I would expect it to return an error code

```
└─[$]> echo "" | jq --exit-status '.[] | select(.test == "test")'; echo $?    
4
```

**Environment (please complete the following information):**
 
 ```
 └─[$]> lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

```
└─[$]> jq --version                                                 
jq-1.6
```

**Comment by itchyny** [comment]
This issue is already resolved in the latest version (ref: #1142, #1697).
