### ISSUE TITLE
Editor Bindings for Gedit/GtkSourceView

### ISSUE THREAD

**Issue by XHawk87** [jqlang/jq#2587]
I've started on a language definition file for Gedit/GtkSourceView: https://github.com/XHawk87/gtksourceview-jq-definition

It's in a very rough state at the moment. I'm hoping for some help from some other interested parties in bringing it up to standard.

**Comment by wader** [comment]
Hi, these might be interesting:

Syntax grammar used by my [vscode-jq](https://github.com/wader/vscode-jq) extension, have used it for a long time with few problems: https://github.com/wader/vscode-jq/tree/master/syntaxes

Repo and syntax used by [github linguist](https://github.com/github-linguist/linguist) to highlight jq code on github: https://github.com/wader/language-jq

Also the grammar by @fadado has been useful to me https://github.com/fadado/JBOL/blob/master/doc/JQ-language-grammar.md

And of course the lexer/parser in stedolan/jq, gojq etc are useful resources also.
