### ISSUE TITLE
Can't get jq to install.

### ISSUE THREAD

**Issue by suzuki-reha** [jqlang/jq#2597]
**Describe the bug**
Since May 29, 2023 curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x . Trying to install jq binary with /jq but getting 404.
I confirm that I was able to install until May 26, 2023.

**To Reproduce**
I only get a 404 error page when I run the following command
curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x . /jq

**Expected behavior**
When executing the following command, the jq binary should be able to be retrieved
curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x . /jq

**Environment (please complete the following information):**
 - OS and version: MacOS (13.3.1 (a) (22E772610a), Ubuntu
 - jq version [1.5, 1.6].

**Comment by wader** [comment]
Hi jq has recently moved, you can find binaries here https://jqlang.github.io/jq/download/

Where did you find the https://stedolan.github.io/jq/download/linux64/jq URL? only page i can find with it is https://aws.amazon.com/jp/blogs/news/introducing-fine-grained-iam-roles-service-accounts/

**Comment by suzuki-reha** [comment]
This URL has been in use in the existing environment for about a year and I do not know where you got it from.
Once it was downloaded from the following URL.
https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64

Thanks for the info.

**Comment by itchyny** [comment]
We transferred the repository recently, but due to the difficulty of redirecting non-HTML file in GitHub Pages, the executable has been removed from the new repository. You can get the executable from the URL you mentioned, and also from https://github.com/jqlang/jq/releases/latest/download/jq-linux64 which redirects to the latest release.

**Comment by suzuki-reha** [comment]
@itchyny 
Thank you for the informative state of affairs.

**Comment by wader** [comment]
@suzuki-reha Ok thanks. Was mostly curious from where the link was found in the first place as i could not find a similar one at the new location. But @itchyny figured out that the binary was removed in https://github.com/jqlang/jq/commit/d08a76eb5e498a3660a7d9d88f3e43ac0fbfb820

**Comment by KrishnaPayyavula** [comment]
@itchyny , We also facing the same issue, our pipeline setup is downloading the executable from the source https://stedolan.github.io/jq/download/linux64/jq.

But I don't know where I got the link from.

**Comment by nicowilliams** [comment]
> @itchyny , We also facing the same issue, our pipeline setup is downloading the executable from the source https://stedolan.github.io/jq/download/linux64/jq.
> 
> But I don't know where I got the link from.

That _used to be_ the correct link.  It stopped being the correct link when `stedolan/jq` moved to `jqlang/jq` -- that happened recently.  I'm not sure how to get GitHub to make that link a redirect.
