### ISSUE TITLE
Need a GitHub Actions workflow that builds jq.1.prebuilt, the website, and mantests

### ISSUE THREAD

**Issue by nicowilliams** [jqlang/jq#2691]
We need a GitHub Actions workflow that builds `jq.1.prebuilt`, `jq.1`, the website (as a tarball), and mantests, and then makes a GitHub release of those artifacts so we can:

- manually update `jq.1.prebuilt` in the source tree and commit it
- manually update `tests/man.test` in the source tree and commit it
- manually update the `gh_pages` from the website tarball

**Comment by itchyny** [comment]
When we update the manual files, we need to update `jq.1.prebuild` and `tests/man.test` to make the PR status green #2697.
The website is automatically updated by Github Actions #2603.
What's missing?

**Comment by emanuele6** [comment]
I guess what is missing is a bot that automatically generates `jq.1.prebuilt`, `parser.c`, etc after a PR is merged, but do we really wan that?

**Comment by nicowilliams** [comment]
No, let me close this.
