### ISSUE TITLE
add case-insensitive options/variants for various string functions

### ISSUE THREAD

**Issue by liquidaty** [jqlang/jq#2721]
anything having to do with searching, sorting, splitting, `startswith`, `endswith`, `ltrimstr`, `rtrimstr`, etc would benefit from having a case-insensitive option.

in some of these cases, case-insensitivity can be emulated in a somewhat trivial manner-- for example, if I want to remove any ".csv" suffix a case-insensitive manner, I can assign the lower-cased value to a variable, then check if that saved variable ends with ".csv", and if so chop the length of the target suffix (4 chars) off the back of the original value. But even in these cases, the workaround is klunky and requires a complex representation for a simple concept.

however, in other cases, such as `split`, a workaround is not very feasible (or reasonably straightforward).

Having a case-insensitive alternative for these-- whether a different function name such as `startswith_i` or an additional parameter, or some other manner-- would be convenient, clean and elegant.

**Comment by itchyny** [comment]
Using `i` flag with regex filters `test/2`, `sub/3`, and `split/2` cover these use cases. Could you explain why you don't use these filters?

**Comment by liquidaty** [comment]
Oh nice! Apologies, my mistake, my initial use case was for `rtrimstr` and I did not realize those options existed for test/sub/split. Are there similar options for `startswith`, `endswith`, `ltrimstr`, `rtrimstr `?

**Comment by itchyny** [comment]
I mean case-insensitive `rtrimstr` can be achieved by `sub("str$"; ""; "i")` and `startswith` by `test("^str"; "i")`.

**Comment by liquidaty** [comment]
aahh, I see thank you. That is helpful.

I still think a more "layperson" solution, that would not require regex and anchors to get case-insensitivity, would be of value (more so for my target user base than myself at least-- for example, I could totally see the user trying `sub(".csv$";...)` and getting confused+frustrated due to the period not behaving like a literal period, or perhaps not knowing that the dollar sign anchor needs to be there to ensure the match is at the end);

but, given the regex alternatives, that incremental value is definitely lower and less important than I had thought when I first opened this issue

**Comment by itchyny** [comment]
I suspect case-insensitive option can also have variations. Case-insensitive option of regex filters allows each characters to be either upper or lower case, but in your use case you may want to trim either .csv or .CSV but not .CsV or .cSV (I guess). This can be achieved by `sub("\\.(?:csv|CSV)"; "")`. I'm not against the need for simpler solutions for beginners, but I think regex filters are flexible enough to cover various use cases.

**Comment by nicowilliams** [comment]
Case-insensitivity is a real pain, as we saw on the utf8proc PR :)

I'm very much inclined to leave case-insensitivity to Oniguruma!  :)

**Comment by liquidaty** [comment]
In that case I'd at least suggest adding to the documentation for functions such as `rtrimstr`. Currently, a user looking up that function will find no indication that there is any way to achieve case-insensitivity, unless that user happens to already be familiar with the regex functions and then is clever enough to the workaround themselves (which clearly I was not, and I think I'm probably not much less savvy as your average jq user) (and FWIW after several tries with chatGPT-4 just now, it also could not figure out a solution that worked...)

**Comment by pkoppstein** [comment]
@liquidaty wrote:

> adding to the documentation 

From the context, it seems you are suggesting adding usage guidelines to the jq Manual in particular, so I'd like to point out that the Manual serves a central role as a relatively succinct but readable, authoritative description of jq, and to preserve its integrity and ensure it continues to play that role effectively, it's important to avoid bloat.
There are other places on the jqlang website for additional information - the Tutorial, FAQ, Cookbook, Tips, etc.  

Many users in any case prefer to get usage information from sources such as stackoverflow.com, no matter what's in the manual :-(

**Comment by itchyny** [comment]
I added the docs label, but also think that we don't need to document on this topic, so closing this issue. But still, you can send us a PR and we'll review soon.
