### ISSUE TITLE
Multiple conditions in a single select filter

### ISSUE THREAD

**Issue by nkrishnakishor** [jqlang/jq#2725]
I'm trying run multiple conditions in a single select filter but I'm getting wrong out.

Data is as below

```

{
  "List1": [
    {
      "List2": [
        {
          "Key1": "value1",
          "Key2": "value2",
          "Key3": "value3",
          "Key4": "value4"
        },
        {
          "Key1": "value5",
          "Key2": "value6",
          "Key3": "value7",
          "Key4": "value8"
        }
      ]
    }
  ]
}
```

Running the query as `jq '.List1[].List2[] | select(.Key1 != "value11" and .Key2 == "value2")'`

I get the output as below which should not be the case, it should return null output since there is no such data.

```
{
  "Key1": "value5",
  "Key2": "value6",
  "Key3": "value7",
  "Key4": "value8"
}
```

I'm doing something wrong ?

**Comment by emanuele6** [comment]
If you run that query with that input, you don't get that output.
You get only the first object, not the second:
```
{
  "Key1": "value1",
  "Key2": "value2",
  "Key3": "value3",
  "Key4": "value4"
}
```

And you get that because it has `"Key1":"value1"` and `"Key2":"value2"`, which verifies your condition. `"value1" != "value11"` and `"value2" == "value2"`.

Maybe you typoed `value11` instead of `value1`.

**Comment by pkoppstein** [comment]
Closing as this Q was asked at https://stackoverflow.com/questions/76709596/multiple-conditions-in-a-single-select-filter, where an explanation was given.  The OP can continue seeking help at stackoverflow.com easily enough.
