### ISSUE TITLE
Merging on matching nested keys

### ISSUE THREAD

**Issue by CrossNox** [jqlang/jq#2734]
I'm trying to use a json as a "template" to fill with another with a similar structure. This can also be seen as merging without adding new keys only present on the right side:

The "template" looks as follows:
```json
{
  "a": "",
  "b": {
    "b1": 0,
  }
}
```

And the json with values looks as follows:
```json
{
  "a": "A",
  "c": 3,
  "b": {
    "b1": 101,
    "b2": 102
  }
}
```

For which I expect the output to be like:
```json
{
  "a": "A",
  "b": {
    "b1": 101,
  }
}
```

Object multiplication (`echo $template $values | jq -s '.[0] * .[1]'`) would return:
```json
{
  "a": "A",
  "c": 3,
  "b": {
    "b1": 101,
    "b2": 102
  }
}
```

,which adds unwanted keys.

I haven't been able to figure it out, with nested keys.

**Comment by nicowilliams** [comment]
```bash
: ; jq --slurpfile v values.json '$v[0] as $v | reduce (path(..|scalars)) as $p (.; setpath($p; $v|getp
ath($p)))' template.json
{
  "a": "A",
  "b": {
    "b1": 101
  }
}
```

This iterates through all the paths to scalar values in the template and replaces those with the corresponding value (which need not be a scalar) at the same path in the values source.

**Comment by nicowilliams** [comment]
Feel free to re-open if you have more questions.  Consider using the #jq channel on Libera Chat IRC for support questions.
