### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by flobee** [jqlang/jq#2770]
This is a bug in communication 

it does also a 'lint' job for testing own json files without a '--lint' check parameter. cool :+1: 

```
jq file
```

tell the world in readme or documentition so search engins will index informations. 
only a simple hint at stackoverflow.... i found.

**Comment by nicowilliams** [comment]
It may be a language issue, but I don't understand what you're asking for.

**Comment by flobee** [comment]
> It may be a language issue, but I don't understand what you're asking for.

i wanted to ask for --lint option

but it is already in :-)

but  search engins shows other options which give a hint to this project for a solution.
its just missing in the docs that this program will report "lint" aspects.

e.g: https://duckduckgo.com/?q=how+to+lint+a+json+string+in+bash

**Comment by emanuele6** [comment]
I think you meant to use `jq . file` instead of `jq file`.

**Comment by flobee** [comment]
> I think you meant to use `jq . file` instead of `jq file`.

yes!
`cat ./faulty.json | jq` does it also

it is obvious that this program must be able to do this kind of thing.
but if you search for a 'lint' for json it gets rather weird

**Comment by emanuele6** [comment]
Well, closing then.

**Comment by nicowilliams** [comment]
@flobee I strongly recommend you include the `.` argument.

**Comment by flobee** [comment]
> This is a bug in communication

pls add it to the docs. so you/ this project can be found easy if one is just in shell context and is looking for a solution.
.
