### ISSUE TITLE
Using `-f` with a file that has no main program can assume the main program is `.`, or produce an incorrect error

### ISSUE THREAD

**Issue by nicowilliams** [jqlang/jq#2785]
See #2353.

Reproducer:

```
$ printf 'def a: 0;\n' > m.jq
$ jq -n -f m.jq
null
$ printf 'def a: 0;\ndef b: a;' > m.jq
$ jq -n -f m.jq
jq: error: a/0 is not defined at <top-level>, line 2:
def b: a;
jq: 1 compile error
$ 
```

What's happening is that if there's no main program in the file specified with `-f` then jq assumes `.`, but probably does not bother fully-linking the jq code in that file, then it detects that there are unbound symbols and produces an error.

What should happen: it should always be an error to use `-f` with a jq program file that has no main program.

**Comment by pkoppstein** [comment]
@nicowilliams wrote:
>  it should always be an error to use -f with a jq program file that has no main program.

Why must it be an *error*?  It's convenient for testing a bunch of defs to be able to write `jq -n -f FOO.jq`. 
Admittedly, one can always tack on `empty` or some such, but why introduce the backward incompatibility (**relative to jq 1.6**), not to mention the hassle?

"Nothing will come of Nothing."

**Comment by nicowilliams** [comment]
> Why must it be an *error*?  It's convenient for testing a bunch of defs to be able to write `jq -n -f FOO.jq`. 

Just add `.`, or `empty`, or whatever you like at the end.

> Admittedly, one can always tack on `empty` or some such, but why introduce the backward incompatibility (**relative to jq 1.6**), not to mention the hassle?

It doesn't work reliably as you yourself noted.  Therefore we're free to "break" backwards compatibility, except it's more making it do the obviously correct thing (and consistently at that) that matches the documentation anyways.  Why should jq invent a main program because the user didn't?  We've already had enough trouble with doing that when stdout is a tty and stdin is a pipe, and I want no more of that trouble.

You'll get used to it, I'm sure :)  It's really not a big deal.  And it's more a big deal (for me or whoever would volunteer their time) to make it work the way you want.

**Comment by pkoppstein** [comment]
> It's really not a big deal.

Agreed, a message that no main program was found would not be very horribly terrible, but:

(1) many other interpreters adhere to "Nothing will come of Nothing", e.g.
```
$ echo "" | python3
$ perl -E ''
$ echo '' | js
$ julia <(echo "")
$ echo "" | ruby
$ echo "" | sqlite3
$ echo "" | bash
$ bash -c ""
$ awk -f <(echo "")
$ Rscript <(echo "")
$ php <(echo "")

$ jq-1.6  -n -f <(echo "")
null
```
And for fun:
```
$ echo "" > empty.c
$ gcc -c empty.c
$ gfortran -c empty.c
$ crystal empty.c
$
```

(2) the argument from lack-of-time fails as a reason for adding a new requirement that it must be an error.

But I'll try very hard to refrain from saying more on the topic, except perhaps to add to the listing above :-)

**Comment by nicowilliams** [comment]
@pkoppstein we're trying to get a release done.  Noise does not help.  Until 1.7 is released please keep your contributions to the absolute necessary for that release -- if it's not necessary, then please hold off until after.

**Comment by julien-braure** [comment]
First thanks for `jq`, this is a useful tool, but when you say 

> ... It's really not a big deal. ...

I tend to disagree with that as this "non-backward compatible" change just broke our production...

The fix is indeed simple, we just added a `.` , but still you changed behavior, fixing one usage to, sadly, break another one which was functionnal
