### ISSUE TITLE
Sign new release key with the old key -- or just rename the old release key and keep using it

### ISSUE THREAD

**Issue by nicowilliams** [jqlang/jq#2812]
See subject.  Changing the release key might be a bit surprising.  Maybe it's best to keep using the old one.

Either way let's do this before the 1.7 release.

**Comment by itchyny** [comment]
Do you keep the old private key?

**Comment by nicowilliams** [comment]
> Do you keep the old private key?

I'm looking...  If I can't find it, maybe @stedolan still has it.

**Comment by nicowilliams** [comment]
I've not found it.
