### ISSUE TITLE
Add command-line option to show build options used to build jq

### ISSUE THREAD

**Issue by nicowilliams** [jqlang/jq#2816]
It would be nice to have a command-line option by which to show the `./configure` build options used to build jq.  Or perhaps a digested version of that, like if Oniguruma was used from the sub-module, whether stack protection features were enabled (and which), etc.

**Comment by nicowilliams** [comment]
See #1514.

**Comment by itchyny** [comment]
I feel `--config` is unsuitable option, maybe `--version-debug`, `--version-verbose` or something else. I know vim exposes compilation/linking options in `--version`, but I don't like to expose the information of build environment honestly.

**Comment by nicowilliams** [comment]
How about `--build-configuration`?

**Comment by itchyny** [comment]
Sounds good.
