### ISSUE TITLE
Will not find a key

### ISSUE THREAD

**Issue by rpatchet** [jqlang/jq#2830]
**Describe the bug**

I search for a specific key in a Postman download JSON file, which has an enclosing .collection object. If unfamiliar, Postman has recursive `.item` array of objects. Within `.item` can be keys such as `.name`, `.protocolProfileBehavior` (a recent addition), `.request`, and `.response` (array). I try to find `.item` objects that have both a `.request` and a `.protocolProfileBehavior` where the latter also has a `.followRedirects` as seen in this excerpt:
```
"protocolProfileBehavior": {
  "disableBodyPruning": true,
  "followRedirects": false
},
```

This filter returns nothing:
`jq -c '.collection | recurse( .item[]? ) | select( .request and .protocolProfileBehavior.followRedirects ) | { "name": .name, "flag": .protocolProfileBehavior }'`

This filter returns a line for each of the 729 requests in the original file:
`jq -c '.collection | recurse( .item[]? ) | select( .request and .protocolProfileBehavior.disableBodyPruning ) | { "name": .name, "flag": .protocolProfileBehavior }'`

The first three lines of that output are:
```
{"name":"Read External Authentication Initialization","flag":{"disableBodyPruning":true,"followRedirects":false}}
{"name":"Read External Authentication Callback","flag":{"disableBodyPruning":true,"followRedirects":false}}
{"name":"Read External Authentication Status","flag":{"disableBodyPruning":true}}
```

As you can see, the first two also contain "followRedirects" yet the first filter will not find them.

**To Reproduce**

This excerpt contains just the three requests shown in the sample output above.

[GitHub-sample.json.zip](https://github.com/jqlang/jq/files/12280774/GitHub-sample.json.zip)

**Expected behavior**

Using the sample file with the first filter, I expect that objects in the `.item` array that have both a `.request` object and a `.protocolProfileBehavior` object, where the latter contains `followRedirects`, appear:
```
{"name":"Read External Authentication Initialization","flag":{"disableBodyPruning":true,"followRedirects":false}}
{"name":"Read External Authentication Callback","flag":{"disableBodyPruning":true,"followRedirects":false}}
```

**Environment (please complete the following information):**

- macOS 13.5
- jq version 1.6 and 1.7rc1

**Additional context**

I encountered this with another key in the same source file, but I do not recall which key it was.

**Comment by wader** [comment]
Hi, haven't look deeper at it yet but i noticed that `followRedirects` is `false`. Maybe your looking for `(. protocolProfileBehavior | has("followRedirects"))` or possibly check that it is `true` or `false`?

**Comment by nicowilliams** [comment]
`jq -c '.collection | recurse( .item[]? ) | select( .request and .protocolProfileBehavior.followRedirects ) | { "name": .name, "flag": .protocolProfileBehavior }'` so you want only requests that have `.protocolProfileBehavior.followRedirects` set to `true`, but the ones you show don't:

```JSON
{"name":"Read External Authentication Initialization","flag":{"disableBodyPruning":true,"followRedirects":false}}
{"name":"Read External Authentication Callback","flag":{"disableBodyPruning":true,"followRedirects":false}}
{"name":"Read External Authentication Status","flag":{"disableBodyPruning":true}}
```

- the first and the second objects above has `.flag.followRedirects` set to `false`
- the last one doesn't have `.flag.followRedirects` set at all
- your jq code doesn't refer to `.flag` either

**Comment by rpatchet** [comment]
The main issue here is that jq finds the key "disableBodyPruning" with just `.protocolProfileBehavior.disableBodyPruning`, but not its peer "followRedirects" with the same filter condition pattern `.protocolProfileBehavior.followRedirects`.

The condition `.protocolProfileBehavior.followRedirects == false` works, but obviously finds only `false`.

I can find the key with the filter condition of `( .protocolProfileBehavior | has( "followRedirects" ) )`, but that is beside the point. The filter condition `.protocolProfileBehavior.followRedirects` should work on every key in an object.

**Comment by wader** [comment]
Not sure i follow what you mean by "The filter condition `.protocolProfileBehavior.followRedirects` should work on every key in an object". Do you the expression should check if the `.protocolProfileBehavior` object has a `followRedirects` key regardless of its value? if so, then that is not how it works. `select` is the thing that does do actual filtering here and you give it an expression that is the condition that should be true for it to "passthru" the input.

Note that all `disableBodyPruning` is `true` in the example file so that is why `select(.protocolProfileBehavior.disableBodyPruning)` "works".

**Comment by nicowilliams** [comment]
Can you post a full JSON text?  Feel free to redact it of private data, of course.

**Comment by rpatchet** [comment]
@nicowilliams 
I understand my error! I should have understood this. I have only been using jq for about a year and have a long way to go to understand all its features.

As described in [if-then-else-end](https://jqlang.github.io/jq/manual/v1.6/#if-then-else-end). using `.protocolProfileBehavior.followRedirects` alone tells jq to evaluate the the key for `false` or `null`. This successfully tests for the existence of `.request` because it is an object and therefore is only null (logical false) or not-null (logical true). However, I failed to recognize that `followRedirects` is a boolean and is `false` in the JSON. Amazingly, it evaluates to `false` - d'oh!!! 

My apologies for posting something that should have been obvious. I use jq nearly every day and love it.

**Comment by wader** [comment]
@rpatchet no worries! also good to know is that you can index into `null` and it returns `null`, so `null | .a[1].b.c` is `null` ...and bonus trivia you can also assign to `null`, `null | .a = 1` is `{a:1}`, and it becomes an object or array.
