### ISSUE TITLE
map_values + tonumber? not working properly

### ISSUE THREAD

**Issue by kassio** [jqlang/jq#2841]
**Describe the bug**

Input:

```json
{"b":"01","d": "10","a": "a"}
```

**To Reproduce**

- `tonumber` or fallback (https://jqplay.org/s/kx9mfd3zR8F):

```jq
map_values(. | tonumber? // .)
```

Returns the only not-number value

```json
{"a":"a"}
```

- `try . | tonumber` or fallback (https://jqplay.org/s/nCSUa4gNC9u):
 
```jq
map_values(. as $value | try (. | tonumber) catch $value)
```

Returns all strings

```json
{"b":"01","d":"10","a":"a"}
```

**Expected behavior**

I'd expected it to perform the same way as (https://jqplay.org/s/dJ49rJJo9lX):

```jq
. | to_entries | map({key: .key, value: (.value | tonumber? // .)}) | from_entries
```

returns the same object format with possible numbers as numbers, not numbers unchanged:

```json
{"b":1,"d":10,"a":"a"}
```

**Environment (please complete the following information):**

- OS and Version: Macos (13.5 (22G74)), JQplay
- jq version `jq-1.6`

**Additional context**

**Comment by emanuele6** [comment]
This was already reported by other people, and it is fixed in master; it is also fixed in `jq-1.7rc1`! \o/
