### ISSUE TITLE
[Feat Req]Stop parsing once query is found

### ISSUE THREAD

**Issue by cipri-tom** [jqlang/jq#2864]
**Describe the ~~bug~~ Feature**
I have a LAAARGE json file (271 MB). I do some sanity queries against it, requiring a first item of the first key. Something like : 

```
$ time jq '.images[0]' train/Annotations/iSAID_train-fixed.json
{
  "id": 0,
  "file_name": "P0000.png",
  "ins_file_name": "P0000_instance_id_RGB.png",
  "seg_file_name": "P0000_instance_color_RGB.png",
  "width": 3875,
  "height": 5502
}
real	0m6.959s
user	0m6.146s
sys	0m0.812s
$ 
```
Where `'images'` is the first key:

```
{"images":[{"id":0,"file_name":"P0000.png","ins_file_name":"P0000_instance_id_RGB.png","seg_file_name":"P0000_instance_color_RGB.png","width":3875,"height":5502},{"id":1,"file_name":"P0001.png","ins_file_name":"P0001_instance_id_RGB.png","seg_file_name":"P0001_instance_color_RGB.png","width":1252,"height":5774},{"id":2,"file_name":"P0002.png", 
...
```

**To Reproduce**
Pick/generate any similarly large file. The one I'm using is hosted here: https://drive.google.com/drive/folders/19RPVhC0dWpLF9Y_DYjxjUrwLbKUBQZ2K?usp=sharing

**Expected behavior**

While impressively fast for this file, `jq` still takes 7 seconds to display the result. I imagine that if I was streaming this file, it would be even slower, waiting to get the entirety of it.

I would like to have a way to stop parsing as soon as my query is found / achieved.

**Environment (please complete the following information):**

- OS and Version: Ubuntu 18.04
- jq version : jq-1.6

Thank you  ! 

**Additional context**

I understand that I would give up correctness verification, i.e. if the JSON suddenly ends without closing all the objects, it would not be detected. Because of this, I imagine this feature would be behind a switch, so that I'm explicit that  _I know what I'm doing ™️_.

**Comment by wader** [comment]
Your probably looking for `--stream` https://jqlang.github.io/jq/manual/#streaming

Something like this if you looking for a specific path. If you want to whole object it gets a bit more complicated.
```sh
$ jq --stream -n 'first(inputs as [$p,$v] | select($p == ["images",0,"file_name"]) | $v)' iSAID_train.json
"P0000.png"
```

`first/1` makes jq stop after first match

**Comment by cipri-tom** [comment]
Ohh, thank you ! I should have read the docs in more detail, to learn about `--stream`.

But wow, I would have never come up with that expression for selecting just a part. Thank you, I'll read more about it

**Comment by wader** [comment]
👍 I noticed now that there is some things written in the wiki about streaming and big inputs https://github.com/jqlang/jq/wiki/Cookbook#processing-huge-json-texts might be useful

**Comment by emanuele6** [comment]
@wader It's not that much more complicated :)
```jq
first(fromstream(inputs |select(first[:3] == [ "images", 0, "file_name" ]) | del(first[:3])))
```
See: https://github.com/jqlang/jq/issues/2847#issuecomment-1679778275

**Comment by nicowilliams** [comment]
One annoying thing is that `--stream` is not fast.  @pkoppstein has pointed this out in the past, and I've not gotten around to figuring out why.  In principle it ought to be much faster.

**Comment by wader** [comment]
> @wader It's not that much more complicated :)
> 
> ```jq
> first(fromstream(inputs |select(first[:3] == [ "images", 0, "file_name" ]) | del(first[:3])))
> ```
> 
> See: [#2847 (comment)](https://github.com/jqlang/jq/issues/2847#issuecomment-1679778275)

Aha yes that is nice. Have only read but not used `fromstream` myself yet 👍  i'm guessing you meant `[:2]`?
```jq
$ jq --stream -n 'first(fromstream(inputs | select(first[:2] == [ "images",0]) | del(first[:2])))' iSAID_train.json
{
  "id": 0,
  "file_name": "P0000.png",
  "ins_file_name": "P0000_instance_id_RGB.png",
  "seg_file_name": "P0000_instance_color_RGB.png"
}
```

**Comment by emanuele6** [comment]
@wader It should match the length of the path; in my example I had `[ "images", 0, "file_name" ]` like in your previous comment, so `[:3]`; if you have `[ "images", 0 ]`, then you should use `[:2]`.

**Comment by cipri-tom** [comment]
Managed to test this today. The speed of it is ... 🤯 instant ! Thank you !

**Comment by wader** [comment]
@cipri-tom 👍 ... but i guess i won't be that instant if the match very late in the stream :)
