### ISSUE TITLE
JQ syntax editor/plugin for jetbrains products

### ISSUE THREAD

**Issue by chb0github** [jqlang/jq#2869]
This is a feature request for support and integration with jetbrains editorsfor jq syntax. Jetbrains offers a plugin framework for such things, and it would be a great way to further support the jq community:

Specifically:
1. Syntax highlighting
2. syntax error/validation
3. debug

Perhaps a new repo for the effort, so it can grow independently. I recognize this doesn't specifically align to this repo, but I saw no where else to publish the request

**Comment by wader** [comment]
If it supports LSP there is https://github.com/wader/jq-lsp which i use for https://github.com/wader/vscode-jq which also has example of grammar for syntax highlighting.

**Comment by nicowilliams** [comment]
> If it supports LSP there is https://github.com/wader/jq-lsp which i use for https://github.com/wader/vscode-jq which also has example of grammar for syntax highlighting.

My goodness, you wrote a language server for jq?!  That's awesome!

**Comment by nicowilliams** [comment]
> If it supports LSP there is https://github.com/wader/jq-lsp which i use for https://github.com/wader/vscode-jq which also has example of grammar for syntax highlighting.

We should link this from the README!

**Comment by wader** [comment]
Currently the installation of both jq-lsp and vscode-jq is not very polished, no packing and i'm not sure it even works on windows :). Maybe we could for now add some section to the wiki with development support stuff?

btw have you seen https://github.com/fiatjaf/awesome-jq? maybe could cherry pick some stuff from there also
