### ISSUE TITLE
leaf_path ignores nodes with boolean value `false`

### ISSUE THREAD

**Issue by ershov** [jqlang/jq#2872]
## Describe the bug

leaf_path ignores nodes with boolean value `false`

## To Reproduce

[jqplay snippet](https://jqplay.org/s/4gCy5dVoMJb) or run:

```bash
$ echo '{"asd": 5, "qwe": false, "zxc": true}' | jq 'leaf_paths'
```

Output:

```json
[
  "asd"
]
[
  "zxc"
]
```

## Expected behavior

`leaf_paths` should return all leafs:

```json
[
  "asd"
]
[
  "qwe"
]
[
  "zxc"
]
```

## Environment (please complete the following information):

- OS and Version: macOS, jqplay website
- jq version: jq-1.6 and the same at jqplay

**Comment by nicowilliams** [comment]
Thank you for this report!  Yes, this is a bug.

The bug is in `paths/1`, which is defined as

```jq
def paths(node_filter): . as $dot|paths|select(. as $p|$dot|getpath($p)|node_filter);
```

but should have been:

```jq
def paths(node_filter): . as $dot|paths|select(. as $p|$dot|getpath($p)|node_filter|true);
```

**Comment by emanuele6** [comment]
@nicowilliams No.

At most the bug is that `leaf_paths` was incorrectly implemented as `paths(scalars)` instead of `paths(scalars | true)`.

`leaf_paths` was already marked as deprecated in jq 1.6, and it has been removed in master.

**Comment by nicowilliams** [comment]
@emanuele6 ay, I need more caffeine today.

**Comment by emanuele6** [comment]
```
  s      O    O
  s        L
c[_]     \____/
```

**Comment by ershov** [comment]
Hey thanks everyone for your replies.
Are you sure that removing `leaf_paths` is a good idea? It's going to break a lot of code. (Although fixing it might do that too)

**Comment by nicowilliams** [comment]
> Are you sure that removing `leaf_paths` is a good idea? It's going to break a lot of code. (Although fixing it might do that too)

I'm not sure it was a good idea, but `leaf_paths` was marked as obsolete in 1.6 so we're able to allow ourselves to remove it.
