### ISSUE TITLE
jq1.7 `latest` asset names used in 1.6 release not found (404)

### ISSUE THREAD

**Issue by suzuki-reha** [jqlang/jq#2877]
**Describe the bug**
The latest (currently 1.7) jq from the URL "https://github.com/jqlang/jq/releases/latest/download/jq-linux64" does not install. (`status:404`)
Until yesterday the latest 1.6 was downloaded.  

1. Execute "https://github.com/jqlang/jq/releases/latest/download/jq-linux64
2. Redirect to "https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux64" but page returns 404

**To Reproduce**
When I run the URL "https://github.com/jqlang/jq/releases/latest/download/jq-linux64" in my browser, nothing is downloaded.

**Expected behavior**
The latest version (currently, 1.7 is the latest) should be downloaded when the URL "https://github.com/jqlang/jq/releases/latest/download/jq-linux64" is executed in a browser.

**Environment (please complete the following information):**
- OS and Version: all
- jq version [1.7]

**Comment by nicowilliams** [comment]
> **Describe the bug** The latest (currently 1.7) jq from the URL "https://github.com/jqlang/jq/releases/latest/download/jq-linux64" does not install. (`status:404`) Until yesterday the latest 1.6 was downloaded.

Oh, interesting.  I don't know how to make `latest` work.  ~Any ideas?~

This does work, of course: https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux-amd64

EDIT: Ah, this link works https://github.com/jqlang/jq/releases/latest/download/jq-linux-arm64

The issue is that we didn't keep the asset name `jq-linux64`.  We didn't because we now produce executables for Linux on more ISAs.

**Comment by nicowilliams** [comment]
We could restore the `jq-linux64` name for backwards compatibility with things that expected that name so they could download jq, ~but we'd have to do a new version release for that~.

**Comment by nicowilliams** [comment]
Can you update your docker files or scripts to use https://github.com/jqlang/jq/releases/latest/download/jq-linux-arm64 ?

**Comment by bc-rajesh** [comment]
Similar issue. We are using the circleci jq orb circleci/jq@2.2.0 and using it to install the latest version of jq. 
This tries to get the latest version https://github.com/stedolan/jq/releases/download/jq-1.7/jq-linux64 and then redirected to https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux64 but returns 404.

The circleci JQ orb needs to be updated as well

**Comment by TaeJung-Shim** [comment]
I've also encountered an error while using a different library. 
(https://github.com/stefanprodan/kube-tools/blob/master/src/install.sh)
Is there any way to keep the previous URL?

**Comment by butyear** [comment]
I've also encountered an error while using a different library. 
(https://github.com/stefanprodan/kube-tools/blob/master/src/install.sh)
Is there any way to keep the previous URL?

**Comment by nicowilliams** [comment]
~I think I'd have to redo the 1.7 release to do what you're asking for, or else do a 1.7.1 release.~

I added a `jq-linux64` asset that' a copy of the `jq-linux-amd64` asset.

**Comment by nicowilliams** [comment]
I've added

 - `jq-linux32` as the same as `jq-linux-i386`
 - `jq-linux64` as the same as `jq-linux-amd64`
 - `jq-osx-amd64` as the same as `jq-macox-amd64`
 - `jq-win32.exe` as the same as `jq-windows-i386.exe`
 - `jq-win64.exe` as the same as `jq-windows-amd64.exe`

and I've

 - updated `sha256sum.txt` accordingly.

I've **not** _yet_ fixed the GitHub Actions CI workflows to do the same.  Maybe that should be a separate issue and for the next release.

**Comment by suzuki-reha** [comment]
@nicowilliams 
Thank you for your prompt response.

**Comment by itchyny** [comment]
I strongly recommend to migrate to the new URLs with explicit architecture in executable names, because we may not fix this in the next release.
