### ISSUE TITLE
jq version has a "dirty" suffix

### ISSUE THREAD

**Issue by mjarosie** [jqlang/jq#2886]
**Describe the bug**

Not sure if it's a bug or just my misinterpretation of the output, but the new `jq` has a "dirty" suffix, should that be the case?

**To Reproduce**

Download the latest version of `jq`, then run:

```
$ jq-win64.exe --version
```

Produces:
```
jq-1.7-dirty
```

**Expected behavior**

That should probably just print `jq-1.7`.

**Environment (please complete the following information):**

- OS and Version: Windows
- jq version 1.7

**Additional context**

I have noticed it when testing an update of the [Chocolatey package](https://community.chocolatey.org/packages/jq) that I maintain.

**Comment by nicowilliams** [comment]
Huh, yes, I see that, but I don't see what's different about the GitHub Actions CI workflow build for Linux vs. Windows that would cause this.
