### ISSUE TITLE
`shtest` failure due to use of non-existent `script -n` option

### ISSUE THREAD

**Issue by jpalus** [jqlang/jq#2887]
**Describe the bug**
`shtest` fails:
```console
+ command -v script
+ unset NO_COLOR
+ >/dev/null 
+ 2>&1 
+ script -qc echo /dev/null
+ >/tmp/B.6gmfnxqd/BUILD/tmp/jq7IllHp/color 
+ faketty /tmp/B.6gmfnxqd/BUILD/jq-1.7/jq -n .
+ script -q /dev/null /tmp/B.6gmfnxqd/BUILD/jq-1.7/jq -n . /dev/null
+ sed 's/^\x5E\x44\x08\x08//'
script: invalid option -- 'n'
Try 'script --help' for more information.
+ >/tmp/B.6gmfnxqd/BUILD/tmp/jq7IllHp/expect 
+ printf '\033[0;90mnull\033[0m\r\n'
+ od -c /tmp/B.6gmfnxqd/BUILD/tmp/jq7IllHp/expect
0000000 033   [   0   ;   9   0   m   n   u   l   l 033   [   0   m  \r
0000020  \n
0000021
+ od -c /tmp/B.6gmfnxqd/BUILD/tmp/jq7IllHp/color
0000000
+ cmp /tmp/B.6gmfnxqd/BUILD/tmp/jq7IllHp/color /tmp/B.6gmfnxqd/BUILD/tmp/jq7IllHp/expect
cmp: EOF on /tmp/B.6gmfnxqd/BUILD/tmp/jq7IllHp/color which is empty
+ clean
+ true
+ '[' -n /tmp/B.6gmfnxqd/BUILD/tmp/jq7IllHp ']'
+ rm -rf /tmp/B.6gmfnxqd/BUILD/tmp/jq7IllHp

+ exit 1
```

**To Reproduce**
Run `make check` with `script` implementation from `util-linux 2.39.2`.

**Expected behavior**
Tests pass.

**Environment (please complete the following information):**

- OS and Version: PLD Linux
- jq version 1.7

**Additional context**
`faketty` function uses `script`:
https://github.com/jqlang/jq/blob/7a72f58d2e92254652162ec7ca1b3074e3a22c35/tests/shtest#L511-L516

And then is invoked with `-n` option that is passed down to `script`:
https://github.com/jqlang/jq/blob/7a72f58d2e92254652162ec7ca1b3074e3a22c35/tests/shtest#L518

However `util-linux` implementation does not recognize `-n` option and, as far as I can tell, it never did:
https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/tree/term-utils/script.c#n770

**Comment by jpalus** [comment]
Ah sorry, `script` was being misdetected as one from macos due to issue on my side. Sorry for confusion.

**Comment by nicowilliams** [comment]
```bash
faketty $JQ_NO_B -n . > $d/color
```

The `-n` here is not for `script` via `faketty` but for `jq` via `$JQ_NO_B` :)
