### ISSUE TITLE
jq 1.6 doesn't show version on alpine...still? again?

### ISSUE THREAD

**Issue by ingernet** [jqlang/jq#2890]
**Describe the bug**
Running `jq --version` on Alpine only returns `--`. It's possible that the Alpine distro of `jq` has never supported the `--version` flag, but that seems like a very un-UNIX-y thing to do....

Running this in a `bash` shell, in a Docker container using this image:  `gcr.io/google.com/cloudsdktool/google-cloud-cli:445.0.0-alpine`

`jq` version: jq-1.6-r3 x86_64
Installation method: `apk add --no-cache jq~=1.6`

Command and Output:
```
$ jq --version
jq--
```

**To Reproduce**
```
# fire up docker
$ docker run -it --name jq_versioning  gcr.io/google.com/cloudsdktool/google-cloud-cli:445.0.0-alpine /bin/bash

# install jq
fde80b4fbaa4:/# apk add --no-cache jq~=1.6

# query it for version
fde80b4fbaa4:/# jq --version
```

**Expected behavior**
I would expect it to output the version. For reference, in MacOS, here's what I get:
```
$ jq --version
jq-1.6
```

**Environment (please complete the following information):**

- OS and Version: Alpine Linux 3.18.2
- jq version: jq-1.6-r3 x86_64

**Additional context**
There was [another issue](https://github.com/jqlang/jq/issues/1566) opened about this years ago, closed without fix because of a miscommunication about the OS.

**Comment by wader** [comment]
And seem to still be a problem with alpine edge which has jq 1.7
```sh
$ docker run --rm -ti alpine:edge sh -c 'apk add jq && jq --version'
Unable to find image 'alpine:edge' locally
edge: Pulling from library/alpine
b790c763077d: Pull complete
Digest: sha256:f2d1645cd73c7e54584dc225da0b5229d19223412d719669ebda764f41396853
Status: Downloaded newer image for alpine:edge
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/2) Installing oniguruma (6.9.8-r1)
(2/2) Installing jq (1.7-r0)
Executing busybox-1.36.1-r6.trigger
OK: 9 MiB in 17 packages
jq-
```

Build log for 1.7 https://build.alpinelinux.org/buildlogs/build-edge-x86/main/jq/jq-1.7-r0.log (has a `GEN      src/version.h` log and don't see any errors or warnins)
APKBUILD file https://git.alpinelinux.org/aports/tree/main/jq/APKBUILD

**Comment by wader** [comment]
I think the problem might be that it downloads the "Source code (tar.gz)" https://github.com/jqlang/jq/archive/refs/tags/jq-1.7.tar.gz which is the git tag and has no pre-generated `src/version.h`. Instead it should download https://github.com/jqlang/jq/releases/download/jq-1.7/jq-1.7.tar.gz which is the more proper source distribution with a `src/version.h`. Also in that case `autoreconf -fi` should not be needed.

**Comment by wader** [comment]
Reported upstream https://gitlab.alpinelinux.org/alpine/aports/-/issues/15261

**Comment by wader** [comment]
hmm upstream might not be the correct word... anyway :)

**Comment by wader** [comment]
Fixed https://gitlab.alpinelinux.org/alpine/aports/-/commit/d9ccfc30b07e9e859310af1d25673e56c0df3e64

**Comment by wader** [comment]
but i guess jq 1.6 will remin broken

**Comment by wader** [comment]
```
$ docker run --rm -ti alpine:edge sh -c 'apk add jq && jq --version'
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/2) Installing oniguruma (6.9.8-r1)
(2/2) Installing jq (1.7-r1)
Executing busybox-1.36.1-r6.trigger
OK: 9 MiB in 17 packages
jq-1.7
```

Close? not sure about jq in current stable alpine, my guess not worth fixing?

**Comment by kasperk81** [comment]
backport the same fix to 1.6 downstream? 
`jq-1.6.tar.gz` from https://github.com/jqlang/jq/releases/tag/jq-1.6 instead of `Source code (tar.gz)` (former has version.h).

**Comment by wader** [comment]
You mean change alpine so that the APKBUILD for 1.6 also downloads the source distribution instead of the tag tar.gz? yeah that would be good but i don't know how that work in alpine. Maybe can ask in the alpine issue i created?

**Comment by wader** [comment]
Asked here https://gitlab.alpinelinux.org/alpine/aports/-/issues/15261#note_337462

**Comment by wader** [comment]
No reply from alpine ppl. I think i will close this for now as i suspect they don't backport something like this
