### ISSUE TITLE
Open the discussions section for the project

### ISSUE THREAD

**Issue by trantor** [jqlang/jq#2891]
Hello @nicowilliams . I was thinking that enabling discussions for the project might be interesting. Thoughts?

**Comment by emanuele6** [comment]
Hello @nicowilliams :)

**Comment by owenthereal** [comment]
👍 People could even ask questions async there if they can't join our discord

**Comment by itchyny** [comment]
Someone has opened the discussions in this repository. Thanks for suggestion.
