### ISSUE TITLE
Default color of jq is indistinguishable under Solarized Light background

### ISSUE THREAD

**Issue by taoky** [jqlang/jq#2903]
**Describe the bug**
Since jq 1.7, its default color is very hard to read when using Solarized Light.

**To Reproduce**

Tilix 1.9.5, with Solarized Light color scheme.

```
> echo '{"a": 1, "b": "b", "c": [1,2,3,4,5]}' | jq .
```

![image](https://github.com/jqlang/jq/assets/2109893/68a5acca-4d8f-46e4-879f-e73bd2d0c72a)

**Expected behavior**

Clean output like jq 1.6.

**Environment (please complete the following information):**

- OS and Version: Arch Linux
- jq version 1.7

**Additional context**

~~This may be caused by https://github.com/jqlang/jq/pull/2824.~~

**Comment by itchyny** [comment]
#2824 does not change the color of numbers. Could you share the screenshot of the same command with jq 1.6?

**Comment by taoky** [comment]
jq 1.6:

![image](https://github.com/jqlang/jq/assets/2109893/54bab3bd-61fd-48f7-9a74-506d4a72951f)

I'm also bisecting jq's code and I would comment here if I have found out that commit.

**Comment by taoky** [comment]
It's https://github.com/jqlang/jq/commit/07b18a33feb6ccab08be221657e19b82abf0d84e.

**Comment by taoky** [comment]
This works correctly within Solarized Light:

```
> echo '{"a": 1, "b": "b", "c": [1,2,3,4,5]}' | JQ_COLORS="1;30:0;39:0;39:0;39:0;32:1;39:1;39" jq .
```

(Screenshot is the same as jq 1.6).

Guess that this commit should be reverted...

**Comment by taoky** [comment]
~~I'm trying to revert this commit, and it seems that directly changes "37" to "39" will make "null" indistinguishable under dark background.~~ "null" also shows badly in released jq 1.7 under Solarized Dark.

**Comment by nicowilliams** [comment]
It might be nice to have an env var that names the terminal's color scheme so we can pick a suitable color scheme.

**Comment by taoky** [comment]
> It might be nice to have an env var that names the terminal's color scheme so we can pick a suitable color scheme.

It's a bit mess as there's no universal convention about getting color scheme: https://unix.stackexchange.com/questions/245378/common-environment-variable-to-set-dark-or-light-terminal-background.

**Comment by nicowilliams** [comment]
> > It might be nice to have an env var that names the terminal's color scheme so we can pick a suitable color scheme.
> 
> It's a bit mess as there's no universal convention about getting color scheme: https://unix.stackexchange.com/questions/245378/common-environment-variable-to-set-dark-or-light-terminal-background.

Using `COLORFGBG` sounds pretty good to me.  I'm not too keen on `OSC 11` because that would be the first instance in which jq communicates with the terminal, and I'd rather not have that complexity since we can leave it to [shell-term-background](https://github.com/rocky/shell-term-background) to set `COLORFGBG` where `OSC 11` is supported and tell people to use that.
