### ISSUE TITLE
jq --version shows a -dirty suffix for 1.7 release on Windows

### ISSUE THREAD

**Issue by allxiao** [jqlang/jq#2905]
**Describe the bug**
When I download the latest 1.7 release and run `jq --version` **on Windows**, it shows a `-dirty` suffix. Checked the `-win32`, `-win64`, `-windows-i386` and `-windows-amd64` variants.

```
> jq.exe --version
jq-1.7-dirty
```

**To Reproduce**
1. Download [jq-win64.exe](https://github.com/jqlang/jq/releases/download/jq-1.7/jq-win64.exe) from the [release page](https://github.com/jqlang/jq/releases/tag/jq-1.7).
2. Run `jq-win64 --version`

**Expected behavior**
The `jq --version` command shows `jq-1.7`, which aligns with the behavior on Linux.

**Environment (please complete the following information):**

- OS and Version:  Windows 11
- jq version 1.7

**Additional context**
Linux version looks good.

**Comment by wader** [comment]
Hi, dup of https://github.com/jqlang/jq/issues/2886?
