### ISSUE TITLE
Regex improperly treats object as string following variable/try-catch usage 

### ISSUE THREAD

**Issue by ethanrowe** [jqlang/jq#2907]
Some combination of variables, try/catch, and `sub` causes loss of type information.

In a programmatically generated JQ command pipeline, I am attempting to:
* conditionally decode string inputs as JSON (pass them through unchanged if JSON decoding fails).
* conditionally perform regex substitution to remove whitespace (if non-string item, pass it through without applying `sub`).
* what I found instead is that items of type `object` were treated as `string`, and in my exploration determined it was the interaction of `sub` with early variable usage and `try ... catch`.

**To Reproduce**

Very simply, this should fail with an error, instead of outputting JSON data.

```bash
jq -n '{"foo": "bar"} | tojson | (. as $orig | try fromjson catch $orig) | sub("bogus"; "")'
```

What I get is:

```
"{\"foo\":\"bar\"}"
```

Despite the fact that `type` claims the current object at the tail of the pipeline to be `object`:

```
$ jq -n '{"foo": "bar"} | tojson | (. as $orig | try fromjson catch $orig) | type'
"object"
```

**Expected behavior**

I would expect to get an error:

```
jq: error (at <unknown>): object ({"foo":"bar"}) cannot be matched, as it is not a string
```

...which has exit code 5.

To illustrate another way, I would expect the last command in this sequence to have the same error as the preceding commands:

```
$ jq -n '{"foo": "bar"} | sub("bogus"; "")'
jq: error (at <unknown>): object ({"foo":"bar"}) cannot be matched, as it is not a string
$ jq -n '{"foo": "bar"} | tojson | fromjson | sub("bogus"; "")'
jq: error (at <unknown>): object ({"foo":"bar"}) cannot be matched, as it is not a string
$ jq -n '{"foo": "bar"} | tojson | (. as $orig | try fromjson catch $orig) | sub("bogus"; "")'
"{\"foo\":\"bar\"}"
```

**Environment (please complete the following information):**

- Linux ubuntu 20.04 LTS
- jq 1.6

**Additional context**

FWIW, it appears the use of the variable is where things go awry; if I rework the try/catch sequence to avoid variable usage, I get the expected result.

```
jq -n '{"foo": "bar"} | tojson | ({"x": ., "y": [try fromjson catch empty]} | if (.y | length > 0) then .y[0] else .x end) | sub("bogus"; "")'
```

I realize this usage probably seems a little odd.

Thanks for this incredibly useful tool.

**Comment by nicowilliams** [comment]
This is fixed in jq 1.7.
