### ISSUE TITLE
Opensuse tumbleweed - 1.7 version incorrectly printed.

### ISSUE THREAD

**Issue by danie-dejager** [jqlang/jq#2910]
**Describe the bug**
I am running OpenSuse Tumbleweed and noticed that the package `jq-1.7-1.1.x86_64` does not diplay the version correctly.
`jq -V` or `jq --version` will output
`jq-`
![Screenshot_20230925_143138](https://github.com/jqlang/jq/assets/13314239/bf65ba32-14ef-483a-a323-5619fd742411)

**Expected behavior**
correct version should be returned.

**Environment (please complete the following information):**

- OS and Version: `openSUSE Tumbleweed`
- jq version:` jq-1.7`
Current SPEC file:
https://build.opensuse.org/package/view_file/utilities/jq/jq.spec?expand=1

**Comment by wader** [comment]
Looks like dup of https://github.com/jqlang/jq/issues/2890?

**Comment by danie-dejager** [comment]
Seems the output differs slightly for Alpine. There it is `jq--` and for Tumbleweed `jq-`. #2890 was logged for 1.6 already.

**Comment by wader** [comment]
Okok hmm strange. But the tags url will not have a version.h so maybe try change the url first at least?

**Comment by nicowilliams** [comment]
It's probably how they're building it.

We should probably commit a file with the version number, much like we commit the flex and bison outputs.

**Comment by itchyny** [comment]
The source url of that spec file is the link of `Source code (tar.gz)` but should be that of `jq-1.7.tar.gz`. Anyway, this is not an issue of this repository, please report to the distributor.

**Comment by nicowilliams** [comment]
Sadly we can't delete the release artifacts that GH automatically generates.

**Comment by danie-dejager** [comment]
Logged it here:
https://bugzilla.opensuse.org/show_bug.cgi?id=1215737

**Comment by danie-dejager** [comment]
Issue was fixed in `1.7-2.1`

**Comment by wader** [comment]
For future reference, they switched to proper source distribution archive:

> Wed Sep 27 04:32:39 UTC 2023 - Andreas Stieger <andreas.stieger@gmx.de>
>  - switch to bootstrapped upstream tarball to fix version output
> [boo#1215737]
