### ISSUE TITLE
`jq -n '.57 * 100'` -> `56.99999999999999`

### ISSUE THREAD

**Issue by nicowilliams** [jqlang/jq#2923]
```bash
: ; jq -n '.57 * 100'
56.99999999999999
```

This is in fact correct because IEEE 754 doubles are like that.  But jq ought to print `57`.

**Comment by IsaacG** [comment]
Thanks for opening this for me :smile:

**Comment by itchyny** [comment]
Is this a request that calculations should keep decimal precisions or be done in rational numbers? I tested Python, Ruby, Node, and feel this is common behavior where numbers are represented in IEEE 754. An attempt to fix one side of floating-point calculation errors will lead to endless requests on numerical precisions.

**Comment by nicowilliams** [comment]
C (`printf()`) rounds up correctly:

```bash
: ; cat d.c
#include <stdio.h>

int
main(void)
{
   double d = .57;

   printf("%lf\n", d * 100);
   return 0;
}
: ; cc d.c
: ; ./a.out
57.000000
: ;
```

Python does not, indeed:

```Python
Python 3.9.7 (default, Jun 22 2022, 20:11:26)
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> d = .57
>>> print(d * 100)
56.99999999999999
>>>
```

Ruby doesn't either:

```Ruby
irb(main):004:0> d = 0.57
=> 0.57
irb(main):005:0> print d * 100
56.99999999999999=> nil
irb(main):006:0>
```

Node doesn't:

```Node
Welcome to Node.js v12.22.5.
Type ".help" for more information.
> d = 0.57
0.57
> d * 100
56.99999999999999
>
```

**Comment by nicowilliams** [comment]
I believe rounding up is the convention for this case, though clearly it's not a universal convention.

**Comment by emanuele6** [comment]
In what case? If the result ends with `.99999999999999`? What if that is the actual result? Aribtrarily special casing `.99999999999999` does not sound great.

In your C code, the number is printed as `57.000000` only because `%f` is short for `%.6f` so it is being rounded to 6 fractional digits. (Also note that `l` is ignored by `%f`; `%f` takes `double`s by default).
If you use something like `%.40f`, it will print `56.9999999999999928945726423989981412887573`.

**Comment by nicowilliams** [comment]
`%.15g` -> `57`, `%.16g` -> `56.99999999999999`.

**Comment by nicowilliams** [comment]
Maybe we just need a `printf`-alike for jq (ugh).

**Comment by emanuele6** [comment]
Yes, and/or maybe there could be an output processing option like `--number-precision 6` that will format all numbers as `%.6f` before printing them out.

But I don't think that really addresses this report. What is wanted here really is arbitrary precision. Which is probably not really worth having since most programs that parse JSON will parse them as IEEE 754 anyway, and it is common for programming languages to not be that precise with real numbers.

**Comment by nicowilliams** [comment]
> Yes, and/or maybe there could be an output processing option like `--number-precision 6` that will format all numbers as `%.6f` before printing them out.

Sure.  We'd have to add arguments to `jvp_dtoa_fmt()` and its callers (and ultimately we'd need a `tojson/1` that takes an object with output settings).  (Or make that a global variable, but it's not ok to use globals like that in a library.)  It's doable.

> But I don't think that really addresses this report. What is wanted here really is arbitrary precision. Which is probably not really worth having since most programs that parse JSON will parse them as IEEE 754 anyway, and it is common for programming languages to not be that precise with real numbers.

@IsaacG can tell us what would address the report, but it's got to be either arbitrary precision or different display settings.  Re: arbitrary precision I agree that that's a lot of work and probably not worthwhile -- if you want to do high-precision numerical analysis, then jq is too slow anyways and you might as well not use jq for that.  So we're only likely to go for better control over display -- your `--number-precision` and a `tojson/1`.

**Comment by IsaacG** [comment]
I don't have a strong opinion here. Different display settings sounds like a reasonable approach to me.

**Comment by emanuele6** [comment]
But what would be the use case?

**Comment by nicowilliams** [comment]
The use case has to be masking the inadequacies of IEEE 754 :) which in this case have to do with base-2 vs base-10 representation.

Arbitrary precision _binary_ floating point numbers would still have this problem.  The problem is that us pesky humans use base 10, not base 2.  So if we wanted to address this on a more fundamental level we'd want to make jq use an arbitrary precision decimal floating point library.  But then base 10 also can't represent fractions like ⅓ so... what we really need is an arbitrary precision rational number library.

**Comment by IsaacG** [comment]
My use case would be wanting to be able to do `jq '.57 * 100'` and getting output `57`.

**Comment by emanuele6** [comment]
That description of a use case can only suggest that you want arbitrary precision for aesthetic reasons.

Simply passing `--number-precision 6` to your `jq` won't make it arbitrarily precise, it will just round numbers more agressively and hide some imprecision.

So, adding `--number-precision` *for only that reason*, would only be adding an option that users can use to tediously (having to pass a long option to every `jq` command, or having to write a wrapper shell function or script to do that) only partially address the problem they want to solve.
