### ISSUE TITLE
Missing version number in 1.7

### ISSUE THREAD

**Issue by andrew-schulman** [jqlang/jq#2927]
**Describe the bug**
I built jq 1.7 in Cygwin. The build succeeds, but when I run `jq --version`, the output is just `jq-`, instead of `jq-1.7`.

**To Reproduce**
1. Build and install jq 1.7.
2. Run `jq --version`.

**Expected behavior**
```
$ jq --version
jq-1.7
```

**Observed behavior**
```
$ jq --version
jq-
```

**Environment (please complete the following information):**

- Cygwin 3.4.9
- jq 1.7, built from source

**Additional context**
I can fix the problem either by running `make VERSION=1.7`, or by applying this patch:
```
diff '--color=auto' -urN a/Makefile.in b/Makefile.in
--- a/Makefile.in   2023-09-06 16:00:52.000000000 -0400
+++ b/Makefile.in   2023-10-12 09:17:19.472262000 -0400
@@ -757,7 +757,7 @@
 @ENABLE_ERROR_INJECTION_TRUE@libinject_errors_la_SOURCES = src/inject_errors.c
 @ENABLE_ERROR_INJECTION_TRUE@libinject_errors_la_LIBADD = -ldl
 @ENABLE_ERROR_INJECTION_TRUE@libinject_errors_la_LDFLAGS = -module
-generate_ver = ver="`{ $(srcdir)/scripts/version || echo '$(VERSION)' ; } | sed 's/.*/\#define JQ_VERSION \"&\"/'`"
+generate_ver = ver="`{ $(srcdir)/scripts/version || echo '$(PACKAGE_VERSION)' ; } | sed 's/.*/\#define JQ_VERSION \"&\"/'`"
 CLEANFILES = src/version.h .remake-version-h src/builtin.inc \
    src/config_opts.inc jq.1
 jq_SOURCES = src/main.c src/version.h
```

**Comment by wader** [comment]
Hi, could this be dup of #2890? that the cygwin build is based on a github tag tar.gz instead of the dist tar.gz file?

Hmm did it work to change to `PACKAGE_VERSION` i can't see that we pass any version to `AM_INIT` or how does that work?

**Comment by andrew-schulman** [comment]
It does seem similar to #2890, but not exactly the same. I built from the release file, jq-1.7.tar.gz, not a git tag.

**Comment by wader** [comment]
Ok! yes then it sounds like something different. So does it for some reason re-generate the version.h file (and fails?) even when it should not be needed?

Trying to understand what is going on here https://github.com/jqlang/jq/blob/master/Makefile.am#L103-L111

**Comment by andrew-schulman** [comment]
Yes, it is regenerating version.h. Apparently the test at line 108 is failing, because `$(VERSION)` is empty in line 106. So if I run `make VERSION=1.7`, or change `$(VERSION)` to `$(PACKAGE_VERSION)` in line 106, the problem is fixed.

**Comment by itchyny** [comment]
What is the commands you used to build? You don't need to autoreconf.

**Comment by andrew-schulman** [comment]
I used the standard Cygwin build procedure for autotools, which amounts to
```
autoreconf
configure
make
```
If I take out the autoreconf, then yes, the version number is there as expected:
```
$ jq --version
jq-1.7
```

**Comment by itchyny** [comment]
As explained in README.md [here](https://github.com/jqlang/jq#instructions), don't do `autoreconf` on building from the release tarball.
