### ISSUE TITLE
1 test fails in jq 1.7 on Cygwin

### ISSUE THREAD

**Issue by andrew-schulman** [jqlang/jq#2928]
**Describe the bug**
I built jq-1.7 in Cygwin. When I run `make test`, all of the tests succeed except `tests/shtest`. The part that fails is this:
```
$ printf '1\n' | jq -cen --seq '[inputs] == []'
assertion "cb == jq_util_input_next_input_cb" failed: file "/home/ASchulma/dev/cygwin/jq/jq-1.7-1.x86_64/src/jq-1.7/src/util.c", line 381, function: jq_util_input_get_position
```

**Environment (please complete the following information):**
- Cygwin 3.4.9
- jq 1.7, built from release file jq-1.7.tar.gz

**Comment by wader** [comment]
Looks like #2822 and #2848 are related to this

**Comment by andrew-schulman** [comment]
Oh. Yes, this is a dup of #2822. Sorry about that. Closing.
