### ISSUE TITLE
`strftime`'s month are 0-based indexed instead of 1-based indexed

### ISSUE THREAD

**Issue by SamuelLarkin** [jqlang/jq#2929]
# Describe the bug
`strftime`'s month is offset by one.

# Info
## man pages
```sh
man strftime
```
```
...
%m     The month as a decimal number (range 01 to 12).  (Calculated from tm_mon.)
...
```
## Wikipeida
According to [Wikipedia.org/ISO_8601](https://en.wikipedia.org/wiki/ISO_8601)

**Calendar dates**

Calendar date representations are in the form shown in the adjacent box.
[YYYY] indicates a four-digit year, 0000 through 9999.
[MM] indicates a two-digit month of the year, **01 through 12**.
[DD] indicates a two-digit day of that month, 01 through 31.
For example, "5 April 1981" may be represented as either "1981-04-05"[[14]](https://en.wikipedia.org/wiki/ISO_8601#cite_note-isofaqtnd-14) in the extended format or "19810405" in the basic format.

## jq Manual
Note that in [jq's Dates](https://jqlang.github.io/jq/manual/v1.6/#dates) the month in the input is `03` but `02` in the output.
```
Command: jq 'strptime("%Y-%m-%dT%H:%M:%SZ")'
input: "2015-03-05T23:51:47Z"
output: [2015,2,5,23,51,47,4,63]
```

# To Reproduce
```sh
jq --version ; jq -n '[2023, 07, 01, 0,0,0,0,0] | strftime("%Y-%m-%d")'
jq-1.6
"2023-08-01"
```

# Expected behavior
Given `[2023, 07, 01, 0,0,0,0,0]` I would expect 2023-07-01.
Why would months be 0-based indexed while year and day would be 1-based indexed?

# Environment

- OS and Version: Ubuntu
- jq version: 1.6

**Comment by nicowilliams** [comment]
>  Why would months be 0-based indexed while year and day would be 1-based indexed?

Fair question!  jq's "broken down time" representation is really POSIX's `struct tm` serialized as an array, and [POSIX says](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/time.h.html):

```
The <time.h> header shall declare the structure tm, which shall include at least the following members:

int    tm_sec   Seconds [0,60]. 
int    tm_min   Minutes [0,59]. 
int    tm_hour  Hour [0,23]. 
int    tm_mday  Day of month [1,31]. 
int    tm_mon   Month of year [0,11]. 
int    tm_year  Years since 1900. 
int    tm_wday  Day of week [0,6] (Sunday =0). 
int    tm_yday  Day of year [0,365]. 
int    tm_isdst Daylight Savings flag. 
```

I also think this is strange, that some things are zero-based and others are one-based in "broken-down time", but for jq to differ from this would cause even more confusion.  (Nor could we change this now, as that would be a backwards-incompatible change.)

Perhaps we should document this better, though we already say "Refer to your host operating system´s documentation [...]" in the manual section on datetime functions.

Note that jq is consistent about this:

```bash
: ; jq -cn '"2015-03-05T23:51:47Z" | . as $in | strptime("%Y-%m-%dT%H:%M:%SZ")| ($in == strftime("%Y-%m
-%dT%H:%M:%SZ"))'
true
: ; 
```

**Comment by nicowilliams** [comment]
Do you have suggestions for how we could make this clearer in the documentation?  (I do, so I might produce a PR.  But I'm asking for your opinion as to what would have helped you understand this ugliness more readily.)

**Comment by SamuelLarkin** [comment]
What a weird choice from the os's `strptime` to have a mix of 0-based and 1-based indexed fields.  All fields are 0-based indexed except the day of the month which is 1-based.

The way I stumbled on this is that I needed to filter some `jsonl` files where I entered a manual date.  The entries have their date exploded in `year`, `month` & `day`.  Expecting to filter entries with a date of November 1st 2022:
```sh
jq 'select((.doc | [.year//0, .month//0, .day//0, 0,0,0,0,0] | mktime) >= ([2022, 11, 1, 0,0,0,0,0] | mktime))'
```

To be fair, your documentation has an example that if I had looked closely, I would have notice that the month was shifted by one.  I unfortunately realized it in my work 😞 
```
Command: jq 'strptime("%Y-%m-%dT%H:%M:%SZ")'
input: "2015-03-05T23:51:47Z"
output: [2015,2,5,23,51,47,4,63]
```

My bad for looking at `mktime`'s man pages and not at `strptime`.

Could you simply add a warning that if you create manual dates by constructing an array of 8 numbers, like I did, that the months are 0-based indexed?  Or could you add a snippet that shows what `mktime`'s expected format?  By that I mean, adding
```
               int tm_sec;    /* Seconds (0-60) */
               int tm_min;    /* Minutes (0-59) */
               int tm_hour;   /* Hours (0-23) */
               int tm_mday;   /* Day of the month (1-31) */
               int tm_mon;    /* Month (0-11) */
               int tm_year;   /* Year - 1900 */
               int tm_wday;   /* Day of the week (0-6, Sunday = 0) */
               int tm_yday;   /* Day in the year (0-365, 1 Jan = 0) */
               int tm_isdst;  /* Daylight saving time */
```
right in the documentation?
Then again, it's my bad for not reading 'mkdtime`.

Thank you for your time and thank you for such a GREAT and USEFUL software 😄

**Comment by nicowilliams** [comment]
Sure, and looking back too, I think it was a mistake to use an array instead of an object for the broken down time.
