### ISSUE TITLE
man page missing text

### ISSUE THREAD

**Issue by 1da1a172** [jqlang/jq#2930]
**Describe the bug**
Text is missing from the man page. It looks like anytime there is a link, the link text and following text to the end of the line is removed.

**To Reproduce**
For a specific example, look at the first two sentences of under the [REGULAR EXPRESSIONS section](https://man.archlinux.org/man/jq.1.en#REGULAR_EXPRESSIONS).
It reads:
> jq uses the
>
> Oniguruma supports several flavors of regular expression, so it is important to know that jq uses the

**Expected behavior**
It should contain the [full text](https://jqlang.github.io/jq/manual/#regular-expressions):
> jq uses the Oniguruma regular expression library, as do PHP, TextMate, Sublime Text, etc, so the description here will focus on jq specifics.
>
> Oniguruma supports several flavors of regular expression, so it is important to know that jq uses the "Perl NG" (Perl with named groups) flavor.

**Environment:**
- Archlinux
- jq version 1.7

**Additional context**
To rule out a packaging bug, I also built `jq` manually from the git source. I made sure I had the correct dependencies installed and followed the [documentation build instructions](https://github.com/jqlang/jq/blob/master/docs/README.md). `jq.1` is still missing the same text.

It is worth noting that the text is also missing from the [prebuilt man page](https://github.com/jqlang/jq/blob/master/jq.1.prebuilt#L2741).

**Comment by nicowilliams** [comment]
Looks like a bug in the manual markup.  Thanks for the report!
