### ISSUE TITLE
What is the character set of json key? Doesn't it also support hyphens? I found that jq has confusing problems with character set support. I tested 1.7 and previous versions.

### ISSUE THREAD

**Issue by cliusz** [jqlang/jq#2943]
**Describe the bug**

**To Reproduce**
Provide a minimal test case to reproduce the behavior.
If the input is large, either attach it as a file, or [create a gist](https://gist.github.com) and link to it here.

**Expected behavior**

**Environment (please complete the following information):**

- OS and Version: [e.g. macOS, Windows, Linux (please specify distro)]
- jq version [e.g. 1.5]

**Additional context**

**Comment by nicowilliams** [comment]
To use hyphens in keys you need to use `.["the-key"]` syntax.  The `.key` syntax you've been using is only for identifier-like keys -- a hyphen would be confused with the minus binary operator.
