### ISSUE TITLE
Windows jq version 1.7 has a "dirty" suffix when downloading AMD64 version from https://jqlang.github.io/jq/download/

### ISSUE THREAD

**Issue by gj02ib65** [jqlang/jq#2947]
**Describe the bug**
jq --version reports "jq 1.7 dirty" when I download using the AMD64 link https://github.com/jqlang/jq/releases/download/jq-1.7/jq-windows-amd64.exe.  I have switched to using the jq 1.6 --version, which reports "jq 1.6".  I have not tested the other direct download versions on jq 1.7. 

**To Reproduce**
From Windows 11 - Download jq 1.7 from this link "https://github.com/jqlang/jq/releases/download/jq-1.7/jq-windows-amd64.exe".  Then run jq --version.

**Expected behavior**
I expect that the jq --version would report "jq 1.7."

**Environment (please complete the following information):**

- OS and Version: [e.g. macOS, Windows, Linux (please specify distro)]:  Windows 11
- jq version [e.g. 1.5]:  jq 1.7

**Additional context**

**Comment by gj02ib65** [comment]
Related to #2886

**Comment by emanuele6** [comment]
duplicate even
