### ISSUE TITLE
OT: What versions of arm require `armel`?

### ISSUE THREAD

**Issue by coolaj86** [jqlang/jq#2950]
I've just automated a process of [categorizing over 33,000 release assets](https://github.com/webinstall/webi-installers/pull/756) across 100+ modern developer tooling projects and `jq` is the only one that explicitly has a build for `armel`.

What does that mean? Is that `armv4`? or `armv5`? or `armv6`? Or is it more OS-specific (`gnueabihf` vs `gnueabi` vs `arm-eabi`) than hardware specific?

I'm not a C developer and as I've been sifting through various documentation and forums trying to figure how to match which build to which `unarm -m`, I'm still stumped as to the overlap between hardware and gnu naming conventions.

What type of system would need an `armel` binary? It seems that even as far back as Raspberry Pi 1 uses `arm-unknown-linux-gnueabihf` (armhf / armv7l).

**Comment by wader** [comment]
Hi, i think https://github.com/jqlang/jq/issues/2933 might have some info about this

**Comment by itchyny** [comment]
The `armel` binary is built by `arm-linux-gnueabi`, so this is for older versions than v7. Like Debian for ARM EABI  https://wiki.debian.org/ArmEabiPort.

**Comment by coolaj86** [comment]
Thanks. This was helpful.

I did some other research and took notes here: https://github.com/webinstall/webi-installers/issues/778

Basically what I've learned is that ARM is a very robust set of standards that it not always fully implemented for special purpose boards - most of which we would never need to care about.

- armv7 (`armhf`) has been around since 2008 (Gumstix, BeagleBoard)
- but armv6 (`armel`, `arm11`) was put in brand new devices as recently as 2014 (RPi B+)

# Bottom Line

I can't find reference to _any_ popular devices that would need `armel`. \
I think you'd have to go back to a device more than 20 years old - before ARM was yet _hip_.

The original Raspberry Pi 1 was `armv6hf` (a custom module set inbetween armv7 and armv6), but some of the OSes of that era may have been _compiled_ as `armel` for backwards compatibility. If so, they would have required `armel` binaries, or possibly the addition of `libc:armhf`. \
I can't easily find a version that old to test with to confirm.

Statically compiled `armhf` binaries would run on an `armel`-compiled OS as long as the hardware was `armv6hf` or newer.
