### ISSUE TITLE
Base64d filter is not working as expected.

### ISSUE THREAD

**Issue by ZobairQ** [jqlang/jq#3001]
**Describe the bug**
A clear and concise description of what the bug 
The `@base64d` is not working the same way as base64 -d. If you have a base64 value you would want to decode using `@base64d` you get an extra new line. However using the `-j` option eleminates this. 
How if you have two values that are base64 encoded such as an array, `@base64d` only decodes the first value.

```bash
## This is the extra line
bash-5.1# echo '{"data":"bW9ua2V5Cg== ZmlzaAo="}' |jq -r '.data|@base64d'
monkey

bash-5.1# echo '{"data":"bW9ua2V5Cg== ZmlzaAo="}' |jq -r -j '.data|@base64d'
monkey ## This does not decode the fish encryption

## This is the behaviour I expect
bash-5.1# echo '{"data":"bW9ua2V5Cg== ZmlzaAo="}' |jq -r '.data'|base64 -d
monkey
fish
bash-5.1# echo '{"data":"bW9ua2V5Cg== ZmlzaAo="}' |jq -r -j '.data'|base64 -d
monkey
fish
bash-5.1# 

```

**To Reproduce**
The commands are provided in the description.
**Expected behavior**
```
bash-5.1# echo '{"data":"bW9ua2V5Cg== ZmlzaAo="}' |jq -r '.data'|base64 -d
monkey
fish
```
**Environment (please complete the following information):**
```
bash-5.1# cat /etc/*-release
3.13.5
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.5
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
Jq version: 1.6 and 1.17.1 

- OS and Version: [e.g. macOS, Windows, Linux (please specify distro)]
- jq version [e.g. 1.5]

**Additional context**
This is fairly simple to test and reproduce

**Comment by emanuele6** [comment]
It is not a bug; you need to split the string manually

**Comment by emanuele6** [comment]
E.g. `.data / " " | .[] | @base64d` or `.data | scan("[^ ]+") | @base64d`
