### ISSUE TITLE
Unrecognized HTML entity: `&copy;` while running xq command

### ISSUE THREAD

**Issue by lulunac27a** [jqlang/jq#3021]
**Describe the bug**
I got an error while using `curl` command to curl HTML/XML webpages:
`xq: Error running jq: ExpatError: undefined entity &copy;`

**Expected behavior**
Should successfully pretty print XML output in JSON format including the copyright sign `&copy;` (©) 

**Environment (please complete the following information):**

- OS and Version: [e.g. macOS, Windows, Linux (please specify distro)] Mac
- jq version [e.g. 1.5] jq 1.6, xq 3.2.3

**Additional context**
Add `--html` option to parse HTML code on webpages

**Comment by nicowilliams** [comment]
I think you want to open this issue at https://github.com/sibprogrammer/xq/issues
