### ISSUE TITLE
Modulo operator drops fractional part

### ISSUE THREAD

**Issue by dimo414** [jqlang/jq#3025]
**Describe the bug**
In `jq` the `%` operator returns an integer, even if the input was a floating point value.

**To Reproduce**
```
$ jq '.%60' <<<"62.5"
2
```

**Expected behavior**
Typically modulo of a floating-point value should preserve the fractional part, e.g.:

```
$ python3 -c 'print(62.5 % 60)'
2.5
```

Users who want only the integer part can `round` the fractional part away, but you can't (easily) recover the fractional part once it's removed by `%`.

**Environment (please complete the following information):**
```
$ jq --version
jq-1.6
```

**Comment by emanuele6** [comment]
You want `fmod(.; 60)`, instead of `. % 60`
