### ISSUE TITLE
`jq` Installed Using x86_64 on Apple Silicon Using Mise

### ISSUE THREAD

**Issue by stherold** [jqlang/jq#3049]
**Describe the bug**

[Mise](https://github.com/jdx/mise) uses [ASDF plugins](https://github.com/asdf-vm/asdf-plugins) to install development tools. For jq it installs the Intel version of `jq`. 

**To Reproduce**

1. Create empty folder
1. Install mise using `curl https://mise.run | sh`
1. Create a config folder structure: `mkdir -p .config/mise`
1. Add [these](https://github.com/Blackjacx/Scripts/tree/main/bootstrap/config_dirs/mise) Mise config files to the created folder
1. Run `mise install`
1. Compare `file ${HOME}/.local/share/mise/installs/fzf/0/bin/fzf` with `file ${HOME}/.local/share/mise/installs/jq/1/bin/jq`

**Expected behavior**

After digging deeper I found that for [fzf](https://github.com/junegunn/fzf) it installs the arm64 vesion correctly. Thsi led me to checking the releases. It seems for both tools the GitHub release artifacts are downloaded. For fzf there is one with the name [fzf-0.46.1-darwin_arm64.zip](https://github.com/junegunn/fzf/releases). But for jq the name is corrupted (I think): [jq-macos-arm64](https://github.com/jqlang/jq/releases) - extension missing and macos instead of darwin. I recommend to name it as follows: `jq-<version>-darwin-arm64.zip`. This way it matches the fzf style and management tools like mise are able to properly install it.

**Environment (please complete the following information):**

- macOS 14.3.1 (23D60)
- jq 1.7.1

**Comment by itchyny** [comment]
The release artifacts are the executables so the names are not corrupted. I don't see what should be fixed from this issue. Isn't this a bug of Mise? Just switch the executable URLs based on the CPU architecture.

**Comment by nicowilliams** [comment]
[Looks fixed](https://github.com/lsanwick/asdf-jq/commit/addae5118090263aa43ca9eb998b250b10c7d2dd) in ASDF?

**Comment by nicowilliams** [comment]
Anyways, this is certainly not a bug in jq.  This should be reported to Mise or ASDF.
