### ISSUE TITLE
Hello, I just added jq into the x-cmd pkg

### ISSUE THREAD

**Issue by edwinjhlee** [jqlang/jq#3050]
Hello, friends in jq community.

I just add jq into the x-cmd pkg. Now jq users can simply 'x jq' to use jq.

And we record some scriptplay demos for jq:
- https://www.x-cmd.com/pkg/jq#jq
- https://www.x-cmd.com/1min/jq#jq

I apologize in advance if it's not appropriate to raise this topic using a GitHub issue.

**Comment by itchyny** [comment]
Thanks for letting us know.
