### ISSUE TITLE
Escaped backspace at end of string does not remove last character

### ISSUE THREAD

**Issue by SiXoS** [jqlang/jq#3054]
**Describe the bug**
When using the escape character `\b` for backspace at the end of a string, the last character is not removed.

**To Reproduce**
```bash
$ jq -nr '"hell\bo"' 
helo

$ jq -nr '"hello\b"'
hello
```

**Expected behavior**
The command `jq -nr '"hello\b"'` should output `hell`

**Environment (please complete the following information):**

- OS: Linux 6.5.0-21-generic 21~22.04.1-Ubuntu x86_64
- jq version: 1.6

**Comment by itchyny** [comment]
The command `printf 'hello\b\n'` doesn't remove `o` neither (while `printf 'hell\bo\n'` outputs `helo`). Is this an issue of jq?

**Comment by itchyny** [comment]
I think the escaped backspace just tells the terminal to move the cursor backwards, not erase the printed characters to the end of the line.
Try: `printf 'hello'; sleep 3; printf '\b\b'; sleep 3; printf 'oo'; sleep 3`

**Comment by emanuele6** [comment]
Yes, that is correct; this is not a bug, it is just what happens when you print a raw `\b` to a terminal. Closing
