### ISSUE TITLE
CI does extra work by running `sudo apt-get upgrade`

### ISSUE THREAD

**Issue by mgree** [jqlang/jq#3066]
The [CI workflow file testing the `jq` build](https://github.com/jqlang/jq/blob/master/.github/workflows/ci.yml) runs [`sudo apt-get upgrade`](https://github.com/jqlang/jq/blob/c95b34ff827d05a2d262f00280a4891a295ed0ed/.github/workflows/ci.yml#L84), which can lead  to updating irrelevant packages, like firefox.

**EDITED TO ADD**: https://github.com/jqlang/jq/actions/runs/8252928583?pr=3063 is a run that exhibits the slow behavior.

**Comment by wader** [comment]
Yeap that seems unnecessary.

@owenthereal was there some special reasons for doing an upgrade?

**Comment by emanuele6** [comment]
FWIW I have had to re-run a lot of CI jobs in the past two/three days because they were randomly failing on that step:
https://github.com/jqlang/jq/actions/runs/8466407678/job/23195111718
