### ISSUE TITLE
Regex capture doesn't produce any result

### ISSUE THREAD

**Issue by itoed** [jqlang/jq#3072]
Shouldn't `capture` return an object even when the input doesn't match?

```
$ jq -en '"xyzzy_14" | capture("(?<a>[a-z]+)-(?<n>[0-9]+)")'
$ echo "$?"
4
$ jq --version
jq-1.7.1
```

If this is as designed, how do you check for nothingness?

**Comment by itoed** [comment]
I got the answer from [scan](https://jqlang.github.io/jq/manual/#scan).
```
$ jq -en '"xyzzy_14" | [capture("(?<a>[a-z]+)-(?<n>[0-9]+)")']
[]
```

**Comment by pkoppstein** [comment]
> how do you check for nothingness?

You can also use `//`.

**Comment by wader** [comment]
@itoed if you use the `g` flag to find all matches it might be a bit clearer what's going on. jq outputs each match separately, not an array with matches, so if no matches no outputs at all.
```sh
$ jq -cn '"abc" | capture("(?<group>.)"; "g")'
{"group":"a"}
{"group":"b"}
{"group":"c"}
```
