### ISSUE TITLE
apt-get (ubuntu) still gives version 1.6

### ISSUE THREAD

**Issue by BeyondEvil** [jqlang/jq#3075]
**Describe the bug**
`apt-get` on Ubuntu (Jammy) still installs version 1.6

**To Reproduce**
Run:

```sh
# apt-get -y update && apt-get -y install jq && jq --version
```

**Expected behavior**
Latest version (`1.7.1` as of writing) should be installed.

**Environment (please complete the following information):**

```sh
ssm-user@ip-10-46-128-9:/var/snap/amazon-ssm-agent/7983$ uname -a
Linux ip-10-46-128-9 6.5.0-1015-aws #15~22.04.1-Ubuntu SMP Tue Feb 20 20:12:08 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
ssm-user@ip-10-46-128-9:/var/snap/amazon-ssm-agent/7983$ lsb_release -c
Codename:       jammy
ssm-user@ip-10-46-128-9:/var/snap/amazon-ssm-agent/7983$ sudo apt-get -y update && sudo apt-get install jq && sudo jq --version
Hit:1 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://packages.gitlab.com/runner/gitlab-runner/ubuntu jammy InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
jq is already the newest version (1.6-2.1ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
jq-1.6
```

**Additional context**
This is an AWS AMI Ubuntu image.

**Comment by wader** [comment]
Hi, it's not packaged by anyone of the current jq maintainers so you probably have to ask the debian maintainer about it. 1.7  seems to be package for testing and unstable atm, see https://tracker.debian.org/pkg/jq, but not sure if it will be moved to current stable or it will have to wait for a new stable release.

**Comment by BeyondEvil** [comment]
> Hi, it's not packaged by anyone of the current jq maintainers so you probably have to ask the debian maintainer about it. 1.7 seems to be package for testing and unstable atm, see https://tracker.debian.org/pkg/jq, but not sure if it will be moved to current stable or it will have to wait for a new stable release.

Is there a plan for the current jq maintainers to take over maintenance of the debian package?

**Comment by wader** [comment]
No plan that i know of. I think it's probably best that experts for each distribution to do the packaging, but me and probably other jq maintainers are happy to help out with issues they encounter. Looking at the current jq debian issues they seem mostly be about debian specific things like lack of build for mips64el etc.

jq 1.7 seems to be in ubuntu noble, there is no AWS AMI image for that? other option i guess is to download one of our static builds.

**Comment by BeyondEvil** [comment]
Yeah, I saw that as well (the issue with mips) but also some warning regarding NMU (something wrt. maintainers...?).

I'm not sure what is needed to push it forward, I'm not well versed in the debian package domain :(

Seems the latest version is 23.10 Mantic, there are no 24 Noble AMIs available yet.

I'll go the static route, thanks! :)

**Comment by wader** [comment]
👍 the current debian package maintainer seems fairly active so hopefully things will move along soon
