### ISSUE TITLE
Are there any errors in the ICU License description in the "decNumber"?

### ISSUE THREAD

**Issue by 2020122300003133** [jqlang/jq#3079]
https://github.com/jqlang/jq?tab=License-1-ov-file#readme
The "decNumber" of the ICU License listed here is "ICU 1.8.1 and later", is this correct?

I am aware that the following is listed at the end of the "ICU 1.8.1 and later" regulation, but I do not see it listed here.

**"All trademarks and registered trademarks mentioned herein are the property of their respective owners."**

Wouldn't the correct phrase be "ICU License - ICU 1.8.1 to ICU 57.1" instead of "ICU 1.8.1 and later"?

Best regards,

**Comment by 2020122300003133** [comment]
https://github.com/jqlang/jq/blob/master/src/decNumber/ICU-license.html
I found the correct License here.

I suggest that the "readme" be modified.

Best regards,

**Comment by emanuele6** [comment]
I cannot see what is wrong. [src/decNumber/ICU-license.html](https://github.com/jqlang/jq/blob/master/src/decNumber/ICU-license.html) says "ICU 1.8.1 and later"; and `README.md` says
> jq uses parts of the open source C library "decNumber", which is distributed under [ICU License](https://github.com/jqlang/jq/blob/master/COPYING)

And the "ICU License" link links to `COPYING` that says "ICU 1.8.1 and later".

**Comment by emanuele6** [comment]
Oh, you are saying `COPYING` is missing:
```

--------------------------------------------------------------------------------
All trademarks and registered trademarks mentioned herein are the property of their respective owners.
```
at the end.

Hmm, that is probably part of the licence, yes. It should be included in `COPYING`

**Comment by 2020122300003133** [comment]
I apologize that my explanation was not clear.
And thank you for adding the document.
