### ISSUE TITLE
Unable to install jp using poetry or pip

### ISSUE THREAD

**Issue by JPonsa** [jqlang/jq#3087]
Unable to install jp using poetry 

running "poetry add jq" gives the error below.  

Note: This error originates from the build backend, and is likely not a problem with poetry but with jq (1.7.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "jq (==1.7.0)"'

I tried poetry run pip install "jq (>=1.7.0) , and poetry run pip wheel --no-cache-dir --no-use-pep517 "jq (>=1.7.0)" but failed."

Any guidance is welcomed.

**Comment by itchyny** [comment]
Please report to [the issue tracker of the Python binding](https://github.com/mwilliamson/jq.py/issues).
