### ISSUE TITLE
 The jq  returned wrong json after updating based on select. 

### ISSUE THREAD

**Issue by HeenaBansal20** [jqlang/jq#3089]
Hi ,
I need some help to update json and  return teh updated one. But with belwo query i can see my intented key value is updated. but returned json is not matching with original one.

My json looks like :
`{
    “School”: {
        “SchoolName1”: {
            “Class “: “Grade1”,
            “Student”: [
                "1A”,
                “1B,
                “1”C
            ]
        }
    },
    “Infrastructure: [
        {
            “Abc”: “school1,
            “123”: " 123”,
            “EFG: "2.6.6",
            “Teachers: {
                “r1”: “1000”,
                "r2”:  "2000”,
                "r3”:  “3000”
            },
        {
                        “Abc”: “school2”,
            “123”: “123”,
            “EFG: "2.6.6",
            “Teachers: {
                “r1”: “500”,
                "r2”:  “7000”,
                "r3”:  “9000”
        }
    ]
}`

I am looking to update r2 value based on ABC value.
`jq ".[]| map(if .\"Abc\" == "School2" then .Teachers.r2 = 5000 else . end)"  
`This query is updating the key value pair correctly but resultant json looks like below
`[
{
            “Class “: “Grade1”,
            “Student”: [
                "1A”,
                “1B,
                “1”C
            ]
        }
]
[
    “Infrastructure: [
        {
            “Abc”: “school1,
            “123”: " 123”,
            “EFG: "2.6.6",
            “Teachers: {
                “r1”: “1000”,
                "r2”:  "2000”,
                "r3”:  “3000”
            },
        {
                        “Abc”: “school2”,
            “123”: “123”,
            “EFG: "2.6.6",
            “Teachers: {
                “r1”: “500”,
                "r2”:  “5000”,
                "r3”:  “9000”
        }
    ]
}
]

`
The jq shouldn't delete the keys from JSON.

**Comment by itchyny** [comment]
Instead of starting the query with `.[] |`, use `.[] |=` (like `".[] |= map(if .\"Abc\"`). The `.[]` query iterates the map values, whereas `|=` updates against them.
