### ISSUE TITLE
Multiplying -1 with 0 must result 0, not -0

### ISSUE THREAD

**Issue by mkipcak-hrlabs** [jqlang/jq#3102]
**Describe the bug**
Multiplying -1 with 0 must result 0, not -0

**To Reproduce**
Execute this command below
 jq -n '0 * -1'

**Expected behavior**
Mathematically speaking, the result of this mathematical operation (zero times minus 1) should be zero(0) and not minus zero (-0). 

**Environment (please complete the following information):**
any

- OS and Version: [e.g. macOS, Windows, Linux (please specify distro)]
- jq-1.7.1 macos

**Additional context**

**Comment by itchyny** [comment]
Zero is singed in IEEE 754 and this is working as intended.

**Comment by wader** [comment]
@mkipcak-hrlabs could elaborate on what problem this causes? node seem to behave the same but not python. I also noticed this behaviour 🤔 
```
$ jq -n '-0 | abs, fabs'
-0
0
```
