### ISSUE TITLE
Unexpected output

### ISSUE THREAD

**Issue by haanjde** [jqlang/jq#3108]
# Bug description
During developing a larger solution, unexpected output was generated.

# Reproduction
Minimal test case:
```console
echo '{"a":{"b":"g"}}{"a":{"c":"h"}}{"a":{"d":"i"}}{"e":{"f":"j"}}' | jq 'inputs'
{
  "a": {
    "c": "h"
  }
}
{
  "a": {
    "d": "i"
  }
}
{
  "e": {
    "f": "j"
  }
}
```

# Expected behavior
The expected output was

```json
{
  "a": {
    "b": "g"
  }
}
{
  "a": {
    "c": "h"
  }
}
{
  "a": {
    "d": "i"
  }
}
{
  "e": {
    "f": "j"
  }
}
```

# Environment

- OS and Version: Ubuntu 24.04 LTS
- jq version: jq-1.7

**Comment by itchyny** [comment]
Invoke with `-n` option not to read the first value as query input; `jq -n 'inputs'`.
