### ISSUE TITLE
Regular expression alternation (|) used with quantifier (* or +) returns inconsistent results when first alternative is able to match an empty string

### ISSUE THREAD

**Issue by elmaimbo** [jqlang/jq#3117]
**Describe the bug**
When alternation is used in combination with a `*` or `+` quantifier - i.e. `(XXX|YYY)*` or `(XXX|YYY)+` - you get unexpected results if the first alternative (`XXX`) can match an empty string.

**To Reproduce**
The following base-line test produces the output `ab`:
```
$ jq -nr '"ab" | match("(?:a|b)*") | .string'
ab
```

To observe the issue, make the first alternative optional:
```
$ jq -nr '"ab" | match("(?:a?|b)*") | .string'
a
```

Interestingly, if you then swap the order of the two alternatives (meaning that the one that can match an empty string is no longer the first alternative) it fixes the problem:
```
$ jq -nr '"ab" | match("(?:b|a?)*") | .string'
ab
```

**Expected behavior**
All three tests above should produce the same output.

**Environment (please complete the following information):**
- OS and Version: Linux Ubuntu 23.10
- jq versions 1.6, 1.7 and 1.71 all give the same results

**Comment by pkoppstein** [comment]
gojq and jaq both produce the correct result:
```
$ jq -nR '"ab" | match("(a?|b)*").string'
"a"
$ gojq -nR '"ab" | match("(a?|b)*").string'
"ab"
$ jaq -nR '"ab" | match("(a?|b)*").string'
"ab"
```

**Comment by emanuele6** [comment]
> gojq and jaq both produce the correct result:

`jq` and `gojq` don't use the same kind of regular expressions though. There are some `jq` regular expressions that won't work in`gojq`.

---

I don't think `jq` has any control over this issue anyway; `match` just calls to oniguruma and contructs an object based on the result.

**Comment by pkoppstein** [comment]
Apparently the observed behavior is expected of PCRE. (*)

Since jq deliberately uses the PCRE flavor of Oniguruma, it would therefore appear that the only question to emerge from this issue is whether in future jq should choose a different flavor.

---
(*) See https://regex101.com/
