### ISSUE TITLE
Request for snap maintenance

### ISSUE THREAD

**Issue by boukendesho** [jqlang/jq#3135]
Hi team,

I like jq and appreciate the project,

but the jq snap in ubuntu snap store is very [outdated](https://snapcraft.io/jq) .

I understand there is no offical support for snap, 
so i  want to take over the snap jq maintenance as a community maintainer.

I'd like to know if you're open to this idea. Thanks.

**Comment by wader** [comment]
Hi, yeap i don't think any of the current jq maintainers are involved with the snap packaging. Best is probably to try contact the current maintainer of it which seems to be https://snapcraft.io/publisher/mvo

**Comment by boukendesho** [comment]
@wader I tried and no response from current snap jq maintainer.
But there is a way that can take over the maintenance from current maintainer.

I need a validation from the official like this https://github.com/rclone/rclone/issues/7221

And after team's comment i can show it to canonical and it will transfer the name to me.

**Comment by wader** [comment]
I see, that we can probably do. In these post-xz-backdoor days i guess we probably want to somehow verify the person who takes it over also? not sure how that could be done, does snap has some process/guidelines for that?

**Comment by boukendesho** [comment]
Snap have verified accounts and star developers, but i am neither.
I see your concern, but  i can't do much about it.
Or you can take over the maintenance, a snap package is simple, only a single yaml file define all the things.
If you are interested in , i can contribute to it.
All i want just snap jq can get  updated.

**Comment by boukendesho** [comment]
@wader

**Comment by wader** [comment]
Hey, sorry i have no experience with snap. Is the yaml file usually in the repo of the project or somewhere else? is there some build infra that builds things into some kind of binary package? maintained/hosted by canonical?

**Comment by boukendesho** [comment]
@wader Yes, usually in the repo under snap directory. such as  [this](https://github.com/boukendesho/rclone-snap/blob/main/snap/snapcraft.yaml)
If link the repo to canonical's snap store, then whenever a commit made, canonical will auto start build snap package for you. A snap package is a readonly squashfs file system, hosted by canonical snap store.

**Comment by wader** [comment]
Ok so best would be to add the snap file to jqlang/jq repo somewhere and then tell canonical somehow to use that file to build? i guess that would be fine. As long as things are transparent and the building/packaging happens on canonical's systems it sounds resonable and safe.

What do other maintainers think?

**Comment by boukendesho** [comment]
@wader That will be great! 
Then you need register a snap store account, file a request , take the jq name from current maintainer.
After take over the name, you can access to the snap store developer page to do some settings.

**Comment by pkoppstein** [comment]
The listing at https://snapcraft.io/store?q=Jq shows seven snap packages for jq, with 5 different authors.   One package is highlighted as being authored by “Canonical”.  Have attempts been made to contact the Canonical author in particular?

**Comment by boukendesho** [comment]
@pkoppstein Only this [one](https://snapcraft.io/jq) have correct name jq. Others are jq-core18, jq-core20, jq-core22 etc....

**Comment by boukendesho** [comment]
@wader @pkoppstein Sorry to keep pushing, but if upstream is too busy could you once again consider letting me maintain the snap ?

**Comment by itchyny** [comment]
The jq maintainers have no ownership on the snap packages. I think you should be the maintainer of the snap, but here is not the right place to request that.
