### ISSUE TITLE
Docker images lack `latest` tag

### ISSUE THREAD

**Issue by ErroneousBosch** [jqlang/jq#3142]
**Describe the bug**
Docker images lack `latest` tag

**To Reproduce**
try to pull `ghcr.io/jqlang/jq:latest` with docker. request will time out

```
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/jqlang/jq/manifests/latest": Get "https://ghcr.io/token?account=erroneousbosch&scope=repository%3Ajqlang%2Fjq%3Apull&service=ghcr.io": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Expected behavior**
latest version of docker container (1.7.1 at time of writing) should pull. 

**Environment (please complete the following information):**

- Ubuntu 22.04
- jq 1.7.1

**Additional context**
Given that this is in the README, it can be confusing for some people.

**Comment by itchyny** [comment]
We have already released the `latest` tag, I think the error comes from different issue.

```
 $ docker pull ghcr.io/jqlang/jq
Using default tag: latest
latest: Pulling from jqlang/jq
Digest: sha256:096b83865ad59b5b02841f103f83f45c51318394331bf1995e187ea3be937432
Status: Image is up to date for ghcr.io/jqlang/jq:latest
ghcr.io/jqlang/jq:latest
```
https://github.com/jqlang/jq/pkgs/container/jq/157780318?tag=latest

The `docker/metadata-action` action automatically adds `latest` tag when we use `type=match`, so we have nothing special to do.
https://github.com/docker/metadata-action?tab=readme-ov-file#latest-tag

**Comment by wader** [comment]
Works for me too:
```sh
$ docker run --rm ghcr.io/jqlang/jq:latest --version
Unable to find image 'ghcr.io/jqlang/jq:latest' locally
latest: Pulling from jqlang/jq
84929edf7b1a: Pull complete
2e5a8bb8c775: Pull complete
Digest: sha256:096b83865ad59b5b02841f103f83f45c51318394331bf1995e187ea3be937432
Status: Downloaded newer image for ghcr.io/jqlang/jq:latest
jq-1.7.1
```
Some transient network problem or proxies in between?

**Comment by itchyny** [comment]
Closing, latest tag is working.
