### ISSUE TITLE
`JV_PRINTF_LIKE` macros in `jv.h` missing fallback definition

### ISSUE THREAD

**Issue by fuhsnn** [jqlang/jq#3159]
Hi, the two macros here:
https://github.com/jqlang/jq/blob/c1d885b0249f3978de3a21ea2bfb7ced06ed2aff/src/jv.h#L111-L117
are defined only for `__GNUC__` compilers, no fallback provided otherwise. 

As `__attribute__ ((__format__))` is only for warnings, some dummy defines will allow non-`__GNUC__` compilers to build `jq`.
```
diff --git a/src/jv.h b/src/jv.h
index 083509e..67aa596 100644
--- a/src/jv.h
+++ b/src/jv.h
@@ -113,6 +113,9 @@ jv jv_array_indexes(jv, jv);
   __attribute__ ((__format__( __printf__, fmt_arg_num, args_num)))
 #define JV_VPRINTF_LIKE(fmt_arg_num) \
   __attribute__ ((__format__( __printf__, fmt_arg_num, 0)))
+#else
+#define JV_PRINTF_LIKE(fmt_arg_num, args_num)
+#define JV_VPRINTF_LIKE(fmt_arg_num)
 #endif
```

**Comment by emanuele6** [comment]
Thank you for the report!
