### ISSUE TITLE
jq cannot parse more than 10,000 definitions in a row

### ISSUE THREAD

**Issue by 01mf02** [jqlang/jq#3171]
When parsing something like `def a: 1; def a: 1; ...; 1`, where the definition is repeated 10,000 times, jq yields an error:

~~~
$ jq-linux-amd64-1.7.1 -n -f <(for i in `seq 10000`; do echo "def a: 1;"; done; echo 1)
jq: error: memory exhausted at <top-level>, line 9993:
def a: 1;        
jq: 1 compile error
~~~

My hypothesis is that `def a: 1; def b: 2; 3` is parsed to something like `Def(..., Def(..., 3))` This is underpinned by the [maximum parser stack size of 10000](https://github.com/jqlang/jq/blob/37f4cd2648faa2a4c78c3d4caf5d61cb491c7d22/src/parser.c#L1875).
An easy (?) solution is to parse to something like `[Def(...), Def(...)], 3` instead; that is, store a list of consecutive definitions. That's what I do in jaq, and it works great.

**Comment by itchyny** [comment]
Parsing such file with an unrealistic number of definitions is not important to us, so I'm closing this now. But if you have a patch to extending the limit, we'll review it. Thanks.
