### ISSUE TITLE
Add command line flag to not output value

### ISSUE THREAD

**Issue by nikandfor** [jqlang/jq#3175]
There is an `--exit-status` flag which is useful for using in bash. But most of the time I used it I wanted to not to have any output, just the exit code. There is an option to redirect output to `/dev/null`, but it would be much more convenient to have a flag.

For example
```bash
for file in some/files/*.json; do
    jq -e '.some.key == "some value"' $file >/dev/null && echo $file
done
```

Would be cool to have, say, `-q` flag (for quiet) instead of `>/dev/null`.

Can we consider it?

**Comment by itchyny** [comment]
This is a duplication of #1225. No one has submitted a patch for years though.

**Comment by wader** [comment]
I looked into adding this but if i remember correctly it was quite messy to do in the current code so i got stuck trying to refactoring things. But please try if you have time and motivation! would be nice

Update: found a first version, pushed it here https://github.com/wader/jq/tree/quiet-mode if i remember it has some problems that triggered the refactor

**Comment by itchyny** [comment]
Closing as dup.
