### ISSUE TITLE
No warning when a single equals-sign appears in a boolean expression inside select()

### ISSUE THREAD

**Issue by dnwake** [jqlang/jq#3210]
**Describe the bug**

The behavior of a single equals-sign inside a boolean expression is extremely unintuitive, creating a high risk of mistakes when using the `select()` function.  This risk could be mitigated by adding warnings.

**To Reproduce**

***Example 1***

Input: 
`[{"x":0}, {"x":1}]`

Code: 
`.[] | select (.x=1)`

Output:
```
{"x":0}
{"x":1}
```

Comment:
`.x=1`
is interpreted as 
`{"x":1}`
which is then converted to boolean` true`

***Example 2***

Input: 
`[{"x":1, "y":1}, {"x":1, "y":2}]`

Code: 
`.[] | select (.x=1 and .y==2)`

Output:
```
{"x":1,"y":1}
{"x":1,"y":2}
```

Comment:
`.x=1 and .y==2`
is interpreted successively as 
`.x = (1 and .y== 2)`
then
`.x = (true and .y == 2)`
then
`.x = true`  or `.x = false` (depending on the value of .y)
then
`{x: true}` or `{x: false}` (depending on the value of .y)
then
`true` (regardless of the value of .y).

**Expected behavior**
It's hard to imagine any situation in which this behavior of the single equals-sign inside a select expression would be desired.  It is overwhelmingly likely to be a typographical error for double equals-sign representing equality.

A warning would be expected in order to guard against these errors.

**Environment (please complete the following information):**

- OS and Version: macOS 14.6.1
- jq version 1.7.1

**Additional context**

**Comment by wader** [comment]
As same argument would apply to condition expression of `if` and arguments to `sort_by`, `group_by` etc i think a more general solution is probably more suitable. Maybe an opt-in option to warn/error on any assignment or assignment to input? but i'm personally not sure jq need much more options.

BTW there is a hacky way to error or warn on any assignments if you want. This redefines the internal `_assign/2` function:
```sh
$ jq -n 'def _assign(paths;$v): error("trying to assign \(path(paths)) to \($v)"); select(.x=1)'
jq: error (at <unknown>): trying to assign ["x"] to 1
```

**Comment by pkoppstein** [comment]
Issuing a warning for doubtful code is the job of a linter, not an interpreter. An option to issue warnings might be nice but scoping out and implementing such an option would be a major undertaking, well beyond the scope of the particular issue raised here, which I am therefore closing.
