### ISSUE TITLE
Provide built-in array compaction

### ISSUE THREAD

**Issue by aep-sunlife** [jqlang/jq#3213]
**Describe the bug**

Neither `flatten`, nor `add`, nor `+` concatenate arrays.

Strangely, `flatten` when sent a series of elements nested in a single array, has no effect. jq 1.7.1 on macOS.

`flatten[]` almost works, but when given a list of lists of objects, then the output is always a raw series of objects, without the opening/closing hard brackets (`[ ... ]`). Causing downstream JSON processing to fail. I'm not using the `-r` raw option. There doesn't appear to be a way to restore the brackets without re-nesting the elements, back to the original problem.

Would like this behavior aliased to a more memorable function name.

**Comment by wader** [comment]
Not sure i follow what you mean by array concatenation and compaction, could you give some examples?

`+` does what i would call array concatenation:
```sh
$ jq -cn '[[1],2,3] + [[4],5,6]'
[[1],2,3,[4],5,6]
```
`add` works similar but you instead give it an array of values, that can be other things than arrays, to concatenate:
```sh
$ jq -cn '[[1,2], [3,4], [5,6]] | add'
[1,2,3,4,5,6]
```
`flatten` on the other hand will "flatten"-out any nested arrays so you end up with just one array containing all non-array values:
```sh
$ jq -cn '[[[1]],2] | flatten'
[1,2]
```
`flatten[]` is short-hand for `flatten | .[]` so it will iterate and output each value in the flattened array. Noticed the difference between `1, 2` and `[1, 2]` in jq. The first is a generator that outputs `1` then `2`, the latter outputs just one value the array `[1, 2]`. And `[1,2] | .[]` is more or less `1, 2`, and you can collect the generator into an array again `[[1, 2]  | .[]]` results in `[1, 2]`.

Hope that helps and clears some things up

**Comment by pkoppstein** [comment]
[aep-sunlife](https://github.com/aep-sunlife) Hopefully @wader clarified the situation for you.  If you have a usage question, I would suggest you ask it at stackoverflow.com using the jq tag.  Thanks.
