### ISSUE TITLE
`jq -e` returns unexpected results on empty input

### ISSUE THREAD

**Issue by erickj** [jqlang/jq#3214]
The following behavior seems to be at odds with the description of the `-e` flag in the jq man page. The return value for checking if an empty input has a key seems to always succeed.

```
$ echo '' | jq -e '. | has("foo")'; echo $?
0
$ echo ' ' | jq -e '. | has("foo")'; echo $?
0
$ echo '' | jq -e 'if . | has("foo") then true else false end'; echo $?
0
$ jq -version
jq-1.6
```

`jq -e` documentation says:
```
 -e / --exit-status:

           Sets the exit status of jq to 0 if the last output values was neither false nor null, 1 if the last output value was either false or null, or 4 if no valid result was ever produced. Normally jq
           exits with 2 if there was any usage problem or system error, 3 if there was a jq program compile error, or 0 if the jq program ran.
```

**Describe the bug**
Checking for the presence of a key on an empty value or white space input returns code 0. 

**To Reproduce**
See above

**Expected behavior**
return a non-0 return code

**Environment (please complete the following information):**

- OS and Version: [e.g. macOS, Windows, Linux (please specify distro)]
jq-1.6

**Comment by erickj** [comment]
interesting, it looks like maybe this bug was fixed in more recent versions.

```
$ echo '' | jq -e '. | has("foo")'; echo $?
4
22:01:49 [erick@jupiter:~/workspace/src/strix] (git:master *$%)
$ jq --version
jq-1.7.1
```

**Comment by wader** [comment]
Yeap, probably https://github.com/jqlang/jq/pull/1697. Note also that for `echo '' | jq ...` there wont be any inputs at all, as the exit code 4 indicates.

```sh
$ echo '{}' | jq -e 'has("foo")'; echo $?
false
1
$ echo '' | jq -e 'has("foo")'; echo $?
4
```
