### ISSUE TITLE
enhancement request: warning [was: error/2]

### ISSUE THREAD

**Issue by pkoppstein** [jqlang/jq#445]
[This proposal has been tweaked to take into account subsequent comments.]

error/1 writes to stderr, which is a good thing, but currently so far as I know, there's no way to write to stderr without also backtracking.  Being able to write to stderr without backtracking has several uses, not least as an aid to debugging.

warning(MSG) would fill the bill.

This would evaluate to ".".

**Comment by emanuele6** [comment]
This issue was basically a feature request for `stderr` or `stderr | empty`... closing.
