### ISSUE TITLE
Build man page/docs without ruby/bundle

### ISSUE THREAD

**Issue by drankinatty** [jqlang/jq#637]
This is a feature request that another manner be found to build/install man pages/doc without reliance on ruby/bundle. The additional storage size to install ruby/rubygem-bundle is ridiculous just to build documentation. Even after the ruby/rubygem-bundle install, the bundle install requires:

Fetching gem metadata from https://rubygems.org/..
Installing rake (10.0.3)
Installing Platform (0.4.0)
Installing open4 (1.3.0)
Installing POpen4 (0.1.4)
Installing i18n (0.6.4)
Installing multi_json (1.7.3)
Installing activesupport (3.2.12)
Installing addressable (2.3.4)
Installing builder (3.2.0)
Installing launchy (2.3.0)
Installing liquid (2.5.0)
Installing syntax (1.0.0)
Installing maruku (0.6.1)
Installing rack (1.5.2)
Installing sass (3.2.8)
Installing rack-protection (1.5.0)
Installing tilt (1.4.0)
Installing sinatra (1.4.2)
Installing watch (0.1.0)
Installing yui-compressor (0.9.6)
Installing bonsai (1.4.8)
Installing hpricot (0.8.6)
Installing mustache (0.99.4)
Installing rdiscount (2.0.7.2)
Installing ronn (0.7.3)
Using bundler (1.3.5)
Your bundle is complete!

Surely there is a better way. After developing heavily in linux for over 15 years, I have never had nor wanted ruby on my systems (Arch and openSuSE boxes). The basic install is over 30 meg just to build the jq docs. Yes, it will build without docs, but that's not desirable. Out of 100's of packages built/installed, jq is the first to want ruby/rubygems/bundle to create docs. Surely there is a better way.

Just an opportunity for improvement. Oldschool folks hate wasted space, even in the days of huge drives.

**Comment by alanbur** [comment]
For now could you please just provide a downloadable pre-built and preferably print-ready version of the documentation linked off of the project page?

**Comment by itchyny** [comment]
Ruby dependency was removed in #1838 on Feb 27, 2019.
