### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by kxmatejka** [jqlang/jq#683]
Hello, i have two pc. Both computers are running debian. On first pc work jq fine, but on second pc I have error: 
Illegal instruction (SIGILL)

piece from json:
{"server": {
        "protocol": "http",
        "adress": "10.7.64.206",
        "port": "7331"}

some usage:
jq '.server.adress' './config.json'

any idea? thx

**Comment by nicowilliams** [comment]
What does this say:

    $ file `which jq`

?

**Comment by oliverlangan** [comment]
I have the same problem, running jq 1.4 (32- or 64-bit) on an older version of Mac OS.
```
$ curl -O https://stedolan.github.io/jq/download/osx32/jq
$ chmod a+x jq
$ echo '{}' | ./jq .
Illegal instruction
$ sw_vers
ProductName:	Mac OS X Server
ProductVersion:	10.6.8
BuildVersion:	10K549
```

**Comment by itchyny** [comment]
Closing as unreproducible issue report. If anyone can reproduce, comment below in detail, thanks.
