### ISSUE TITLE
Dockerfile cleanup

### ISSUE THREAD

**Issue by dtolnay** [jqlang/jq#845]
Following up on #842:
- split into layers on natural boundaries (get dependencies, get code, build code and manual) to reduce rebuilding time
- factor long steps into shell scripts, maybe even reusable in .travis.yml
- enable valgrind if possible

**Comment by nicowilliams** [comment]
Can Travis-CI build a dockerfile?

**Comment by dtolnay** [comment]
Good idea. I will give it a shot tonight.

**Comment by dtolnay** [comment]
As far as I can tell, no, not on the container-based Travis infrastructure:
> It's not currently possible, mostly for security reasons, but is something we want to address in the future.

But Docker Hub can! https://docs.docker.com/docker-hub/builds/
