### ISSUE TITLE
Set O_CLOEXEC in MT-safe way

### ISSUE THREAD

**Issue by dtolnay** [jqlang/jq#867]
There is a glibc-specific implementation at #152.

**Comment by nicowilliams** [comment]
O_CLOEXEC is POSIX, only the "e" option for fopen() isn't.  I'll probably rework this someday.

I'm thinking that it'd be nice to have a `./configure --enable-mt` that builds a libjq-mt that uses atomics for managing reference counts.

**Comment by emanuele6** [comment]
jq does not set cloexec anywhere, and since it does not exec anywhere, it is unnecessary to `CLOEXEC` input and script files.
This issue is probably outdated
